---
title: "Debugging and defensive programming"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm007 - January 30, 2017

## Overview

* Define a bug
* Review best practices for reading, writing, and styling code
* Distinguish between errors, warnings, and messages
* Introduce `traceback()` and explain how to read it
* Identify methods for error handling and recovery
    * `try()`
    * `tryCatch()`
* Identify methods for error handling in `purrr` and `map()` functions

## Slides and links

* [Slides](extras/cm007_slides.html)
* [Debugging and defensive programming](block012_debugging.html)

* [Debugging, condition handling, and defensive programming in *Advanced R* by Hadley Wickham](http://adv-r.had.co.nz/Exceptions-Debugging.html)
* [Style in *Advanced R* by Hadley Wickham](http://adv-r.had.co.nz/Style.html)
* [21.6 Dealing with failure in *R for Data Science*](http://r4ds.had.co.nz/iteration.html#dealing-with-failure)
* [Defensive Programming & Debugging in R-Studio](https://cdn.rawgit.com/AnnArborRUserGroup/Presentations/f145727c9ea99b1c7c1581a4d3e816d7956a00e6/2016-02/reino-defensive-programming-debugging-R-Studio/Presentation-revealjs.html#/) - a slide presentation by Reino Bruner prepared for the Ann Arbor R Users Group


## To do for Wednesday

* Finish [homework 4](hw04-programming.html)
* Readings TBD

