---
title: "Data wrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm004 - January 18, 2017

## Overview

* Identify different types of vectors and how they can be read and parsed
* Define *tidy data* and its characteristics
* Explain relational data and its structure
* Define factors
* Practice tidying data

## Slides and links

* [Slides](extras/cm004_slides.html)
* [In-class practice exercise](https://gist.github.com/bensoltoff/509f4d56bd782fe8cef3d066700d6d28)
* [Solution set for in-class practice exercise](extras/cm004_tidy_tutorial.html)

* Chapters 9-13 from [R for Data Science](http://r4ds.had.co.nz/)
* Lohr. 2014. [For Big-Data Scientists, "Janitor Work" Is Key Hurdle to Insights.](http://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insights-is-janitor-work.html?_r=0) *New York Times*.

## To do for Monday

* Register your GitHub account for the class [**ADD GOOGLE LINK**] - all remaining homework assignments will be in **private repositories**. Private repos can only be seen and edited by members of our [course organization](https://github.com/uc-cfss). Once you register your GitHub account, I will invite you to join the course organization. If you don't register your account, you won't have access to any of the homework assignments.
* [Work on homework 2](hw02-explore-wrangle-data.html)
* Think about your topic for your [final project](project_description.html). If you want to do a group project, start identifying project partners or post on the [discussion board](https://github.com/uc-cfss/Discussion) to find classmates with similar interests.


