---
title: "Statistical learning: regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm009 - February 6, 2017

## Overview

* Define statistical learning
* Review the major goals of statistical learning
* Explain the difference between parametric and non-parametric methods
* Identify the difference between statistical learning and machine learning
* Introduce linear models and ordinary least squares regression
* Demonstrate how to estimate a linear model in R using `lm`
* Demonstrate how to extract model statistics using [`broom`](https://cran.r-project.org/web/packages/broom/index.html) and [`modelr`](https://github.com/hadley/modelr)

## Slides and links

* [Slides](extras/cm009_slides.html)
* [Statistical learning: the basics](stat001_statistical_learning.html)
* [Statistical learning: linear regression](stat002_linear_models.html)

* Chapters 2 and 3.1-3.3 in [*An Introduction to Statistical Learning*](http://link.springer.com.proxy.uchicago.edu/book/10.1007%2F978-1-4614-7138-7)
* Chapter 25 in [R for Data Science](http://r4ds.had.co.nz/)
* [Vignette on `broom`](https://cran.r-project.org/web/packages/broom/vignettes/broom.html)
* [Examples of estimating common statistical models in R](http://www.ats.ucla.edu/stat/dae/)

## To do for Wednesday

* [Finish homework 5](hw05-reproducible-research.html)
* Read chapters 4.1-3, 8.1, 8.2.2 in [*An Introduction to Statistical Learning*](http://link.springer.com.proxy.uchicago.edu/book/10.1007%2F978-1-4614-7138-7)
* Install the `titanic` package using the command `install.packages("titanic")`

