---
title: "Data wrangling: relational data and factors"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm006 - April 11, 2018

## Overview

* Introduce relational data
* Demonstrate how tables can be linked to one another
* Demonstrate methods in `dplyr` for linking and merging related tables
* Practice joining tables
* Define factors
* Demonstrate how to transform and reorder factors for visualizations
* Practice transforming factors

## Before class

* Read Chapters 13, 15 from [R for Data Science](http://r4ds.had.co.nz/)
    * Do not complete exercises 13.4.6.2-3 -- we will be completing these as in-class exercises

## Slides and links

* [Slides](extras/cm006_slides.html)
* [Relational data: a quick review](datawrangle_relational_data.html)
* [Practice using relational data](datawrangle_relational_data_exercise.html)
* [Practice transforming and visualizing factors](datawrangle_factors_exercise.html)

## What you need to do

* [Begin homework 3](hw03-wrangle-data.html)
