---
title: "Data wrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm004 - January 18, 2017

## Overview

* Define a vector
* Identify different types of vectors
* Demonstrate how vectors can be read and parsed
* Define tidy data and its characteristics
* Practice tidying data
* Introduce relational data
* Demonstrate how tables are linked to one another
* Demonstrate methods in `dplyr` for linking and merging related tables

## Slides and links

* [Slides](extras/cm004_slides.html)
* [Parsing vectors](block005_parsing_vectors.html)
* [Tidy data: principles and practice](block006_tidy_data.html)
* [Relational data: a fly by the seat of your pants introduction](block007_relational_data.html)

* Chapters 9-13, 15 from [R for Data Science](http://r4ds.had.co.nz/)
    * When you have time, come back and read chapters 14 and 16. These are especially helpful when you work on data frames which have columns that store text or date/time information.
* Lohr. 2014. [For Big-Data Scientists, "Janitor Work" Is Key Hurdle to Insights.](http://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insights-is-janitor-work.html?_r=0) *New York Times*.
    * [Data Carpentry](http://www.mimno.org/articles/carpentry/) - a response to the NYTimes article

## To do for Monday

* [Begin homework 3](hw03_wrangle_data.html)
* Read chapters 17-19 from [R for Data Science](http://r4ds.had.co.nz/)


