---
title: "A deep dive into R Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm008 - February 1, 2017

## Overview

* Review the importance of reproducibility in scientific research
* Identify the major components of R Markdown documents
* Explain how to use chunk options to customize output
* Demonstrate the value of caching
* Explain how to include in-line R code
* Introduce the different R Markdown document formats
* Practice writing R scripts (`.R`) versus R Markdown documents (`.Rmd`)

## Slides and links

* [R Markdown](block013_rmarkdown.html)

* Chapters 27, 29 in [R for Data Science](http://r4ds.had.co.nz) for more on R Markdown and document formats
* [Chapter 6](http://r4ds.had.co.nz/workflow-scripts.html) in *R for Data Science* for more info on scripts
* [R Markdown](http://rmarkdown.rstudio.com/) - the official site for R Markdown. Lots of great explanations of the different formats and options available for each one.
* [`pipeline-example`](https://github.com/uc-cfss/pipeline-example) - a repo demonstrating how to combine and use R scripts and R Markdown documents. I recommend you fork/clone the repo to your computer, then explore and execute the different files to see how everything works together.

## To do for Monday

* [Start homework 5](hw05-reproducible-research.html)
* Read chapters 2 and 3.1-3.3 in [*An Introduction to Statistical Learning*](http://link.springer.com.proxy.uchicago.edu/book/10.1007%2F978-1-4614-7138-7)
* Read chapter 25 in [R for Data Science](http://r4ds.had.co.nz/)
    * You can skim chapters 22-24 if you like. I personally am not a fan of how the book introduces statistical modeling, but you may find these chapters more intuitive. Regardless, we will cover the major packages and functions for estimating and visualizing models in class.

