---
title: "Statistical learning: regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm011 - April 30, 2017

## Overview

* Review the major goals of statistical learning
* Explain the difference between parametric and non-parametric methods
* Introduce linear models and ordinary least squares regression
* Demonstrate how to estimate a linear model in R using `lm()`
* Demonstrate how to extract model statistics using [`broom`](https://cran.r-project.org/web/packages/broom/index.html) and [`modelr`](https://github.com/hadley/modelr)
* Practice estimating and interpreting linear models
* Demonstrate the use of logistic regression for classification
* Identify methods for assessing classification model accuracy

## Before class

* Read chapters 22-25 in [R for Data Science](http://r4ds.had.co.nz/)
    * If you want a more rigorous introduction to the fundamentals of statistical learning and linear models, read chapters 2 and 3 in [*An Introduction to Statistical Learning*](http://link.springer.com.proxy.uchicago.edu/book/10.1007%2F978-1-4614-7138-7). However this text assumes a much stronger knowledge of math, probability, and statistics.
* Read/skim chapter 4.1-3 in [*An Introduction to Statistical Learning*](http://link.springer.com.proxy.uchicago.edu/book/10.1007%2F978-1-4614-7138-7)

## Slides and links

* [Slides](extras/cm011_slides.html)
* [Statistical learning: the basics](stat001_statistical_learning.html)
* [Linear regression](stat002_linear_models.html)
* [Logistic regression](stat003_logistic_regression.html)

* [Vignette on `broom`](https://cran.r-project.org/web/packages/broom/vignettes/broom.html)
* [Examples of estimating common statistical models in R](http://www.ats.ucla.edu/stat/dae/)

## What you need to do
