---
title: "Text analysis: classification and topic modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm018 - May 23, 2018

## Overview

* Define topic modeling
* Define a document-term matrix
* Use text as predictors for classification algorithms
* Explain Latent Dirichlet allocation and how this process works
* Demonstrate how to use LDA to recover topic structure from a known set of topics
* Demonstrate how to use LDA to recover topic structure from an unknown set of topics
* Identify methods for selecting the appropriate parameter for $k$

## Before class

* Read chapters 5-7 in [*Tidy Text Mining with R*](http://tidytextmining.com/)
* Read [Blei, D. M. (2012). Probabilistic topic models. *Communications of the ACM*, 55(4), 77-84.](http://cacm.acm.org/magazines/2012/4/147361-probabilistic-topic-models/fulltext)

## Slides and links

* [Slides](extras/cm018_slides.html)
* [Text analysis: supervised classification](text_classification.html)
* [Text analysis: topic modeling](text_topicmodels.html)

## To do for Monday

* [Start homework 9](hw09-text_analysis.html)

