---
title: "Getting data from the web: API access"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm015 - November 13, 2017

## Overview

* Identify multiple methods for obtaining data from the internet
* Define application program interface (API)
* Explain authentication keys and demonstrate secure methods for storing these keys
* Demonstrate how to use canned packages in R to access APIs
* Practice gathering data from Twitter API using the `rtweet` package in R
* Identify methods for writing functions to interact with APIs
* Define JSON and XML data structure and how to convert them to data frames
* Practice tidying messy JSON data objects using `purrr::map()`

## Before class

* Read [Getting data from the web: API access](webdata001_api.html)
* Read [Getting data from the web: writing API queries](webdata003_api_by_hand.html)

## Slides and links

* [Slides](extras/cm015_slides.html)
* [Practice getting data from the Twitter API](webdata002_twitter_exercise.html)
* [Simplifying lists with `purrr`](webdata004_simplifying_lists.html)

* [More install-and-play API packages for R](https://github.com/ropensci/webservices)
* [Documentation for `httr`](https://cran.r-project.org/web/packages/httr/)
* [Lot's more tutorials and practice with `purrr` and recursive lists](https://jennybc.github.io/purrr-tutorial/index.html)

## What you need to do
