---
title: "Text analysis: fundamentals and sentiment analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm017 - November 26, 2018

## Overview

* Identify the basic workflow for conducting text analysis
* Define sentiment analysis and review its use in academic research
* Define the tidy text format
* Demonstrate how to conduct sentiment analysis using tweets
* Explain how to generate and interpret a wordcloud

## Before class

* Read chapters 1-4 in [*Tidy Text Mining with R*](http://tidytextmining.com/)
* Read two blog posts by David Robinson (co-author of `tidytext`) analyzing [Donald J. Trump's twitter account](https://twitter.com/realdonaldtrump)
    * [Text analysis of Trump's tweets confirms he writes only the (angrier) Android half](http://varianceexplained.org/r/trump-tweets/)
    * [Trump's Android and iPhone tweets, one year later](http://varianceexplained.org/r/trump-followup/)
    * Regardless of your political affiliations, these are excellent examples demonstrating many of the key principles of reproducible research that we've learned in this course
        * R Markdown documents and knitting code with output
        * Retrieving data from APIs
        * Textual analysis with `tidytext`
        * Visualizations with `ggplot2`

## Slides and links

* [Slides](extras/cm017_slides.html)
* [Text analysis: basic workflow](text001_workflow.html)
* [Practicing `tidytext` with song titles](text002_song_titles_exercise.html)
* [Practicing sentiment analysis with Harry Potter](text003_harry_potter_exercise.html)

## What you need to do


