---
title: "Statistical learning: resampling and decision trees"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm016 - November 16, 2016

## Overview

* Define resampling methods
* Review the validation set approach using linear regression
* Explain leave-one-out cross-validation
* Explain $k$-fold cross-validation
* Demonstrate how to conduct cross-validation on generalized linear models
* Define a decision tree
* Demonstrate how to estimate a decision tree
* Define and estimate a random forest
* Introduce the `caret` package for statistical learning in R

## Slides and links

* [Notes from class](stat_learning02.html)
* [Slides](extras/cm016_slides.html)

* [The `caret` Package](https://topepo.github.io/caret/) - introductory book for the `caret` package. Tells you what models you can implement and all the nitty-gritty details to customize `train` for different cross-validation methods.

## To do for Monday

* [Start homework 8](hw08-statistical_learning.html)
* Final projects people! Get started on them.
    * [Starter repo for the project](https://github.com/uc-cfss/fp-template) - check this demo out of an R Markdown website. This is what you will start with in your final project repo.
    * [Rendered version of the template](https://uc-cfss.github.io/fp-template/)
    * [Clone your final project repo](https://classroom.github.com/assignment-invitations/9ebfcbb562ac99780788dd2ca9101986)

