<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Practice transforming college education (data)</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45631879-2', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 66px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 71px;
  margin-top: -71px;
}

.section h2 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h3 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h4 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h5 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h6 {
  padding-top: 71px;
  margin-top: -71px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Computing for the Social Sciences</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="faq.html">FAQ</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Practice transforming college education (data)</h1>

</div>


<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)</code></pre></div>
<p>The Department of Education collects <a href="https://collegescorecard.ed.gov/">annual statistics on colleges and universities in the United States</a>. I have included a subset of this data from 2013 in the <a href="https://github.com/uc-cfss/rcfss"><code>rcfss</code></a> library from GitHub. To install the package, run the command <code>devtools::install_github(&quot;uc-cfss/rcfss&quot;)</code> in the console.</p>
<blockquote>
<p>If you don’t already have the <code>devtools</code> library installed, you will get an error. Go back and install this first using <code>install.packages(&quot;devtools&quot;)</code>, then run <code>devtools::install_github(&quot;uc-cfss/rcfss&quot;)</code>.</p>
</blockquote>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(rcfss)
<span class="kw">data</span>(<span class="st">&quot;scorecard&quot;</span>)
<span class="kw">str</span>(scorecard)</code></pre></div>
<pre><code>## Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:    1849 obs. of  12 variables:
##  $ unitid   : int  450234 448479 456427 459596 459851 482477 482547 482592 482617 482662 ...
##  $ name     : chr  &quot;ITT Technical Institute-Wichita&quot; &quot;ITT Technical Institute-Swartz Creek&quot; &quot;ITT Technical Institute-Concord&quot; &quot;ITT Technical Institute-Tallahassee&quot; ...
##  $ state    : chr  &quot;KS&quot; &quot;MI&quot; &quot;CA&quot; &quot;FL&quot; ...
##  $ type     : chr  &quot;Private, for-profit&quot; &quot;Private, for-profit&quot; &quot;Private, for-profit&quot; &quot;Private, for-profit&quot; ...
##  $ cost     : int  28306 26994 26353 28894 23928 25625 24265 NA 20983 21999 ...
##  $ admrate  : num  81.3 98.3 89.3 58.4 68.8 ...
##  $ satavg   : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ avgfacsal: num  45054 52857 NA 47196 55089 ...
##  $ pctpell  : num  0.803 0.773 0.704 0.778 0.61 ...
##  $ comprate : num  0.6 0.336 NA NA NA ...
##  $ firstgen : num  0.506 0.506 0.506 0.506 0.517 ...
##  $ debt     : num  13000 13000 13000 13000 9500 ...</code></pre>
<p>Type <code>?scorecard</code> in the console to open up the help file for this data set. This includes the documentation for all the variables. Use your knowledge of the <code>dplyr</code> functions to perform the following tasks.</p>
<div id="generate-a-data-frame-of-schools-with-a-greater-than-40-share-of-first-generation-students" class="section level1">
<h1>Generate a data frame of schools with a greater than 40% share of first-generation students</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(scorecard, firstgen <span class="op">&gt;</span><span class="st"> </span>.<span class="dv">40</span>)</code></pre></div>
<pre><code>## # A tibble: 578 x 12
##    unitid                                 name state                type
##     &lt;int&gt;                                &lt;chr&gt; &lt;chr&gt;               &lt;chr&gt;
##  1 450234      ITT Technical Institute-Wichita    KS Private, for-profit
##  2 448479 ITT Technical Institute-Swartz Creek    MI Private, for-profit
##  3 456427      ITT Technical Institute-Concord    CA Private, for-profit
##  4 459596  ITT Technical Institute-Tallahassee    FL Private, for-profit
##  5 459851        Herzing University-Brookfield    WI Private, for-profit
##  6 482477            DeVry University-Illinois    IL Private, for-profit
##  7 482547              DeVry University-Nevada    NV Private, for-profit
##  8 482592              DeVry University-Oregon    OR Private, for-profit
##  9 482617           DeVry University-Tennessee    TN Private, for-profit
## 10 482662          DeVry University-Washington    WA Private, for-profit
## # ... with 568 more rows, and 8 more variables: cost &lt;int&gt;, admrate &lt;dbl&gt;,
## #   satavg &lt;dbl&gt;, avgfacsal &lt;dbl&gt;, pctpell &lt;dbl&gt;, comprate &lt;dbl&gt;,
## #   firstgen &lt;dbl&gt;, debt &lt;dbl&gt;</code></pre>
</p>
<p></details></p>
</div>
<div id="generate-a-data-frame-with-the-10-most-expensive-colleges-in-2013" class="section level1">
<h1>Generate a data frame with the 10 most expensive colleges in 2013</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># arrange the data frame by cost from highest to lowest and slice the first 10 rows</span>
<span class="kw">arrange</span>(scorecard, <span class="kw">desc</span>(cost)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>)</code></pre></div>
<pre><code>## # A tibble: 10 x 12
##    unitid                                        name state
##     &lt;int&gt;                                       &lt;chr&gt; &lt;chr&gt;
##  1 195304                      Sarah Lawrence College    NY
##  2 179867           Washington University in St Louis    MO
##  3 144050                       University of Chicago    IL
##  4 190150 Columbia University in the City of New York    NY
##  5 182670                           Dartmouth College    NH
##  6 130697                         Wesleyan University    CT
##  7 147767                     Northwestern University    IL
##  8 120254                          Occidental College    CA
##  9 115409                         Harvey Mudd College    CA
## 10 230816                          Bennington College    VT
## # ... with 9 more variables: type &lt;chr&gt;, cost &lt;int&gt;, admrate &lt;dbl&gt;,
## #   satavg &lt;dbl&gt;, avgfacsal &lt;dbl&gt;, pctpell &lt;dbl&gt;, comprate &lt;dbl&gt;,
## #   firstgen &lt;dbl&gt;, debt &lt;dbl&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># use the top_n function</span>
<span class="kw">top_n</span>(scorecard, <span class="dv">10</span>, <span class="dt">wt =</span> cost)</code></pre></div>
<pre><code>## # A tibble: 10 x 12
##    unitid                                        name state
##     &lt;int&gt;                                       &lt;chr&gt; &lt;chr&gt;
##  1 120254                          Occidental College    CA
##  2 195304                      Sarah Lawrence College    NY
##  3 115409                         Harvey Mudd College    CA
##  4 130697                         Wesleyan University    CT
##  5 147767                     Northwestern University    IL
##  6 144050                       University of Chicago    IL
##  7 230816                          Bennington College    VT
##  8 182670                           Dartmouth College    NH
##  9 179867           Washington University in St Louis    MO
## 10 190150 Columbia University in the City of New York    NY
## # ... with 9 more variables: type &lt;chr&gt;, cost &lt;int&gt;, admrate &lt;dbl&gt;,
## #   satavg &lt;dbl&gt;, avgfacsal &lt;dbl&gt;, pctpell &lt;dbl&gt;, comprate &lt;dbl&gt;,
## #   firstgen &lt;dbl&gt;, debt &lt;dbl&gt;</code></pre>
</p>
<p></details></p>
</div>
<div id="generate-a-data-frame-with-the-average-sat-score-for-each-type-of-college" class="section level1">
<h1>Generate a data frame with the average SAT score for each type of college</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scorecard <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(type) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_sat =</span> <span class="kw">mean</span>(satavg, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</code></pre></div>
<pre><code>## # A tibble: 3 x 2
##                  type mean_sat
##                 &lt;chr&gt;    &lt;dbl&gt;
## 1 Private, for-profit 1002.500
## 2  Private, nonprofit 1075.287
## 3              Public 1037.410</code></pre>
</p>
<p></details></p>
</div>
<div id="calculate-for-each-school-how-many-students-it-takes-to-pay-the-average-faculty-members-salary-and-generate-a-data-frame-with-the-schools-name-and-the-calculated-value" class="section level1">
<h1>Calculate for each school how many students it takes to pay the average faculty member’s salary and generate a data frame with the school’s name and the calculated value</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scorecard <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ratio =</span> avgfacsal <span class="op">/</span><span class="st"> </span>cost) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(name, ratio)</code></pre></div>
<pre><code>## # A tibble: 1,849 x 2
##                                    name    ratio
##                                   &lt;chr&gt;    &lt;dbl&gt;
##  1      ITT Technical Institute-Wichita 1.591677
##  2 ITT Technical Institute-Swartz Creek 1.958102
##  3      ITT Technical Institute-Concord       NA
##  4  ITT Technical Institute-Tallahassee 1.633419
##  5        Herzing University-Brookfield 2.302282
##  6            DeVry University-Illinois 2.450459
##  7              DeVry University-Nevada 1.959860
##  8              DeVry University-Oregon       NA
##  9           DeVry University-Tennessee 2.461993
## 10          DeVry University-Washington 2.552843
## # ... with 1,839 more rows</code></pre>
</p>
<p></details></p>
</div>
<div id="calculate-how-many-private-nonprofit-schools-have-a-smaller-cost-than-the-university-of-chicago" class="section level1">
<h1>Calculate how many private, nonprofit schools have a smaller cost than the University of Chicago</h1>
<p>Hint: the result should be a data frame with one row for the University of Chicago, and a column containing the requested value.</p>
<div id="report-the-number-as-the-total-number-of-schools" class="section level2">
<h2>Report the number as the total number of schools</h2>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scorecard <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(type <span class="op">==</span><span class="st"> &quot;Private, nonprofit&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(cost) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">school_cheaper =</span> <span class="kw">row_number</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(name <span class="op">==</span><span class="st"> &quot;University of Chicago&quot;</span>)</code></pre></div>
<pre><code>## # A tibble: 1 x 13
##   unitid                  name state               type  cost admrate
##    &lt;int&gt;                 &lt;chr&gt; &lt;chr&gt;              &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt;
## 1 144050 University of Chicago    IL Private, nonprofit 62425    8.81
## # ... with 7 more variables: satavg &lt;dbl&gt;, avgfacsal &lt;dbl&gt;, pctpell &lt;dbl&gt;,
## #   comprate &lt;dbl&gt;, firstgen &lt;dbl&gt;, debt &lt;dbl&gt;, school_cheaper &lt;int&gt;</code></pre>
</p>
<p></details></p>
</div>
<div id="report-the-number-as-the-percentage-of-schools" class="section level2">
<h2>Report the number as the percentage of schools</h2>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scorecard <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(type <span class="op">==</span><span class="st"> &quot;Private, nonprofit&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">cost_rank =</span> <span class="kw">percent_rank</span>(cost)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(name <span class="op">==</span><span class="st"> &quot;University of Chicago&quot;</span>)</code></pre></div>
<pre><code>## # A tibble: 1 x 13
##   unitid                  name state               type  cost admrate
##    &lt;int&gt;                 &lt;chr&gt; &lt;chr&gt;              &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt;
## 1 144050 University of Chicago    IL Private, nonprofit 62425    8.81
## # ... with 7 more variables: satavg &lt;dbl&gt;, avgfacsal &lt;dbl&gt;, pctpell &lt;dbl&gt;,
## #   comprate &lt;dbl&gt;, firstgen &lt;dbl&gt;, debt &lt;dbl&gt;, cost_rank &lt;dbl&gt;</code></pre>
</p>
<p></details></p>
</div>
</div>
<div id="session-info" class="section level1 toc-ignore">
<h1>Session Info</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">devtools<span class="op">::</span><span class="kw">session_info</span>()</code></pre></div>
<pre><code>## Session info -------------------------------------------------------------</code></pre>
<pre><code>##  setting  value                       
##  version  R version 3.4.1 (2017-06-30)
##  system   x86_64, darwin15.6.0        
##  ui       X11                         
##  language (EN)                        
##  collate  en_US.UTF-8                 
##  tz       America/Chicago             
##  date     2017-08-01</code></pre>
<pre><code>## Packages -----------------------------------------------------------------</code></pre>
<pre><code>##  package    * version    date       source                              
##  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                      
##  backports    1.1.0      2017-05-22 CRAN (R 3.4.0)                      
##  base       * 3.4.1      2017-07-07 local                               
##  bindr        0.1        2016-11-13 CRAN (R 3.4.0)                      
##  bindrcpp     0.2        2017-06-17 CRAN (R 3.4.0)                      
##  boxes        0.0.0.9000 2017-07-19 Github (r-pkgs/boxes@03098dc)       
##  broom      * 0.4.2      2017-02-13 CRAN (R 3.4.0)                      
##  cellranger   1.1.0      2016-07-27 CRAN (R 3.4.0)                      
##  clisymbols   1.2.0      2017-05-21 cran (@1.2.0)                       
##  colorspace   1.3-2      2016-12-14 CRAN (R 3.4.0)                      
##  compiler     3.4.1      2017-07-07 local                               
##  crayon       1.3.2.9000 2017-07-19 Github (gaborcsardi/crayon@750190f) 
##  datasets   * 3.4.1      2017-07-07 local                               
##  devtools     1.13.2     2017-06-02 CRAN (R 3.4.0)                      
##  digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                      
##  dplyr      * 0.7.2      2017-07-20 CRAN (R 3.4.1)                      
##  evaluate     0.10.1     2017-06-24 CRAN (R 3.4.1)                      
##  forcats    * 0.2.0      2017-01-23 CRAN (R 3.4.0)                      
##  foreign      0.8-69     2017-06-22 CRAN (R 3.4.1)                      
##  gganimate  * 0.1.0.9000 2017-05-26 Github (dgrtwo/gganimate@bf82002)   
##  ggplot2    * 2.2.1      2016-12-30 CRAN (R 3.4.0)                      
##  glue         1.1.1      2017-06-21 CRAN (R 3.4.1)                      
##  graphics   * 3.4.1      2017-07-07 local                               
##  grDevices  * 3.4.1      2017-07-07 local                               
##  grid         3.4.1      2017-07-07 local                               
##  gtable       0.2.0      2016-02-26 CRAN (R 3.4.0)                      
##  haven        1.1.0      2017-07-09 CRAN (R 3.4.1)                      
##  hms          0.3        2016-11-22 CRAN (R 3.4.0)                      
##  htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)                      
##  httr         1.2.1      2016-07-03 CRAN (R 3.4.0)                      
##  jsonlite     1.5        2017-06-01 CRAN (R 3.4.0)                      
##  knitr      * 1.16       2017-05-18 CRAN (R 3.4.0)                      
##  lattice      0.20-35    2017-03-25 CRAN (R 3.4.1)                      
##  lazyeval     0.2.0      2016-06-12 CRAN (R 3.4.0)                      
##  lubridate    1.6.0      2016-09-13 CRAN (R 3.4.0)                      
##  magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                      
##  memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                      
##  methods      3.4.1      2017-07-07 local                               
##  mnormt       1.5-5      2016-10-15 CRAN (R 3.4.0)                      
##  modelr       0.1.1      2017-07-24 CRAN (R 3.4.1)                      
##  munsell      0.4.3      2016-02-13 CRAN (R 3.4.0)                      
##  nlme         3.1-131    2017-02-06 CRAN (R 3.4.1)                      
##  parallel     3.4.1      2017-07-07 local                               
##  pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.0)                      
##  plyr         1.8.4      2016-06-08 CRAN (R 3.4.0)                      
##  psych        1.7.5      2017-05-03 CRAN (R 3.4.1)                      
##  purrr      * 0.2.2.2    2017-05-11 CRAN (R 3.4.0)                      
##  R6           2.2.2      2017-06-17 CRAN (R 3.4.0)                      
##  rcfss      * 0.1.5      2017-07-31 local                               
##  Rcpp         0.12.12    2017-07-15 CRAN (R 3.4.1)                      
##  readr      * 1.1.1      2017-05-16 CRAN (R 3.4.0)                      
##  readxl       1.0.0      2017-04-18 CRAN (R 3.4.0)                      
##  reshape2     1.4.2      2016-10-22 CRAN (R 3.4.0)                      
##  rlang        0.1.1      2017-05-18 CRAN (R 3.4.0)                      
##  rmarkdown    1.6        2017-06-15 CRAN (R 3.4.0)                      
##  rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)                      
##  rstudioapi   0.6        2016-06-27 CRAN (R 3.4.0)                      
##  rvest        0.3.2      2016-06-17 CRAN (R 3.4.0)                      
##  scales       0.4.1      2016-11-09 CRAN (R 3.4.0)                      
##  stats      * 3.4.1      2017-07-07 local                               
##  stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                      
##  stringr    * 1.2.0      2017-02-18 CRAN (R 3.4.0)                      
##  tibble     * 1.3.3      2017-05-28 CRAN (R 3.4.0)                      
##  tidyr      * 0.6.3      2017-05-15 CRAN (R 3.4.0)                      
##  tidyverse  * 1.1.1.9000 2017-07-19 Github (tidyverse/tidyverse@a028619)
##  tools        3.4.1      2017-07-07 local                               
##  tweenr     * 0.1.5      2016-10-10 CRAN (R 3.4.0)                      
##  utils      * 3.4.1      2017-07-07 local                               
##  withr        2.0.0      2017-07-28 CRAN (R 3.4.1)                      
##  xml2         1.1.1      2017-01-24 CRAN (R 3.4.0)                      
##  yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)</code></pre>
</div>

<p>This work is licensed under the  <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 Creative Commons License</a>.</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
