<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Practice transforming and visualizing factors</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45631879-2', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 66px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 71px;
  margin-top: -71px;
}

.section h2 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h3 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h4 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h5 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h6 {
  padding-top: 71px;
  margin-top: -71px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Computing for the Social Sciences</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="faq.html">FAQ</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Practice transforming and visualizing factors</h1>

</div>


<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(knitr)
<span class="kw">library</span>(rcfss)
<span class="kw">theme_set</span>(<span class="kw">theme_minimal</span>())

<span class="co"># load the data</span>
<span class="kw">data</span>(<span class="st">&quot;gun_deaths&quot;</span>)
gun_deaths</code></pre></div>
<pre><code>## # A tibble: 100,798 x 10
##       id  year month intent       police sex     age race  place education
##    &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; &lt;fct&gt;    
##  1     1  2012    1. Suicide           0 M        34 Asia… Home  BA+      
##  2     2  2012    1. Suicide           0 F        21 White Stre… Some col…
##  3     3  2012    1. Suicide           0 M        60 White Othe… BA+      
##  4     4  2012    2. Suicide           0 M        64 White Home  BA+      
##  5     5  2012    2. Suicide           0 M        31 White Othe… HS/GED   
##  6     6  2012    2. Suicide           0 M        17 Nati… Home  Less tha…
##  7     7  2012    2. Undetermined      0 M        48 White Home  HS/GED   
##  8     8  2012    3. Suicide           0 M        41 Nati… Home  HS/GED   
##  9     9  2012    2. Accidental        0 M        50 White Othe… Some col…
## 10    10  2012    2. Suicide           0 M        NA Black Home  &lt;NA&gt;     
## # ... with 100,788 more rows</code></pre>
<div id="convert-month-into-a-factor-column" class="section level1">
<h1>Convert <code>month</code> into a factor column</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">month_levels &lt;-<span class="st"> </span><span class="kw">c</span>(
  <span class="st">&quot;Jan&quot;</span>, <span class="st">&quot;Feb&quot;</span>, <span class="st">&quot;Mar&quot;</span>, <span class="st">&quot;Apr&quot;</span>, <span class="st">&quot;May&quot;</span>, <span class="st">&quot;Jun&quot;</span>, 
  <span class="st">&quot;Jul&quot;</span>, <span class="st">&quot;Aug&quot;</span>, <span class="st">&quot;Sep&quot;</span>, <span class="st">&quot;Oct&quot;</span>, <span class="st">&quot;Nov&quot;</span>, <span class="st">&quot;Dec&quot;</span>
)

<span class="co"># or use the built-in constant</span>
month.abb</code></pre></div>
<pre><code>##  [1] &quot;Jan&quot; &quot;Feb&quot; &quot;Mar&quot; &quot;Apr&quot; &quot;May&quot; &quot;Jun&quot; &quot;Jul&quot; &quot;Aug&quot; &quot;Sep&quot; &quot;Oct&quot; &quot;Nov&quot;
## [12] &quot;Dec&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(gun_deaths &lt;-<span class="st"> </span>gun_deaths <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">month =</span> <span class="kw">factor</span>(month, <span class="dt">levels =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">1</span>, <span class="dt">to =</span> <span class="dv">12</span>), <span class="dt">labels =</span> month_levels)))</code></pre></div>
<pre><code>## # A tibble: 100,798 x 10
##       id  year month intent       police sex     age race  place education
##    &lt;int&gt; &lt;int&gt; &lt;fct&gt; &lt;chr&gt;         &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; &lt;fct&gt;    
##  1     1  2012 Jan   Suicide           0 M        34 Asia… Home  BA+      
##  2     2  2012 Jan   Suicide           0 F        21 White Stre… Some col…
##  3     3  2012 Jan   Suicide           0 M        60 White Othe… BA+      
##  4     4  2012 Feb   Suicide           0 M        64 White Home  BA+      
##  5     5  2012 Feb   Suicide           0 M        31 White Othe… HS/GED   
##  6     6  2012 Feb   Suicide           0 M        17 Nati… Home  Less tha…
##  7     7  2012 Feb   Undetermined      0 M        48 White Home  HS/GED   
##  8     8  2012 Mar   Suicide           0 M        41 Nati… Home  HS/GED   
##  9     9  2012 Feb   Accidental        0 M        50 White Othe… Some col…
## 10    10  2012 Feb   Suicide           0 M        NA Black Home  &lt;NA&gt;     
## # ... with 100,788 more rows</code></pre>
</p>
<p></details></p>
</div>
<div id="visualize-the-total-gun-deaths-per-month-in-chronological-order" class="section level1">
<h1>Visualize the total gun deaths per month, in chronological order</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(gun_deaths, <span class="kw">aes</span>(month)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Gun Deaths in the United States (2012-2014)&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Month&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Number of gun deaths&quot;</span>)</code></pre></div>
<p><img src="datawrangle_factors_exercise_files/figure-html/month-deaths-1.png" width="672" /></p>
</p>
<p></details></p>
</div>
<div id="visualize-the-total-gun-deaths-per-month-sorted-from-lowest-to-highest" class="section level1">
<h1>Visualize the total gun deaths per month, sorted from lowest to highest</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># with geom_col() and fct_reorder()</span>
gun_deaths <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(month) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="kw">fct_reorder</span>(month, n), n)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Gun Deaths in the United States (2012-2014)&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Month&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Number of gun deaths&quot;</span>)</code></pre></div>
<p><img src="datawrangle_factors_exercise_files/figure-html/month-deaths-sort-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># with geom_bar() and fct_infreq()</span>
<span class="kw">ggplot</span>(gun_deaths, <span class="kw">aes</span>(month <span class="op">%&gt;%</span>
<span class="st">                         </span><span class="kw">fct_infreq</span>() <span class="op">%&gt;%</span>
<span class="st">                         </span><span class="kw">fct_rev</span>())) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Gun Deaths in the United States (2012-2014)&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Month&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Number of gun deaths&quot;</span>)</code></pre></div>
<p><img src="datawrangle_factors_exercise_files/figure-html/month-deaths-sort-2.png" width="672" /></p>
</p>
<p></details></p>
</div>
<div id="visualize-the-frequency-of-intent-of-gun-deaths-using-a-bar-chart-sorted-from-most-to-least-frequent" class="section level1">
<h1>Visualize the frequency of intent of gun deaths using a bar chart, sorted from most to least frequent</h1>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">intent_levels &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Accidental&quot;</span>, <span class="st">&quot;Homicide&quot;</span>, <span class="st">&quot;Suicide&quot;</span>, <span class="st">&quot;Undetermined&quot;</span>)

gun_deaths <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(intent)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">intent =</span> <span class="kw">parse_factor</span>(intent, <span class="dt">levels =</span> intent_levels)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(intent <span class="op">%&gt;%</span>
<span class="st">               </span><span class="kw">fct_infreq</span>() <span class="op">%&gt;%</span>
<span class="st">               </span><span class="kw">fct_rev</span>())) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Gun Deaths in the United States (2012-2014)&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Intent of death&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Number of gun deaths&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="datawrangle_factors_exercise_files/figure-html/intent-1.png" width="672" /></p>
</p>
<p></details></p>
</div>
<div id="visualize-total-gun-deaths-by-season-of-the-year-using-a-bar-chart." class="section level1">
<h1>Visualize total gun deaths by season of the year using a bar chart.</h1>
<p>Hint: do not use <code>cut()</code> to create the <code>season</code> column.</p>
<details> <summary>Click for the solution</summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gun_deaths <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">season =</span> <span class="kw">fct_collapse</span>(month,
                               <span class="st">&quot;Winter&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Jan&quot;</span>, <span class="st">&quot;Feb&quot;</span>, <span class="st">&quot;Mar&quot;</span>),
                               <span class="st">&quot;Spring&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Apr&quot;</span>, <span class="st">&quot;May&quot;</span>, <span class="st">&quot;Jun&quot;</span>),
                               <span class="st">&quot;Summer&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Jul&quot;</span>, <span class="st">&quot;Aug&quot;</span>, <span class="st">&quot;Sep&quot;</span>),
                               <span class="st">&quot;Fall&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Oct&quot;</span>, <span class="st">&quot;Nov&quot;</span>, <span class="st">&quot;Dec&quot;</span>))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(season)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Gun Deaths in the United States (2012-2014)&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Season&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Number of gun deaths&quot;</span>)</code></pre></div>
<p><img src="datawrangle_factors_exercise_files/figure-html/season-1.png" width="672" /></p>
</p>
<p></details></p>
</div>
<div id="session-info" class="section level1 toc-ignore">
<h1>Session Info</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">devtools<span class="op">::</span><span class="kw">session_info</span>()</code></pre></div>
<pre><code>## Session info -------------------------------------------------------------</code></pre>
<pre><code>##  setting  value                       
##  version  R version 3.4.3 (2017-11-30)
##  system   x86_64, darwin15.6.0        
##  ui       RStudio (1.1.447)           
##  language (EN)                        
##  collate  en_US.UTF-8                 
##  tz       America/Chicago             
##  date     2018-05-23</code></pre>
<pre><code>## Packages -----------------------------------------------------------------</code></pre>
<pre><code>##  package        * version    date      
##  abind            1.4-5      2016-07-21
##  assertthat       0.2.0      2017-04-11
##  babynames      * 0.3.0      2017-04-14
##  backports        1.1.2      2017-12-13
##  base           * 3.4.3      2017-12-07
##  base64enc        0.1-3      2015-07-28
##  bigrquery      * 0.4.1      2017-06-26
##  bindr            0.1.1      2018-03-13
##  bindrcpp       * 0.2.2      2018-03-29
##  bit              1.1-12     2014-04-09
##  bit64            0.9-7      2017-05-08
##  bitops           1.0-6      2013-08-17
##  blob             1.1.1      2018-03-25
##  boot           * 1.3-20     2017-08-06
##  broom          * 0.4.4      2018-03-29
##  callr            2.0.3      2018-04-11
##  caret          * 6.0-79     2018-03-29
##  cellranger       1.1.0      2016-07-27
##  class            7.3-14     2015-08-30
##  cli              1.0.0      2017-11-05
##  clipr            0.4.0      2017-11-03
##  codetools        0.2-15     2016-10-05
##  colorspace       1.3-2      2016-12-14
##  compiler         3.4.3      2017-12-07
##  config           0.3        2018-03-27
##  crayon           1.3.4      2017-10-03
##  curl           * 3.2        2018-03-28
##  CVST             0.2-1      2013-12-10
##  datasets       * 3.4.3      2017-12-07
##  DBI              0.8        2018-03-02
##  dbplyr           1.2.1      2018-02-19
##  ddalpha          1.3.2      2018-04-08
##  debugme          1.1.0      2017-10-22
##  DEoptimR         1.0-8      2016-11-19
##  devtools         1.13.5     2018-02-18
##  digest           0.6.15     2018-01-28
##  dimRed           0.1.0      2017-05-04
##  dplyr          * 0.7.4      2017-09-28
##  DRR              0.0.3      2018-01-06
##  e1071          * 1.6-8      2017-02-02
##  emo              0.0.0.9000 2017-10-03
##  evaluate         0.10.1     2017-06-24
##  FNN            * 1.1        2013-07-31
##  forcats        * 0.3.0      2018-02-19
##  foreach        * 1.4.4      2017-12-12
##  foreign          0.8-69     2017-06-22
##  gam            * 1.15       2018-02-25
##  gapminder      * 0.3.0      2017-10-31
##  gbm            * 2.1.3      2017-03-21
##  geometry         0.3-6      2015-09-09
##  geosphere        1.5-7      2017-11-05
##  gganimate      * 0.1.0.9000 2017-05-26
##  ggmap          * 2.6.1      2016-01-23
##  ggplot2        * 2.2.1.9000 2018-05-18
##  ggrepel        * 0.7.0      2017-09-29
##  ggstance       * 0.3        2016-11-16
##  glue             1.2.0      2017-10-29
##  gower            0.1.2      2017-02-23
##  graphics       * 3.4.3      2017-12-07
##  grDevices      * 3.4.3      2017-12-07
##  grid             3.4.3      2017-12-07
##  gridExtra      * 2.3        2017-09-09
##  gtable           0.2.0      2016-02-26
##  gutenbergr     * 0.1.4      2018-01-26
##  h2o            * 3.16.0.2   2017-12-01
##  haven          * 1.1.1      2018-01-18
##  here           * 0.1        2017-05-28
##  hexbin         * 1.27.2     2018-01-15
##  highr            0.6        2016-05-09
##  hms              0.4.2      2018-03-10
##  htmltools        0.3.6      2017-04-28
##  htmlwidgets      1.2        2018-04-19
##  httpuv           1.3.6.2    2018-03-02
##  httr           * 1.3.1      2017-08-20
##  igraph           1.2.1      2018-03-10
##  ipred            0.9-6      2017-03-01
##  ISLR           * 1.2        2017-10-20
##  iterators        1.0.9      2017-12-12
##  janeaustenr      0.1.5      2017-06-10
##  jpeg             0.1-8      2014-01-23
##  jsonlite       * 1.5        2017-06-01
##  kernlab          0.9-25     2016-10-03
##  kknn           * 1.3.1      2016-03-26
##  knitr          * 1.20       2018-02-20
##  labeling         0.3        2014-08-23
##  lattice        * 0.20-35    2017-03-25
##  lava             1.6.1      2018-03-28
##  lazyeval         0.2.1      2017-10-29
##  lubridate      * 1.7.4      2018-04-11
##  lvplot         * 0.2.0      2016-05-01
##  magic            1.5-8      2018-01-26
##  magrittr         1.5        2014-11-22
##  mapproj          1.2.6      2018-03-29
##  maps           * 3.3.0      2018-04-03
##  MASS             7.3-49     2018-02-23
##  Matrix           1.2-14     2018-04-09
##  MatrixModels   * 0.4-1      2015-08-22
##  memoise          1.1.0      2017-04-21
##  methods        * 3.4.3      2017-12-07
##  microbenchmark * 1.4-4      2018-01-24
##  mime             0.5        2016-07-07
##  miniUI           0.1.1      2016-01-15
##  mnormt           1.5-5      2016-10-15
##  ModelMetrics     1.1.0      2016-08-26
##  modelr         * 0.1.1      2017-08-10
##  modeltools       0.2-21     2013-09-02
##  munsell          0.4.3      2016-02-13
##  nlme             3.1-137    2018-04-07
##  NLP              0.1-11     2017-08-15
##  nnet           * 7.3-12     2016-02-02
##  nycflights13   * 0.2.2      2017-01-27
##  openssl          1.0.1      2018-03-03
##  parallel       * 3.4.3      2017-12-07
##  pillar           1.2.1      2018-02-27
##  pkgconfig        2.0.1      2017-03-21
##  plyr             1.8.4      2016-06-08
##  png              0.1-7      2013-12-03
##  pROC           * 1.11.0     2018-03-25
##  prodlim          1.6.1      2017-03-06
##  profvis        * 0.3.5      2018-02-22
##  proto            1.0.0      2016-10-29
##  psych            1.8.3.3    2018-03-30
##  purrr          * 0.2.4      2017-10-18
##  quantreg       * 5.35       2018-02-02
##  R6               2.2.2      2017-06-17
##  randomForest   * 4.6-14     2018-03-25
##  rappdirs         0.3.1      2016-03-28
##  rcfss          * 0.1.5      2018-05-01
##  Rcpp             0.12.16    2018-03-13
##  RcppRoll         0.2.2      2015-04-05
##  RCurl            1.95-4.10  2018-01-04
##  readr          * 1.1.1      2017-05-16
##  readxl         * 1.0.0      2017-04-18
##  rebird         * 0.4.0      2017-04-26
##  recipes          0.1.2      2018-01-11
##  reprex         * 0.2.0      2018-04-09
##  reshape2         1.4.3      2017-12-11
##  RgoogleMaps      1.4.1      2016-09-18
##  rjson            0.2.15     2014-11-03
##  rlang            0.2.0.9001 2018-05-18
##  rmarkdown        1.9        2018-03-01
##  robustbase       0.92-8     2017-11-01
##  rpart            4.1-13     2018-02-23
##  rprojroot        1.3-2      2018-01-03
##  rsconnect        0.8.8      2018-03-09
##  rsparkling     * 0.2.3      2018-03-08
##  RSQLite        * 2.1.0      2018-03-29
##  rstudioapi       0.7        2017-09-07
##  rtweet         * 0.6.0      2017-11-16
##  rvest          * 0.3.2      2016-06-17
##  scales         * 0.5.0.9000 2018-05-18
##  sfsmisc          1.1-2      2018-03-05
##  shiny          * 1.0.5      2017-08-23
##  slam             0.1-42     2017-12-21
##  SnowballC        0.5.1      2014-08-09
##  sp               1.2-7      2018-01-19
##  sparklyr       * 0.7.0      2018-01-23
##  SparseM        * 1.77       2017-04-23
##  splines        * 3.4.3      2017-12-07
##  stats          * 3.4.3      2017-12-07
##  stats4           3.4.3      2017-12-07
##  stringi          1.1.7      2018-03-12
##  stringr        * 1.3.0      2018-02-19
##  survival       * 2.41-3     2017-04-04
##  tibble         * 1.4.2      2018-01-22
##  tidyr          * 0.8.0      2018-01-29
##  tidyselect       0.2.4      2018-02-26
##  tidytext       * 0.1.8.900  2018-05-10
##  tidyverse      * 1.2.1      2017-11-14
##  timeDate         3043.102   2018-02-21
##  titanic        * 0.1.0      2015-08-31
##  tm               0.7-3      2017-12-06
##  tokenizers       0.2.1      2018-03-29
##  tools            3.4.3      2017-12-07
##  topicmodels    * 0.2-7      2017-11-03
##  tree           * 1.0-39     2018-03-17
##  tweenr         * 0.1.5      2016-10-10
##  utf8             1.1.3      2018-01-03
##  utils          * 3.4.3      2017-12-07
##  whisker          0.3-2      2013-04-28
##  withr            2.1.2      2018-05-18
##  XML            * 3.98-1.10  2018-02-19
##  xml2           * 1.2.0      2018-01-24
##  xtable           1.8-2      2016-02-05
##  yaml             2.1.18     2018-03-08
##  source                              
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  local                               
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.1)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  local                               
##  CRAN (R 3.4.4)                      
##  Github (gaborcsardi/crayon@b5221ab) 
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  local                               
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  Github (hadley/emo@9f2e0f2)         
##  CRAN (R 3.4.1)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.2)                      
##  Github (dgrtwo/gganimate@bf82002)   
##  CRAN (R 3.4.0)                      
##  Github (tidyverse/ggplot2@54de616)  
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.0)                      
##  local                               
##  local                               
##  local                               
##  CRAN (R 3.4.1)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  cran (@1.2)                         
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.1)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  local                               
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  local                               
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.1)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  local                               
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  local                               
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  Github (tidyverse/reprex@781696d)   
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.0)                      
##  Github (r-lib/rlang@854174a)        
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.1)                      
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.0)                      
##  Github (hadley/scales@d767915)      
##  CRAN (R 3.4.4)                      
##  cran (@1.0.5)                       
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  local                               
##  local                               
##  local                               
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  Github (juliasilge/tidytext@b6c4ed7)
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.4)                      
##  local                               
##  CRAN (R 3.4.2)                      
##  CRAN (R 3.4.4)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.3)                      
##  local                               
##  CRAN (R 3.4.0)                      
##  Github (jimhester/withr@79d7b0d)    
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.3)                      
##  CRAN (R 3.4.0)                      
##  CRAN (R 3.4.4)</code></pre>
</div>

<p>This work is licensed under the  <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 Creative Commons License</a>.</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
