---
title: "FAQ"
output:
  html_document:
    toc: true
    toc_depth: 2
---

# Should I take this course?

This course is open to any graduate (or advanced undergraduate) at UChicago. I anticipate drawing students from a wide range of departments such as Sociology, Psychology, Political Science, Comparative Human Development, and MAPSS. Typically these students are looking to learn basic computational and analytical skills they can apply to master's theses or dissertation research.

If you have never programmed before or don't even know what the [shell](shell.html) is, **prepare for a shock**. This class will prove to be immensely beneficial if you stick with it, but that will require you to commit for the full 10 weeks. I do not presume any prior programming experience, so everyone starts from the same knowledge level. I guarantee that the first few weeks and assignments will be rough - but the good news is that they will be rough for everyone! Your classmates are struggling with you and you can lean on one another to get through the worst part of the learning curve.

# What do I need for this course?

**You will need to bring a computer to class each day.** Class sessions are a mix of lecture, demonstration, and live coding. It is essential to have a computer so you can follow along and complete the exercises.

## Textbooks/Readings

* [R for Data Science](http://r4ds.had.co.nz/) -- Garrett Grolemund and Hadley Wickham. Hardcover to be published late 2016, but an open-source online version is available now.
* [An Introduction to Statistical Learning: with Applications in R](http://www-bcf.usc.edu/~gareth/ISL/) -- Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani. [Hardcover is available online for around $70.](https://www.amazon.com/Introduction-Statistical-Learning-Applications-Statistics/dp/1461471370) Authenticated UChicago students can purchase a [softcover black-and-white edition for $25](http://link.springer.com.proxy.uchicago.edu/book/10.1007%2F978-1-4614-7138-7)^[I don't recommend this since many of the figures rely on the use of color.] or download a PDF copy of the entire book for free at the previous link. Non-UChicago students can find a free PDF of the entire book [from the authors' site.](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)

### Optional

* [ggplot2: Elegant Graphics for Data Analysis, 2nd Edition](http://link.springer.com.proxy.uchicago.edu/book/10.1007/978-3-319-24277-4) -- Hadley Wickham. Excellent resource for the [`ggplot2`](https://cran.r-project.org/web/packages/ggplot2/index.html) graphics library.
* [Advanced R](http://adv-r.had.co.nz/) -- Hadley Wickham. Hardcover available online for around $55, but the online version is free. A deep dive into R as a programming language, not just a tool for data science. We will use some chapters in class, but most of this material is best covered on your own after completion of this course.
* [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/) - printable cheat sheets for common R tasks and features, such as [data wrangling](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf), [data visualization](https://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf), [base R functions](https://www.rstudio.com/wp-content/uploads/2016/06/r-cheat-sheet.pdf), and even the [RStudio IDE itself](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf).

## Software

By the end of the first week (or even better, before the course starts), you should install the following software on your computer:

* [R](https://www.r-project.org/) - easiest approach is to select [a pre-compiled binary appropriate for your operating system](https://cran.rstudio.com/).
* [RStudio's IDE](https://www.rstudio.com/products/RStudio/) - this is a powerful user interface for programming in R. You could use base R, but you would regret it.
* [Git](https://git-scm.com/) - Git is a [version control system](https://en.wikipedia.org/wiki/Version_control) which is used to manage projects and track changes in computer files. Once installed, it can be integrated into RStudio to manage your course assignments and other projects.

Comprehensive instructions for downloading and setting up this software can be found [here](setup00.html).

# How will I be evaluated?

Each week students will complete a series of programming assignments linked to lecture materials. These assignments will generally be due the following week prior to Wednesday's class. Weekly lab sessions will be held to assist students in completing these assignments. While students are encouraged to assist one another in debugging programs and solving problems in these assignments, it is imperative students also learn how to do this for themselves. That is, *students need to understand, write, and submit their own work.*

Each homework will be evaluated by either myself or the TA, as well as by **two peer reviewers**. Each of you is required to provide two peer reviews for each assignment; failure to complete these reviews will result in a deduction of your final grade.

* [General guidelines for submitting homework](hw00_homework_guidelines.html)
* [Evaluation criteria for homework](hw00_homework_grading.html)
* [How to perform peer review](hw00_peer-review.html)
* [How to properly ask for help](hw00_asking_questions.html)

## Statement on Disabilities

If you need any special accommodations, please provide me (Dr. Soltoff) with a copy of your Accommodation Determination Letter (provided to you by the Student Disability Services office) as soon as possible so that you may discuss with me how your accommodations may be implemented in this course.





