---
title: "How to properly ask for help"
output:
  html_document:
    toc: true
    toc_float: true
---

Asking questions is an important part of this class. Remember the **15 minute rule** - once you've spent 15 minutes attempting to troubleshoot a problem, **you must ask for help**. Questions should be posted to [the class discussion repo on GitHub](https://github.com/uc-cfss/Discussion). However, there are good and bad ways to ask questions. Here are some tips you should always follow when posting questions.

## Introduce the problem with an informative title

* Bad title: "I need help!"
* Good title: "Getting a 'file not found error' when importing scotus.csv"

Be specific with your title. It should be brief, but also informative so that when others are looking at the Issues page (and they have a similar error and/or solution), they can easily find it.

## Summarize the problem

Introduce the problem you are having. Include what task you are trying to perform, pertinent error messages, and any solutions you've already attempted. This helps us narrow down and troubleshoot your problem.

## Include a reproducible example

Including a [minimal, complete, and verifiable example](http://stackoverflow.com/help/mcve) of the code you are using greatly helps us resolve your problem. You don't need to copy all the code from your program into the comment, but include enough code that we can run it successfully **until the point at which the error occurs**.

Along with this, make sure you have [pushed](git05.html#step_4:_push_your_local_changes_online_to_github) your recent commits to the GitHub repo. If it is up-to-date, we can quickly look in or clone your repo to our machines to replicate the problem.

## Format your code snippets

GitHub can easily format and highlight your code. This will make code blocks visually distinct from your written summary. For instance, this block of code is hard to see on this page:

library(twitteR)

source("keys.R")

setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)

data <- userTimeline("realdonaldtrump", n = 1000)

data2 <- twListToDF(data)

write.csv(data2, "data2.csv")

Instead, format your code block by placing triple backticks ````` before and after the code block, like this:

``````
```
library(twitteR)
source("keys.R")
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
data <- userTimeline("realdonaldtrump", n = 1000)
data2 <- twListToDF(data)
write.csv(data2, "data2.csv")
```
``````

```
library(twitteR)
source("keys.R")
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
data <- userTimeline("realdonaldtrump", n = 1000)
data2 <- twListToDF(data)
write.csv(data2, "data2.csv")
```

To get R-specific syntax highlighting, add the language identifier after the first set of backticks:

``````
```r
library(twitteR)
source("keys.R")
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
data <- userTimeline("realdonaldtrump", n = 1000)
data2 <- twListToDF(data)
write.csv(data2, "data2.csv")
```
``````

```r
library(twitteR)
source("keys.R")
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
data <- userTimeline("realdonaldtrump", n = 1000)
data2 <- twListToDF(data)
write.csv(data2, "data2.csv")
```

## Include your `session_info()`

Sometimes problems are caused by using older or incompatible versions of packages. The `session_info()` function in the `devtools` library will print a list of all active packages and their respective versions. Include this in your post so we know which versions of packages you are using, like this:

```{r}
devtools::session_info()
```

## Post your solution

Once you have solved the problem (either by yourself or with the help of an instructor/classmate), **post the solution**. This let's us know that you have fixed the issue AND if anyone else encounters a similar error, they can refer to your solution to fix their problem.

# Acknowledgments {.toc-ignore}

* ["How do I ask a good question?" StackOverflow.com](http://stackoverflow.com/help/how-to-ask)
* ["How to Ask Programming Questions," ProPublica.com](https://www.propublica.org/nerds/item/how-to-ask-programming-questions)
