---
title: "Homework 01: Edit README.md"
output: html_document
---

# Overview

Due before class Monday October 3rd.

The goal is to test your software installation, our GitHub setup, and our homework submission process via an Issue.

# Take possession of `hw01` repository

Go [here](https://classroom.github.com/assignment-invitations/5a09685b38e162287215e6e2e8fcc7ab) to claim your repo for homework 01.

# Edit `README.md`

When you create the repository, you will notice there is only one file in the repo: `README.md`. In future assignments, the repo will be seeded with additional files/data that are necessary to get started.

If you are already familiar with GitHub, edit the `README.md` any way you wish.

If you are new to Git and GitHub, click on the `README` link in the area that looks like a file browser. Click on the pencil and make an edit. Then head down to "Commit changes". Enter a short *commit message*. Then click "Commit changes". This is how you can edit files in GitHub repository through the browser. If you are still mystified by Git(Hub), you can use this browser-based method to edit `README.md` until you get more comfortable with using Git locally and pushing to GitHub. *However, if at all possible*, we want you to pilot a more powerful workflow:

* Pull from GitHub (just an empty precaution now, but will matter when you collaborate with others)
* Make changes locally to `README.md` in RStudio
* Save your changes
* Commit your changes to your repo
* Push the commit to GitHub

*At the very least*, change `README.md` to something like "This is the repository of Benjamin Soltoff for homework 01," just to prove you have been there. Practice making a link, for example, to the [main course webpage](http://uc-cfss.github.io). The goal here is to demonstrate you have setup your software correctly.

# Report your process

Include a description of how you got the changes into `README.md` on GitHub.

  * Did you edit in the browser at GitHub.com?
  * Did you pull, edit locally, save, commit, push to GitHub.com?

You're encouraged to reflect on what was hard/easy, problems you solved, helpful tutorials you read, etc.

# Submit the assignment

Follow instructions on [How to submit homework](hw00_homework-guidelines.html#how-to-submit-homework)

# Rubric

Check minus: `README.md` says equivalent of "This is the repository of Jenny Bryan". All work done via browser at github.com ... but that's just a guess, because student doesn't actually say how it was done.

Check: something in between

Check plus: `README.md` provides a proper introduction of student to the class. It also demonstrates experimentation with 4 or more aspects of the Markdown syntax. Examples: section headers, links, bold, italic, bullet points, image embed, etc. The student describes how they got the changes into `README.md` and offers a few reflections on their GitHub workflow and their experience with Markdown.

### Acknowledgments {.toc-ignore}

```{r child='_ack_stat545.Rmd'}
```
