---
title: "Homework 07: Distributed learning and geospatial visualization"
output: html_document
---

# Overview

Due before class November 13th.

# Fork the `hw07` repository

Go [here](https://github.com/uc-cfss/hw07) to fork the repo for homework 07.

# Titanic (redux)

[Last week](hw06-stat-learn.html) you estimated statistical learning models predicting survival and death on the Titanic. Take the model specification for your best-performing model from the Titanic problem, and estimate it using at least three machine learning algorithms in `sparklyr` (either MLlib or H2O). Calculate the accuracy and AUC metrics for each model. Which algorithm performs the best?
    * If you use an `ml_()` function, you need to split the data into training/test sets
    * If you use an `h2o.()` function, you need to either split the data into training/test sets or use $k$-fold CV

# Geospatial visualization

TBD.

# Submit the assignment

Your assignment should be submitted as one or more R Markdown documents, data files, figures, etc. Follow instructions on [homework workflow](hw00_homework_guidelines.html#homework_workflow). As part of the pull request, you're encouraged to reflect on what was hard/easy, problems you solved, helpful tutorials you read, etc.

# Rubric

Check minus: Cannot get code to run or is poorly documented. No documentation in the `README` file. Severe misinterpretations of the results. Overall a shoddy or incomplete assignment.

Check: Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output). Nothing spectacular, either bad or good.

Check plus: Interpretation is clear and in-depth. Accurately interprets the results, with appropriate caveats for what the technique can and cannot do. Code is reproducible. Writes a user-friendly `README` file. Discusses the benefits and drawbacks of a specific method. Compares multiple models fitted to the same underlying dataset.
