---
title: "Computing for the Social Sciences"
---

* Instructor: Benjamin Soltoff [soltoffbc@uchicago.edu](mailto:soltoffbc@uchicago.edu), Lecturer, [Masters in Computational Social Science](http://macss.uchicago.edu)
* Teaching Assistants: TBD
* Meeting day/time: MW 1:30-2:50pm, location TBD
* Online course discussion: Piazza
* Open lab session: TBD
* Office hours: TBD
* TA office hours: TBD
* Prerequisites: None
* Requirements: Bring your own laptop

## Course Description

## Course Objectives

By the end of the course, students will:

* Construct and execute basic programs in Python and R using elementary programming techniques (e.g. loops, conditional statements, user-defined functions)
* Apply stylistic principles of coding to generate reusable, interpretable code
* Debug programs for errors
* Identify and use external libraries to expand on base functions
* Implement statistical analysis using R
* Visualize information and data using appropriate graphical techniques
* Import data from file or internet using R
* Munge raw data into a tidy format
* Scrape websites to collect data for analysis
* Analyze networks
* Parse and analyze text documents
* Implement machine learning algorithms
* Connect to and obtain data from relational databases through local and API access
* Create interactive web pages using RMarkdown and Shiny
* Write programs which utilize parallel processing and are implemented locally or through a computing cluster

## Textbooks/Readings

### Required

* [R for Data Science](http://r4ds.had.co.nz/) -- Garrett Grolemund and Hadley Wickham. Hardcover to be published late 2016, but an open-source online version is available now.
* Think Python, 2nd Edition -- Allen B. Downey. [Hardcover available on Amazon for $40](https://www.amazon.com/Think-Python-Like-Computer-Scientist/dp/1491939362/ref=sr_1_1?ie=UTF8&qid=1468610678&sr=8-1&keywords=think+python), but a digital copy is available [via the UChicago library (authentication required)](http://proquestcombo.safaribooksonline.com.proxy.uchicago.edu/9781491939406?uicode=uchicago).

### Optional

* [ggplot2: Elegant Graphics for Data Analysis, 2nd Edition](http://link.springer.com.proxy.uchicago.edu/book/10.1007%2F978-0-387-98141-3) -- Hadley Wickham. Excellent resource for the ggplot2 graphics library.

## Software

By Day 1, you should install the following software on your computer:

* [R](https://www.r-project.org/) - easiest approach is to select [a pre-compiled binary appropriate for your operating system](https://cran.rstudio.com/).
* [RStudio's IDE](https://www.rstudio.com/products/RStudio/) - this is a powerful user interface for programming in R. You could use base R, but you would regret it.
* [Anaconda](https://www.continuum.io/downloads) - Anaconda is a popular distribution of Python and includes many important packages already pre-loaded.
* [Github](https://github.com/) - Github is a [version control system](https://en.wikipedia.org/wiki/Version_control) which is used to manage projects and track changes in computer files. Once installed, it can be integrated into RStudio to manage your course assignments and other projects.

## Evaluation

## Course Schedule

### Week 1 - Programming, Python Fundamentals and an Introduction to Computational Social Science

### Week 2 - Code Reuse and Tuning

### Week 3 - Introduction to R/Data Analysis

### Week 4 - Visualization

### Week 5 - Data Munging/Tidy Data

### Week 6 - Web Scraping/Network Analysis

### Week 7 - Text/Machine Learning

### Week 8 - Data Warehousing

### Week 9 - Interactivity

### Week 10 - High Performance Computing






