<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="MACS 30100 - Perspectives on Computational Modeling" />


<title>Statistical learning: logistic regression</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45631879-2', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
div.sourceCode {
  overflow-x: visible;
}
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 66px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 71px;
  margin-top: -71px;
}

.section h2 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h3 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h4 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h5 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h6 {
  padding-top: 71px;
  margin-top: -71px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Computing for the Social Sciences</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="faq.html">FAQ</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Statistical learning: logistic regression</h1>
<h4 class="author"><em>MACS 30100 - Perspectives on Computational Modeling</em></h4>

</div>


<div id="objectives" class="section level1">
<h1>Objectives</h1>
<ul>
<li>Define a classification problem</li>
<li>Demonstrate why linear regression is a poor method to use for classification problems</li>
<li>Introduce the logistic regression functional form</li>
<li>Distinguish between probability, odds, and log-odds</li>
<li>Identify how to calculate predicted probabilities</li>
<li>Implement multiple logistic regression and practice interpreting the parameters</li>
<li>Introduce methods for assessing the accuracy of a classifier model</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(modelr)
<span class="kw">library</span>(broom)
<span class="kw">library</span>(forcats)

<span class="kw">set.seed</span>(<span class="dv">1234</span>)

<span class="kw">theme_set</span>(<span class="kw">theme_minimal</span>())</code></pre></div>
</div>
<div id="classification-problems" class="section level1">
<h1>Classification problems</h1>
<p>The sinking of <a href="https://en.wikipedia.org/wiki/RMS_Titanic">RMS Titanic</a> provided the world with many things:</p>
<ul>
<li>A fundamental shock to the world as its faith in supposedly indestructible technology was shattered by a chunk of ice</li>
<li><p>Perhaps the best romantic ballad of all time</p>
<iframe width="853" height="480" src="https://www.youtube.com/embed/FHG2oizTlpY?rel=0" frameborder="0" allowfullscreen>
</iframe></li>
<li><p>A tragic love story</p>
<div class="figure">
<img src="http://i.giphy.com/KSeT85Vtym7m.gif" alt="Titanic (1997)" />
<p class="caption"><a href="https://en.wikipedia.org/wiki/Titanic_(1997_film)">Titanic (1997)</a></p>
</div></li>
</ul>
<p>Why did Jack have to die? Why couldn’t he have made it onto a lifeboat like Cal? We may never know the answer, but we can generalize the question a bit: why did some people survive the sinking of the Titanic while others did not?</p>
<p>In essence, we have a <strong>classification</strong> problem. The response is a <strong>qualitative variable</strong>, in this case a binary variable indicating whether a specific passenger survived. This differs from a <strong>regression</strong> problem. In a regression problem, the response variable is <strong>quantitative</strong> and could take on potentially an infinite range of values. In classification problems, we want to develop a model that assigns observations to <strong>categories</strong> or <strong>classes</strong> of the response variable. Given our knowledge of survivors and diers on the Titanic, if we combine this with predictors that describe each passenger we might be able to estimate a general model of survival.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></p>
<p>Kaggle is an online platform for predictive modeling and analytics. They run regular competitions where they provide the public with a question and data, and anyone can estimate a predictive model to answer the question. They’ve run a popular contest based on a <a href="https://www.kaggle.com/c/titanic/data">dataset of passengers from the Titanic</a>. The datasets have been conveniently stored in a package called <code>titanic</code>. Let’s load the package and convert the desired data frame to a tibble.<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(titanic)
titanic &lt;-<span class="st"> </span>titanic_train <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># remove missing values</span>
<span class="st">  </span><span class="kw">na.omit</span>()

titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">head</span>() <span class="op">%&gt;%</span>
<span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">PassengerId</th>
<th align="right">Survived</th>
<th align="right">Pclass</th>
<th align="left">Name</th>
<th align="left">Sex</th>
<th align="right">Age</th>
<th align="right">SibSp</th>
<th align="right">Parch</th>
<th align="left">Ticket</th>
<th align="right">Fare</th>
<th align="left">Cabin</th>
<th align="left">Embarked</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="left">Braund, Mr. Owen Harris</td>
<td align="left">male</td>
<td align="right">22</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">A/5 21171</td>
<td align="right">7.2500</td>
<td align="left"></td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">Cumings, Mrs. John Bradley (Florence Briggs Thayer)</td>
<td align="left">female</td>
<td align="right">38</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">PC 17599</td>
<td align="right">71.2833</td>
<td align="left">C85</td>
<td align="left">C</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="left">Heikkinen, Miss. Laina</td>
<td align="left">female</td>
<td align="right">26</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">STON/O2. 3101282</td>
<td align="right">7.9250</td>
<td align="left"></td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">Futrelle, Mrs. Jacques Heath (Lily May Peel)</td>
<td align="left">female</td>
<td align="right">35</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">113803</td>
<td align="right">53.1000</td>
<td align="left">C123</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="left">Allen, Mr. William Henry</td>
<td align="left">male</td>
<td align="right">35</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">373450</td>
<td align="right">8.0500</td>
<td align="left"></td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="right">7</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">McCarthy, Mr. Timothy J</td>
<td align="left">male</td>
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">17463</td>
<td align="right">51.8625</td>
<td align="left">E46</td>
<td align="left">S</td>
</tr>
</tbody>
</table>
<p>The codebook contains the following information on the variables:</p>
<pre><code>VARIABLE DESCRIPTIONS:
Survived        Survival
                (0 = No; 1 = Yes)
Pclass          Passenger Class
                (1 = 1st; 2 = 2nd; 3 = 3rd)
Name            Name
Sex             Sex
Age             Age
SibSp           Number of Siblings/Spouses Aboard
Parch           Number of Parents/Children Aboard
Ticket          Ticket Number
Fare            Passenger Fare
Cabin           Cabin
Embarked        Port of Embarkation
                (C = Cherbourg; Q = Queenstown; S = Southampton)

SPECIAL NOTES:
Pclass is a proxy for socio-economic status (SES)
 1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower

Age is in Years; Fractional if Age less than One (1)
 If the Age is Estimated, it is in the form xx.5

With respect to the family relation variables (i.e. sibsp and parch)
some relations were ignored.  The following are the definitions used
for sibsp and parch.

Sibling:  Brother, Sister, Stepbrother, or Stepsister of Passenger Aboard Titanic
Spouse:   Husband or Wife of Passenger Aboard Titanic (Mistresses and Fiances Ignored)
Parent:   Mother or Father of Passenger Aboard Titanic
Child:    Son, Daughter, Stepson, or Stepdaughter of Passenger Aboard Titanic

Other family relatives excluded from this study include cousins,
nephews/nieces, aunts/uncles, and in-laws.  Some children travelled
only with a nanny, therefore parch=0 for them.  As well, some
travelled with very close friends or neighbors in a village, however,
the definitions do not support such relations.</code></pre>
<p>So if this is our data, <code>Survived</code> is our <strong>response variable</strong>, and the remaining variables are <strong>predictors</strong>, how can we determine who survives and who dies?</p>
<div id="a-linear-regression-approach" class="section level2">
<h2>A linear regression approach</h2>
<p>Let’s concentrate first on the relationship between age and survival. Using the methods we previously learned, we could estimate a linear regression model:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_{1}X\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(titanic, <span class="kw">aes</span>(Age, Survived)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;???&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/titanic_ols-1.png" width="672" /></p>
<p>Hmm. Not terrible, but you can immediately notice a couple of things. First, the only possible values for <code>Survival</code> are <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>. Yet the linear regression model gives us predicted values such as <span class="math inline">\(.4\)</span> and <span class="math inline">\(.25\)</span>. How should we interpret those?</p>
<p>One possibility is that these values are <strong>predicted probabilities</strong>. That is, the estimated probability a passenger will survive given their age. So someone with a predicted probability of <span class="math inline">\(.4\)</span> has a 40% chance of surviving. Okay, but notice that because the line is linear and continuous, it extends infinitely in both directions of age.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(titanic, <span class="kw">aes</span>(Age, Survived)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">fullrange =</span> <span class="ot">TRUE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlim</span>(<span class="dv">0</span>, <span class="dv">200</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;???&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/titanic_ols_old-1.png" width="672" /></p>
<p>What happens if a 200 year old person is on the Titanic?<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a> They would have a <span class="math inline">\(-.1\)</span> probability of surviving. <strong>But you cannot have a probability outside of the <span class="math inline">\([0,1]\)</span> interval!</strong> Admittedly this is a trivial example, but in other circumstances this can become a more realistic scenario.</p>
<p>Or what if we didn’t want to predict survival, but instead predict the port from which an individual departed (Cherbourg, Queenstown, or Southampton). We could try and code this as a numeric response variable:</p>
<table>
<thead>
<tr class="header">
<th>Numeric value</th>
<th>Port</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Cherbourg</td>
</tr>
<tr class="even">
<td>2</td>
<td>Queenstown</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Southampton</td>
</tr>
</tbody>
</table>
<p>But why not instead code it:</p>
<table>
<thead>
<tr class="header">
<th>Numeric value</th>
<th>Port</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Queenstown</td>
</tr>
<tr class="even">
<td>2</td>
<td>Cherbourg</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Southampton</td>
</tr>
</tbody>
</table>
<p>Or even:</p>
<table>
<thead>
<tr class="header">
<th>Numeric value</th>
<th>Port</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Southampton</td>
</tr>
<tr class="even">
<td>2</td>
<td>Cherbourg</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Queenstown</td>
</tr>
</tbody>
</table>
<p><strong>There is no inherent ordering to this variable.</strong> Any claimed linear relationship between a predictor and port of embarkation is completely dependent on how we convert the classes to numeric values.</p>
</div>
</div>
<div id="logistic-regression" class="section level1">
<h1>Logistic regression</h1>
<div id="probability" class="section level2">
<h2>Probability</h2>
<p>Rather than modeling the response <span class="math inline">\(Y\)</span> directly, logistic regression instead models the <strong>probability</strong> that <span class="math inline">\(Y\)</span> belongs to a particular category. In our first Titanic example, the probability of survival can be written as:</p>
<p><span class="math display">\[p(X) = p(\text{survival} = \text{yes} | \text{age})\]</span></p>
<p>The linear regression model above attempted to predict or explain <span class="math inline">\(p(X)\)</span> using the functional form</p>
<p><span class="math display">\[p(X) = \beta_0 + \beta_{1}X\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># simulate fake binary data</span>
sim_logit &lt;-<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">x =</span> <span class="kw">runif</span>(<span class="dv">1000</span>, <span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>),
                        <span class="dt">y =</span> <span class="dv">0</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="op">*</span><span class="st"> </span>x)

<span class="co"># graph it</span>
<span class="kw">ggplot</span>(sim_logit, <span class="kw">aes</span>(x, y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;The linear function&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;X&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;p(X)&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/linear-demo-1.png" width="672" /></p>
<p>But we now know that by using this functional form, we will always have for at least some subset of <span class="math inline">\(\text{age}\)</span> predicted values outside the <span class="math inline">\([0,1]\)</span> range. Instead, we need to model the functional form to prevent values from exceeding this range. One such function is the <strong>logistic function</strong>:<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a></p>
<p><span class="math display">\[p(X) = \frac{e^{\beta_0 + \beta_{1}X}}{1 + e^{\beta_0 + \beta_{1}X}}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">logit2prob &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  <span class="kw">exp</span>(x) <span class="op">/</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(x))
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim_logit &lt;-<span class="st"> </span>sim_logit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">logit2prob</span>(y))

<span class="co"># graph it</span>
<span class="kw">ggplot</span>(sim_logit, <span class="kw">aes</span>(x, prob)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;The logistic function&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;X&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Prob(X)&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/logit-demo-1.png" width="672" /></p>
<p>The logistic transformation produces an S-shaped curve that preserves ordering; that is, larger values of <span class="math inline">\(X\)</span> will also result in larger values of <span class="math inline">\(p(X)\)</span>, but the relationship is now <strong>curvilinear</strong>. <span class="math inline">\(P(X)\)</span> will never decrease below 0 and never exceed 1, so the predicted probabilities will always have inherent meaning.</p>
<div id="probability-of-surviving-the-titanic" class="section level3">
<h3>Probability of surviving the Titanic</h3>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{\beta_0 + \beta_{1}\text{Age}}}{1 + e^{\beta_0 + \beta_{1}\text{Age}}}\]</span></p>
<p>The values of <span class="math inline">\(P(\text{survival} = \text{Yes} | \text{age})\)</span> (or simply <span class="math inline">\(p(\text{survival})\)</span> will range between 0 and 1. Given that predicted probability, we could predict anyone with for whom <span class="math inline">\(p(\text{survival}) &gt; .5\)</span> will survive the sinking, and anyone else will die.<a href="#fn5" class="footnoteRef" id="fnref5"><sup>5</sup></a></p>
<p>We can estimate the logistic regression model using the <code>glm()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">survive_age &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span>Age, <span class="dt">data =</span> titanic, <span class="dt">family =</span> binomial)
<span class="kw">summary</span>(survive_age)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Age, family = binomial, data = titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1488  -1.0361  -0.9544   1.3159   1.5908  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -0.05672    0.17358  -0.327   0.7438  
## Age         -0.01096    0.00533  -2.057   0.0397 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 964.52  on 713  degrees of freedom
## Residual deviance: 960.23  on 712  degrees of freedom
## AIC: 964.23
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Which produces a line that looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># generate predicted values</span>
survive_age_pred &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(survive_age) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># predicted values are in the log-odds form - convert to probabilities</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">logit2prob</span>(pred))

<span class="kw">ggplot</span>(survive_age_pred, <span class="kw">aes</span>(Age)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Survived)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> prob), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Probability of surviving the Titanic&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/titanic_age_glm_plot-1.png" width="672" /></p>
<p>It’s hard to tell, but the line is not perfectly linear. Let’s expand the range of the x-axis to prove this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(titanic, <span class="kw">aes</span>(Age, Survived)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="co"># use geom_smooth for out-of-sample range plotting</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;glm&quot;</span>, <span class="dt">method.args =</span> <span class="kw">list</span>(<span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>),
              <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">fullrange =</span> <span class="ot">TRUE</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlim</span>(<span class="dv">0</span>,<span class="dv">200</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Probability of surviving the Titanic&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/titanic_age_glm_plot_wide-1.png" width="672" /></p>
<p>No more predictions that a 200 year old has a <span class="math inline">\(-.1\)</span> probability of surviving!</p>
</div>
<div id="generating-predicted-probabilities" class="section level3">
<h3>Generating predicted probabilities</h3>
<p>To generate predicted probabilities, just substitute your specified values for <span class="math inline">\(X\)</span> in the original <span class="math inline">\(p(X)\)</span> equation. So for instance, the predicted probability of surviving the Titanic for a 30 year old is</p>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{\beta_0 + \beta_{1} \times 30}}{1 + e^{\beta_0 + \beta_{1} \times 30}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{-0.057 + -0.011 \times 30}}{1 + e^{-0.057 + -0.011 \times 30}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}) = 0.405\]</span></p>
</div>
</div>
<div id="odds" class="section level2">
<h2>Odds</h2>
<p>We can rewrite the probability function in the alternative form</p>
<p><span class="math display">\[\frac{p(X)}{1 - p(x)} = e^{\beta_0 + \beta_{1}X}\]</span></p>
<p>This quantity is called the <strong>odds</strong> and its range is <span class="math inline">\([0,\infty]\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prob2odds &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  x <span class="op">/</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>x)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim_logit &lt;-<span class="st"> </span>sim_logit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">odds =</span> <span class="kw">prob2odds</span>(prob))

<span class="co"># graph it</span>
<span class="kw">ggplot</span>(sim_logit, <span class="kw">aes</span>(x, odds)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;The logistic function&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;X&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Odds(X)&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/odds-demo-1.png" width="672" /></p>
<p>Essentially it is the probability of one outcome divided by the probability of the other outcome. So in this example, it is</p>
<p><span class="math display">\[\frac{p(\text{Survived})}{p(\text{Died})}\]</span></p>
<p>So an odds of <span class="math inline">\(4\)</span> for an individual means they are 4 times more likely to survive than die, whereas an odds of <span class="math inline">\(\frac{1}{4}\)</span> means the odds of surviving are <span class="math inline">\(.25\)</span> as large as the odds of dying (i.e. the odds are higher you will die than survive).</p>
<p>Odds are typically used in the context of gambling since they are easier to follow when establishing a betting strategy. For example, consider an American football game between the Cleveland Browns and the Pittsburgh Steelers. If the odds are 1 in 4 (<span class="math inline">\(\frac{1}{4}\)</span>) of the Pittsburgh Steelers winning a game against the Cleveland Browns and you believe the Steelers will win, this means you must bet $4 in order to win a payoff of $1 if the Steelers win.<a href="#fn6" class="footnoteRef" id="fnref6"><sup>6</sup></a> However if you are a die-hard Browns fan and want to bet on them winning, the odds of the Browns winning are 4 to 1 (<span class="math inline">\(\frac{4}{1}\)</span>) - it means you must bet $1 to earn a payoff of $4 if the Browns in fact win.</p>
<div id="odds-of-surviving-the-titanic" class="section level3">
<h3>Odds of surviving the Titanic</h3>
<p>We can convert the probability of surviving the Titanic to the odds of surviving the Titanic.</p>
<p><span class="math display">\[\frac{p(\text{Survival})}{1 - p(\text{Survival})} = e^{\beta_0 + \beta_{1}\text{Age}}\]</span></p>
<p>The resulting graph is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">survive_age_pred &lt;-<span class="st"> </span>survive_age_pred <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">odds =</span> <span class="kw">prob2odds</span>(prob))

<span class="kw">ggplot</span>(survive_age_pred, <span class="kw">aes</span>(Age, odds)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Odds of surviving the Titanic&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/titanic-odds-plot-1.png" width="672" /></p>
<p>Regardless of age, the odds of surviving the Titanic are always below 1. Considering the probability of even a 1 year old surviving was less than <span class="math inline">\(.50\)</span>, this should be expected. The relationship between age and the odds of survival is still curvilinear.</p>
</div>
</div>
<div id="log-odds" class="section level2">
<h2>Log-odds</h2>
<p>By taking the logarithm of both sides of the odds function, we get</p>
<p><span class="math display">\[\log\left(\frac{p(X)}{1 - p(x)}\right) = \beta_0 + \beta_{1}X\]</span></p>
<p>The result is the <strong>log-odds</strong> or <strong>logit</strong>. Notice that this function now imposes a linear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(p(X)\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prob2logodds &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  <span class="kw">log</span>(<span class="kw">prob2odds</span>(x))
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim_logit &lt;-<span class="st"> </span>sim_logit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">logodds =</span> <span class="kw">prob2logodds</span>(prob))

<span class="co"># graph it</span>
<span class="kw">ggplot</span>(sim_logit, <span class="kw">aes</span>(x, logodds)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;The logistic function&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;X&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Log-Odds(X)&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/log-odds-demo-1.png" width="672" /></p>
<p>A one-unit increase in <span class="math inline">\(X\)</span> corresponds to a monotonic increase or decrease in the log-odds of <span class="math inline">\(Y\)</span>. But because of the exponential transformation between log-odds and odds, <strong>a one-unit increase in <span class="math inline">\(X\)</span> corresponds to a differential increase or decrease in the odds of <span class="math inline">\(Y\)</span></strong>. The amount of the change in the odds of <span class="math inline">\(Y\)</span> depends on the initial value of <span class="math inline">\(X\)</span>. The directionality of the relationship is always the same, but not the magnitude. The same thing applies to the relationship between <span class="math inline">\(X\)</span> and the probability of <span class="math inline">\(Y\)</span>. This explains why we see curvilinear shapes for probabilities and odds, but not for log-odds.</p>
<div id="log-odds-of-surviving-the-titanic" class="section level3">
<h3>Log-odds of surviving the Titanic</h3>
<p>When you estimate a logistic regression model the log-odds function is actually the function for which you are estimating parameters.</p>
<p><span class="math display">\[\log\left(\frac{p(\text{Survival})}{1 - p(\text{Survival})}\right) = \beta_0 + \beta_{1}\text{Age}\]</span></p>
<p>Hence the parameters for the Titanic survival model</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tidy</span>(survive_age)</code></pre></div>
<pre><code>##          term    estimate  std.error  statistic    p.value
## 1 (Intercept) -0.05672364 0.17358043 -0.3267859 0.74382982
## 2         Age -0.01096345 0.00532994 -2.0569560 0.03969046</code></pre>
<p>are actually expressed in terms of log-odds – <strong>for every one-unit increase in age, we expect the log-odds of survival to decrease by 0.011</strong>.</p>
<p><span class="math display">\[\log\left(\frac{p(\text{Survival})}{1 - p(\text{Survival})}\right) = -0.057 + -0.011 x \text{Age}\]</span></p>
<p>Generating predicted values from logistic regression models using <code>add_predictions()</code> always returns the log-odds of the outcome, so we can plot that directly to see the relationship between age and the log-odds of survival.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(survive_age_pred, <span class="kw">aes</span>(Age, pred)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Log-odds of surviving the Titanic&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/log-odds-plot-1.png" width="672" /></p>
<p>While we can graph the log-odds, they don’t make any inherent sense. Nobody discusses the likelihood of events occuring in log-odds term. They are necessary to understanding and estimating logistic regression models, but are not directly interpretable.</p>
<div id="discussing-the-results-in-terms-of-probabilities" class="section level4">
<h4>Discussing the results in terms of probabilities</h4>
<p>To interpret them in terms of probabilities, you need to specify your initial value for age. So for example, an increase in age from 20 to 30 is calculated by taking the <strong>first difference</strong>, or the expected change in probability given a particular change in the predictor. While it looks messy, all you do is calculate the predicted probability of survival for age 20 and 30 and calculate the difference.</p>
<p><span class="math display">\[p(\text{Survival}_{30 - 20}) = \frac{e^{\beta_0 + \beta_{1}30}}{1 + e^{\beta_0 + \beta_{1}30}} - \frac{e^{\beta_0 + \beta_{1}20}}{1 + e^{\beta_0 + \beta_{1}20}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}_{30 - 20}) = \frac{e^{-0.057 + -0.011 \times 30}}{1 + e^{-0.057 + -0.011 \times 30}} - \frac{e^{-0.057 + -0.011 \times 20}}{1 + e^{-0.057 + -0.011 \times 20}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}_{30 - 20}) = 0.405 - 0.431\]</span></p>
<p><span class="math display">\[p(\text{Survival}_{30 - 20}) = -0.0267\]</span></p>
<p>However, compare this to the change in predicted probability of survival from age 40 to 50.</p>
<p><span class="math display">\[p(\text{Survival}_{50 - 40}) = \frac{e^{\beta_0 + \beta_{1}50}}{1 + e^{\beta_0 + \beta_{1}50}} - \frac{e^{\beta_0 + \beta_{1}40}}{1 + e^{\beta_0 + \beta_{1}40}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}_{50 - 40}) = \frac{e^{-0.057 + -0.011 \times 50}}{1 + e^{-0.057 + -0.011 \times 50}} - \frac{e^{-0.057 + -0.011 \times 40}}{1 + e^{-0.057 + -0.011 \times 40}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}_{50 - 40}) = 0.353 - 0.379\]</span></p>
<p><span class="math display">\[p(\text{Survival}_{50 - 40}) = -0.0254\]</span></p>
<p>Again, the relationship between age and the probability of survival is only weakly curvilinear, but you can already see that the first difference will depend on your initial starting value for age.</p>
</div>
</div>
</div>
<div id="estimating-the-parameters" class="section level2">
<h2>Estimating the parameters</h2>
<p>Logistic regression is typically estimated using <a href="https://github.com/UC-MACSS/persp-model/blob/master/demos/MLE/MLest.ipynb"><strong>maximum likelihood estimation</strong></a>.</p>
</div>
<div id="generating-predicted-probabilities-using-add_predictions" class="section level2">
<h2>Generating predicted probabilities using <code>add_predictions()</code></h2>
<p>To visualise the predictions from a model, we start by generating an evenly spaced grid of values that covers the region where our data lies. First we use <code>data_grid()</code> from the <code>modelr</code> package to create a cleaned data frame of potential values:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">titanic_age &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">data_grid</span>(Age)
titanic_age</code></pre></div>
<pre><code>## # A tibble: 88 × 1
##      Age
##    &lt;dbl&gt;
## 1   0.42
## 2   0.67
## 3   0.75
## 4   0.83
## 5   0.92
## 6   1.00
## 7   2.00
## 8   3.00
## 9   4.00
## 10  5.00
## # ... with 78 more rows</code></pre>
<p>Next we use the <code>add_predictions()</code> function to produce the predicted probabilities. This worked very well for linear models; unfortunately it is not perfect for logistic regression because as you I mentioned above, logistic regression directly estimates the <a href="https://wiki.lesswrong.com/wiki/Log_odds"><strong>log-odds</strong></a> for the outcome. Instead, we want the plain old predicted probability. To do this, we use this custom function to convert from log-odds to predicted probabilties:<a href="#fn7" class="footnoteRef" id="fnref7"><sup>7</sup></a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">logit2prob &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  <span class="kw">exp</span>(x) <span class="op">/</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(x))
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(modelr)

titanic_age &lt;-<span class="st"> </span>titanic_age <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(survive_age) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">logit2prob</span>(pred))
titanic_age</code></pre></div>
<pre><code>## # A tibble: 88 × 2
##      Age      pred
##    &lt;dbl&gt;     &lt;dbl&gt;
## 1   0.42 0.4846727
## 2   0.67 0.4839882
## 3   0.75 0.4837691
## 4   0.83 0.4835501
## 5   0.92 0.4833037
## 6   1.00 0.4830847
## 7   2.00 0.4803475
## 8   3.00 0.4776115
## 9   4.00 0.4748768
## 10  5.00 0.4721436
## # ... with 78 more rows</code></pre>
<p>With this information, we can now plot the logistic regression line using the estimated model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(titanic_age, <span class="kw">aes</span>(Age, pred)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Relationship between age and surviving the Titanic&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Predicted probability of survival&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/plot_pred-1.png" width="672" /></p>
</div>
<div id="multiple-predictors" class="section level2">
<h2>Multiple predictors</h2>
<p>But as the old principle of the sea goes, <a href="https://en.wikipedia.org/wiki/Women_and_children_first">“women and children first”</a>. What if age isn’t the only factor effecting survival? Fortunately logistic regression handles multiple predictors in the form:</p>
<p><span class="math display">\[p(X) = \frac{e^{\beta_0 + \beta_{1}X_1 + \dots + \beta_{p}X_{p}}}{1 + e^{\beta_0 + \beta_{1}X_1 + \dots + \beta_{p}X_{p}}}\]</span></p>
<p>In our next model, let’s consider the relationship between age, sex, and survival. The logistic function takes the form:</p>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Sex}}}{1 + e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Sex}}}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">survive_age_woman &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span>Age <span class="op">+</span><span class="st"> </span>Sex, <span class="dt">data =</span> titanic,
                         <span class="dt">family =</span> binomial)
<span class="kw">summary</span>(survive_age_woman)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Age + Sex, family = binomial, data = titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7405  -0.6885  -0.6558   0.7533   1.8989  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.277273   0.230169   5.549 2.87e-08 ***
## Age         -0.005426   0.006310  -0.860     0.39    
## Sexmale     -2.465920   0.185384 -13.302  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 964.52  on 713  degrees of freedom
## Residual deviance: 749.96  on 711  degrees of freedom
## AIC: 755.96
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The parameters essentially tell us the relationship between each individual predictor and the response, <strong>independent of other predictors</strong>. So this model tells us the relationship between age and survival, after controlling for the effects of gender. Likewise, it also tells us the relationship between gender and survival, after controlling for the effects of age. To get a better visualization of this, let’s use <code>data_grid()</code> and <code>add_predictions()</code> again:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">titanic_age_sex &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">data_grid</span>(Age, Sex) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(survive_age_woman) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">logit2prob</span>(pred))
titanic_age_sex</code></pre></div>
<pre><code>## # A tibble: 176 × 3
##      Age    Sex      pred
##    &lt;dbl&gt;  &lt;chr&gt;     &lt;dbl&gt;
## 1   0.42 female 0.7815965
## 2   0.42   male 0.2330934
## 3   0.67 female 0.7813649
## 4   0.67   male 0.2328510
## 5   0.75 female 0.7812907
## 6   0.75   male 0.2327735
## 7   0.83 female 0.7812165
## 8   0.83   male 0.2326960
## 9   0.92 female 0.7811330
## 10  0.92   male 0.2326088
## # ... with 166 more rows</code></pre>
<p>With these predicted probabilities, we can now plot the separate effects of age and gender:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(titanic_age_sex, <span class="kw">aes</span>(Age, pred, <span class="dt">color =</span> Sex)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Probability of surviving the Titanic&quot;</span>,
       <span class="dt">subtitle =</span> <span class="st">&quot;Age + Sex&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Predicted probability of survival&quot;</span>,
       <span class="dt">color =</span> <span class="st">&quot;Sex&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/survive_age_woman_plot-1.png" width="672" /></p>
<p>Substantively, this graph illustrates a key fact about surviving the sinking of the Titanic - age was not really a dominant factor. Instead, one’s gender was much more important. Females survived at much higher rates than males, regardless of age.</p>
</div>
<div id="predicted-probabilities-and-first-differences-in-multiple-variable-models" class="section level2">
<h2>Predicted probabilities and first differences in multiple variable models</h2>
<p>Mathematically, the result is two lines that are parallel to each other <strong>in the log-odds functional form</strong>. The addition of the gender parameter acts like an second intercept when we compare age to probability of survival. All that happens is the line shifts up or down based on the estimated gender parameter.</p>
<p>In terms of predicted probabilities and first differences, <strong>this is not true</strong>. Remember the logistic function:</p>
<p><span class="math display">\[p(X) = \frac{e^{\beta_0 + \beta_{1}X_1 + \beta_{2}X_2}}{1 + e^{\beta_0 + \beta_{1}X_1 + \beta_{2}X_2}}\]</span></p>
<p>Because of the exponential transformation, <span class="math inline">\(\beta_2\)</span> now has a non-linear impact on the predicted probabilities. For clarity, let’s estimate a logistic regression model of the effect of age and fare on survival:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate logistic regression model of age and fare</span>
age_fare &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span>Age <span class="op">+</span><span class="st"> </span>Fare, <span class="dt">data =</span> titanic, <span class="dt">family =</span> binomial)
<span class="kw">tidy</span>(age_fare)</code></pre></div>
<pre><code>##          term    estimate   std.error statistic      p.value
## 1 (Intercept) -0.41705506 0.185975550 -2.242526 2.492738e-02
## 2         Age -0.01757841 0.005665823 -3.102534 1.918715e-03
## 3        Fare  0.01725837 0.002616589  6.595751 4.231096e-11</code></pre>
<p>And generate predicted log-odds and probabilities of survival for a series of hypothetical passengers, varying the fare amount paid.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># generate predicted values</span>
age_fare_pred &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">data_grid</span>(Age, <span class="dt">Fare =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="kw">max</span>(Fare), <span class="dt">by =</span> <span class="dv">100</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(age_fare) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">logit2prob</span>(pred),
         <span class="dt">Fare =</span> <span class="kw">factor</span>(Fare, <span class="dt">levels =</span> <span class="kw">rev</span>(<span class="kw">seq</span>(<span class="dv">0</span>, <span class="kw">max</span>(Fare), <span class="dt">by =</span> <span class="dv">100</span>))))</code></pre></div>
<p>Below is the plot of the log-odds for this regression model. To draw the line, all we did was draw the line for the relationship between age and expected log-odds of survival, holding fare constant at different levels.</p>
<p><span class="math display">\[\log\left(\frac{p(\text{Survival})}{1 - p(\text{Survival})}\right) = \beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Fare}\]</span></p>
<p><span class="math display">\[\log\left(\frac{p(\text{Survival})}{1 - p(\text{Survival})}\right) = (\beta_0 + \beta_{2}\text{Fare}) + \beta_{1}\text{Age}\]</span></p>
<p>Notice that each line is parallel to each other, because all that <span class="math inline">\(\hat{\beta}_{2}\)</span> did was change the intercept for the controlled relationship between age and log-odds of survival.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the new log-odds lines</span>
<span class="kw">ggplot</span>(age_fare_pred, <span class="kw">aes</span>(Age, pred, <span class="dt">group =</span> Fare, <span class="dt">color =</span> Fare)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Log-odds of survival&quot;</span>,
       <span class="dt">subtitle =</span> <span class="st">&quot;Age + Fare model&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Log-odds of survival&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/fd-non-parallel-logodds-1.png" width="672" /></p>
<p>Now see what happens when we do the same thing but using predicted probabilities instead.</p>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Fare}}}{1 + e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Fare}}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{(\beta_0 + \beta_{2}\text{Fare}) + \beta_{1}\text{Age}}}{1 + e^{(\beta_0 + \beta_{2}\text{Fare}) + \beta_{1}\text{Age}}}\]</span></p>
<p>Because of the exponential transformation, even if we hold fare constant, <strong>the resulting probability curve will non-linearly change for different fare values</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the new probability lines</span>
<span class="kw">ggplot</span>(age_fare_pred, <span class="kw">aes</span>(Age, prob, <span class="dt">group =</span> Fare, <span class="dt">color =</span> Fare)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Predicted probability of survival&quot;</span>,
       <span class="dt">subtitle =</span> <span class="st">&quot;Age + Fare model&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Predicted probability of survival&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/fd-non-parallel-prob-1.png" width="672" /></p>
<p>So when calculating first differences and predicted probabilities for a single variable in a multiple variable logistic regression models, <strong>the values at which you hold the other variables constant will directly influence your results</strong>. The general rule of thumb is to hold the other variables constant at their <strong>median</strong> (if continuous) or <strong>modal</strong> (if discrete) values.</p>
</div>
<div id="interactive-terms" class="section level2">
<h2>Interactive terms</h2>
<p>The additive assumption of linear regression also holds true for logistic regression: the relationships between predictors and responses are independent from one another. So for the age and gender example, we assume our function <span class="math inline">\(f\)</span> is:</p>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Sex}}}{1 + e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Sex}}}\]</span></p>
<p>However once again, that is an assumption. What if the relationship between age and the probability of survival is actually dependent on whether or not the individual is a female? That is, the parameter for age is different for men and women? This possibility would take the functional form:</p>
<p><span class="math display">\[p(\text{Survival}) = \frac{e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Sex} + \beta_{3} \times \text{Age} \times \text{Sex}}}{1 + e^{\beta_0 + \beta_{1}\text{Age} + \beta_{2}\text{Sex} + \beta_{3} \times \text{Age} \times \text{Sex}}}\]</span></p>
<p>This is considered an <strong>interaction</strong> between age and gender. To estimate this in R, we simply specify <code>Age * Sex</code> in our formula for the <code>glm()</code> function:<a href="#fn8" class="footnoteRef" id="fnref8"><sup>8</sup></a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">survive_age_woman_x &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Sex, <span class="dt">data =</span> titanic,
                           <span class="dt">family =</span> binomial)
<span class="kw">summary</span>(survive_age_woman_x)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Age * Sex, family = binomial, data = titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9401  -0.7136  -0.5883   0.7626   2.2455  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  0.59380    0.31032   1.913  0.05569 . 
## Age          0.01970    0.01057   1.863  0.06240 . 
## Sexmale     -1.31775    0.40842  -3.226  0.00125 **
## Age:Sexmale -0.04112    0.01355  -3.034  0.00241 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 964.52  on 713  degrees of freedom
## Residual deviance: 740.40  on 710  degrees of freedom
## AIC: 748.4
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>How can we interpret these parameters? Because the gender variable is binary (0 if female, 1 if male), it acts as a switch on the regression equation. So for women, the relationship between age and probability of survival is:<a href="#fn9" class="footnoteRef" id="fnref9"><sup>9</sup></a></p>
<p><span class="math display">\[p(\text{Survival}_{female}) = \frac{e^{\beta_0 + \beta_{1}\text{Age} + \beta_{3} \times \text{Age} \times 0}}{1 + e^{\beta_0 + \beta_{1}\text{Age} + \beta_{3} \times \text{Age} \times 0}}\]</span></p>
<p>which reduces to</p>
<p><span class="math display">\[p(\text{Survival}_{female}) = \frac{e^{\beta_0 + \beta_{1}\text{Age}}}{1 + e^{\beta_0 + \beta_{1}\text{Age}}}\]</span></p>
<p>However for men, the resulting equation looks different:</p>
<p><span class="math display">\[p(\text{Survival}_{male}) = \frac{e^{\beta_0 + \beta_{1}\text{Age} + \beta_{3} \times \text{Age} \times 1}}{1 + e^{\beta_0 + \beta_{1}\text{Age} + \beta_{3} \times \text{Age} \times 1}}\]</span></p>
<p>which reduces to</p>
<p><span class="math display">\[p(\text{Survival}_{male}) = \frac{e^{\beta_0 + \beta_{1}\text{Age} + \beta_{3} \times \text{Age}}}{1 + e^{\beta_0 + \beta_{1}\text{Age} + \beta_{3} \times \text{Age}}}\]</span></p>
<p><span class="math display">\[p(\text{Survival}_{male}) = \frac{e^{\beta_0 + (\beta_{1} + \beta_{3})\text{Age}}}{1 + e^{\beta_0 + (\beta_{1} + \beta_{3})\text{Age}}}\]</span></p>
<p>Let’s plot the interactive effects of age and gender by estimating the log-odds and predicted probability of survival.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">titanic_age_sex_x &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">data_grid</span>(Age, Sex) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(survive_age_woman_x) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">logit2prob</span>(pred))
titanic_age_sex_x</code></pre></div>
<pre><code>## # A tibble: 176 × 4
##      Age    Sex       pred      prob
##    &lt;dbl&gt;  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1   0.42 female  0.6020758 0.6461311
## 2   0.42   male -0.7329451 0.3245488
## 3   0.67 female  0.6070013 0.6472564
## 4   0.67   male -0.7382992 0.3233762
## 5   0.75 female  0.6085774 0.6476162
## 6   0.75   male -0.7400125 0.3230014
## 7   0.83 female  0.6101536 0.6479758
## 8   0.83   male -0.7417258 0.3226269
## 9   0.92 female  0.6119268 0.6483802
## 10  0.92   male -0.7436533 0.3222058
## # ... with 166 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(titanic_age_sex_x, <span class="kw">aes</span>(Age, pred, <span class="dt">color =</span> Sex)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Log-odds of surviving the Titanic&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Log-odds of survival&quot;</span>,
       <span class="dt">color =</span> <span class="st">&quot;Sex&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/age_woman_plot_logodds-1.png" width="672" /></p>
<p>For the log-odds (i.e. based directly on the parameter values), we can see that the interactive term changes the <strong>slope</strong> of the line for age. For women the slope of the line is positive (0.594), whereas for men the slope is negative (-0.724).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># join data frames of interactive and non-interactive model</span>
<span class="kw">bind_rows</span>(<span class="kw">list</span>(<span class="st">&quot;Age + Sex&quot;</span> =<span class="st"> </span>titanic_age_sex <span class="op">%&gt;%</span>
<span class="st">                 </span><span class="kw">rename</span>(<span class="dt">prob =</span> pred),
               <span class="st">&quot;Age x Sex&quot;</span> =<span class="st"> </span>titanic_age_sex_x), <span class="dt">.id =</span> <span class="st">&quot;id&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># plot the two models</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(Age, prob, <span class="dt">color =</span> Sex, <span class="dt">linetype =</span> id)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Probability of surviving the Titanic&quot;</span>,
       <span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Predicted probability of survival&quot;</span>,
       <span class="dt">color =</span> <span class="st">&quot;Sex&quot;</span>,
       <span class="dt">linetype =</span> <span class="st">&quot;Model&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/age_woman_plot_prob-1.png" width="672" /></p>
<p>And now our minds are blown once again! For women, as age increases the probability of survival also increases. However for men, we see the opposite relationship: as age increases the probability of survival <strong>decreases</strong>. Again, the basic principle of saving women and children first can be seen empirically in the estimated probability of survival. Male children are treated similarly to female children, and their survival is prioritized. Even still, the probability of survival is always worse for men than women, but the regression function clearly shows a difference from our previous results.</p>
<p>You may think then that it makes sense to throw in interaction terms (and potentially quadratic terms) willy-nilly to all your regression models since we never know for sure if the relationship is strictly linear and independent. You could do that, but once you start adding more predictors (3, 4, 5, etc.) that will get very difficult to keep track of (five-way interactions are extremely difficult to interpret - even three-way get to be problematic). The best advice is to use theory and your domain knowledge as your guide. Do you have a reason to believe the relationship should be interactive? If so, test for it. If not, don’t.</p>
</div>
</div>
<div id="evaluating-model-accuracy" class="section level1">
<h1>Evaluating model accuracy</h1>
<p>We need a method to evaluate the overall accuracy of a model. This allows us to determine if we have a good or bad model (at least based on predictive power), and compare alternative model specifications to each other. For classification methods such as logistic regression, there are a few different metrics we can use:</p>
<ul>
<li>Accuracy/error rate</li>
<li>Proportional reduction in error</li>
<li>Receiver operating characteristics (ROC) curve and area under the curve (AUC)</li>
</ul>
<div id="accuracy-of-predictions" class="section level2">
<h2>Accuracy of predictions</h2>
<p>One evalation criteria simply asks: how accurate are the predictions? For instance, how often did our basic model just using age correctly predict who survived and died? First we need to get the predicted probabilities for each individual in the original dataset and convert the probability to a prediction - that is, classify the individual as either a <strong>survivor</strong> or <strong>dead</strong>. The standard threshold for binary classification problems is <span class="math inline">\(.5\)</span>; any individual with a predicted probability greater than or equal to <span class="math inline">\(.5\)</span> would be classified as a 1 (or survivor), and any predicted probability less than <span class="math inline">\(.5\)</span> would be classified as a 0 (or dead).<a href="#fn10" class="footnoteRef" id="fnref10"><sup>10</sup></a> Once we make our predictions, then we calculate what percentage of predictions were correct.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">age_accuracy &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(survive_age) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">logit2prob</span>(pred),
         <span class="dt">pred =</span> <span class="kw">as.numeric</span>(pred <span class="op">&gt;</span><span class="st"> </span>.<span class="dv">5</span>))

<span class="kw">mean</span>(age_accuracy<span class="op">$</span>Survived <span class="op">==</span><span class="st"> </span>age_accuracy<span class="op">$</span>pred, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.5938375</code></pre>
<p><span class="math inline">\(59.4\%\)</span> of the predictions based on age only were correct. Is this good or bad? Well, that depends on what you consider your <strong>baseline</strong>. It’s certainly better than an accuracy rate of <span class="math inline">\(0\%\)</span>, but is that what we should compare it to?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create a function to calculate the modal value of a vector</span>
getmode &lt;-<span class="st"> </span><span class="cf">function</span>(v) {
   uniqv &lt;-<span class="st"> </span><span class="kw">unique</span>(v)
   uniqv[<span class="kw">which.max</span>(<span class="kw">tabulate</span>(<span class="kw">match</span>(v, uniqv)))]
}</code></pre></div>
<p>Instead we should compare the model’s accuracy rate to a simple but useless classifier that says predicts <strong>no individuals will survive the sinking of the Titanic</strong>. Because death is the <a href="https://en.wikipedia.org/wiki/Mode_(statistics)">modal</a> category, if we predict that every single person will die we would achieve an accuracy rate of <span class="math inline">\(59.4\%\)</span>. Which coincidentially is exactly the accuracy rate for our age-only model. What gives?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(titanic_age, <span class="kw">aes</span>(Age, pred)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Relationship between age and surviving the Titanic&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Predicted probability of survival&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/plot-pred2-1.png" width="672" /></p>
<p>Oh yeah. If you look at the graph, the predicted probability curve for age is always below <span class="math inline">\(.5\)</span> for the potential age range, so the model actually does act like a modal model - it always predicts death. So our fancy logistic regression model does no better than the useless classifier. What about our interactive age and gender model?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x_accuracy &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(survive_age_woman_x) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">logit2prob</span>(pred),
         <span class="dt">prob =</span> pred,
         <span class="dt">pred =</span> <span class="kw">as.numeric</span>(pred <span class="op">&gt;</span><span class="st"> </span>.<span class="dv">5</span>))

<span class="kw">mean</span>(x_accuracy<span class="op">$</span>Survived <span class="op">==</span><span class="st"> </span>x_accuracy<span class="op">$</span>pred, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.780112</code></pre>
<p>This model is much better. Just by knowing an individual’s age and gender, we can predict with 78% whether he/she lives or dies.</p>
</div>
<div id="proportional-reduction-in-error" class="section level2">
<h2>Proportional reduction in error</h2>
<p><strong>Proportional reduction in error</strong> (PRE) is a formalized way of comparing a model’s accuracy rate to the baseline. It is defined by</p>
<p><span class="math display">\[PRE = \frac{E_1 - E_2}{E_1}\]</span></p>
<p>where <span class="math inline">\(E_1\)</span> is the number of prediction errors in the null model (i.e. useless classifier) and <span class="math inline">\(E_2\)</span> is the number of prediction errors in the statistical learning model. It will range in value between <span class="math inline">\([0,1]\)</span> or <span class="math inline">\([0\%,100\%]\)</span>. <span class="math inline">\(0\%\)</span> means the statistical model reduced none of the prediction error, and <span class="math inline">\(100\%\)</span> means the statistical model eliminated all of the prediction error.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># function to calculate PRE for a logistic regression model</span>
PRE &lt;-<span class="st"> </span><span class="cf">function</span>(model){
  <span class="co"># get the actual values for y from the data</span>
  y &lt;-<span class="st"> </span>model<span class="op">$</span>y
  
  <span class="co"># get the predicted values for y from the model</span>
  y.hat &lt;-<span class="st"> </span><span class="kw">round</span>(model<span class="op">$</span>fitted.values)
  
  <span class="co"># calculate the errors for the null model and your model</span>
  E1 &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">!=</span><span class="st"> </span><span class="kw">median</span>(y))
  E2 &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">!=</span><span class="st"> </span>y.hat)
  
  <span class="co"># calculate the proportional reduction in error</span>
  PRE &lt;-<span class="st"> </span>(E1 <span class="op">-</span><span class="st"> </span>E2) <span class="op">/</span><span class="st"> </span>E1
  <span class="kw">return</span>(PRE)
}</code></pre></div>
<p>So for the age-only model, the PRE is</p>
<p><span class="math display">\[PRE_{\text{Age}} = \frac{290 - 290}{290}\]</span></p>
<p><span class="math display">\[PRE_{\text{Age}} = \frac{0}{290}\]</span></p>
<p><span class="math display">\[PRE_{\text{Age}} = 0\%\]</span></p>
<p>For the interactive age and gender model, the PRE is</p>
<p><span class="math display">\[PRE_{\text{Age x Gender}} = \frac{290 - 157}{290}\]</span></p>
<p><span class="math display">\[PRE_{\text{Age x Gender}} = \frac{133}{290}\]</span></p>
<p><span class="math display">\[PRE_{\text{Age x Gender}} = 45.9\%\]</span></p>
<p>We’ve reduced the error from the useless classifier by <span class="math inline">\(45.9\%\)</span></p>
</div>
<div id="receiver-operating-characteristics-roc-curve" class="section level2">
<h2>Receiver operating characteristics (ROC) curve</h2>
<div id="types-of-error" class="section level3">
<h3>Types of error</h3>
<p>Binary classifiers such as logistic regression make two types of error.</p>
<div class="figure">
<img src="http://marginalrevolution.com/wp-content/uploads/2014/05/Type-I-and-II-errors1-625x468.jpg" />

</div>
<p>Personally I hate the terms type I and type II because I never remember which is which. The above diagram may help, but instead let’s adopt the terms <strong>false positive</strong> and <strong>false negative</strong>.</p>
<p>In the context of the Titanic model, we could make two mistakes:</p>
<ol style="list-style-type: decimal">
<li>False positive - predict an individual survived the Titanic, when in fact the individual died.</li>
<li>False negative - predict an individual died on the Titanic, when in fact the individual survived.</li>
</ol>
</div>
<div id="confusion-matrix" class="section level3">
<h3>Confusion matrix</h3>
<p>Previously all we cared about was the overall accuracy rate of the model, but we may also care about the accuracy or error rate for both types of errors. To do that, we generate a <strong>confusion matrix</strong> using the <code>confusionMatrix()</code> function from the <code>caret</code> library.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(caret)  <span class="co"># load the caret package to use the confusionMatrix function</span>
cm_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">confusionMatrix</span>(x_accuracy<span class="op">$</span>pred, x_accuracy<span class="op">$</span>Survived)
cm_<span class="dv">5</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 360  93
##          1  64 197
##                                        
##                Accuracy : 0.78         
##                  95% CI : (0.748, 0.81)
##     No Information Rate : 0.594        
##     P-Value [Acc &gt; NIR] : &lt;2e-16       
##                                        
##                   Kappa : 0.537        
##  Mcnemar&#39;s Test P-Value : 0.0254       
##                                        
##             Sensitivity : 0.849        
##             Specificity : 0.679        
##          Pos Pred Value : 0.795        
##          Neg Pred Value : 0.755        
##              Prevalence : 0.594        
##          Detection Rate : 0.504        
##    Detection Prevalence : 0.634        
##       Balanced Accuracy : 0.764        
##                                        
##        &#39;Positive&#39; Class : 0            
## </code></pre>
<p>The rows define the predicted outcomes and the columns define the actual (or reference) outcomes for individuals in the dataset. Ideally we want the off-diagonal cells to be 0 because we perfectly predicted all observations. However we can see that isn’t always the case with this model.</p>
</div>
<div id="alternative-thresholds" class="section level3">
<h3>Alternative thresholds</h3>
<p>Perhaps instead of boosting overall model accuracy, we instead care more about improving class-specific accuracy. For example, if we want to increase <strong>sensitivity/recall</strong> we need to increase the true positive rate (TPR):</p>
<p><span class="math display">\[TPR = \frac{\text{Number of actual positives correctly predicted}}{\text{Number of actual positives}}\]</span></p>
<p>However if we are concerned with increasing <strong>specificity</strong> we need to increase the true negative rate (TNR):</p>
<p><span class="math display">\[TNR = \frac{\text{Number of actual negatives correctly predicted}}{\text{Number of actual negatives}}\]</span></p>
<p>While the only way to achieve higher sensitivity <strong>and</strong> specificity is to estimate a better model, we can use our existing model to meet one of these goals. We do this by adjusting our <strong>threshold</strong>, or the cut-off point for classifying individuals as survivors or dead. The confusion matrix above also calculates the sensitivity and specificity of the predictive model. For the original threshold of <span class="math inline">\(.5\)</span>, our true positive rate (or sensitivity) was 0.849. What about for a threshold of <span class="math inline">\(.8\)</span>?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">threshold_<span class="dv">8</span> &lt;-<span class="st"> </span>titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(survive_age_woman_x) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">logit2prob</span>(pred),
         <span class="dt">pred =</span> <span class="kw">as.numeric</span>(pred <span class="op">&gt;</span><span class="st"> </span>.<span class="dv">8</span>))

cm_<span class="dv">8</span> &lt;-<span class="st"> </span><span class="kw">confusionMatrix</span>(threshold_<span class="dv">8</span><span class="op">$</span>pred, threshold_<span class="dv">8</span><span class="op">$</span>Survived)
cm_<span class="dv">8</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 413 253
##          1  11  37
##                                           
##                Accuracy : 0.6303          
##                  95% CI : (0.5937, 0.6658)
##     No Information Rate : 0.5938          
##     P-Value [Acc &gt; NIR] : 0.02556         
##                                           
##                   Kappa : 0.1171          
##  Mcnemar&#39;s Test P-Value : &lt; 2e-16         
##                                           
##             Sensitivity : 0.9741          
##             Specificity : 0.1276          
##          Pos Pred Value : 0.6201          
##          Neg Pred Value : 0.7708          
##              Prevalence : 0.5938          
##          Detection Rate : 0.5784          
##    Detection Prevalence : 0.9328          
##       Balanced Accuracy : 0.5508          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>With a threshold of <span class="math inline">\(.8\)</span>, sensitivity increases to 0.974, but notice the trade-off: overall accuracy has decreased from 0.78 to 0.63, and specificity has also declined substantially. This reveals the trade-off we have to make between sensitivity and specificity.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># function to calculate key stats for the Titanic data</span>
threshold_compare &lt;-<span class="st"> </span><span class="cf">function</span>(threshold, data, model){
  <span class="co"># generate predictions</span>
  pred &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">add_predictions</span>(model) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">logit2prob</span>(pred),
           <span class="dt">pred =</span> <span class="kw">as.numeric</span>(pred <span class="op">&gt;</span><span class="st"> </span>threshold))
  
  <span class="co"># get confusion matrix</span>
  cm &lt;-<span class="st"> </span><span class="kw">confusionMatrix</span>(pred<span class="op">$</span>pred, pred<span class="op">$</span>Survived)
  
  <span class="co"># extract sensitivity and threshold to data_frame</span>
  <span class="kw">data_frame</span>(<span class="dt">threshold =</span> threshold,
             <span class="dt">sensitivity =</span> cm<span class="op">$</span>byClass[[<span class="st">&quot;Sensitivity&quot;</span>]],
             <span class="dt">specificity =</span> cm<span class="op">$</span>byClass[[<span class="st">&quot;Specificity&quot;</span>]],
             <span class="dt">accuracy =</span> cm<span class="op">$</span>overall[[<span class="st">&quot;Accuracy&quot;</span>]])
}

threshold_x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">by =</span> .<span class="dv">001</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">map_df</span>(threshold_compare, titanic, survive_age_woman_x) 

threshold_x <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(measure, value, <span class="op">-</span>threshold) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">measure =</span> <span class="kw">factor</span>(measure, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Accuracy&quot;</span>, <span class="st">&quot;Sensitivity&quot;</span>, <span class="st">&quot;Specificity&quot;</span>))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(threshold, value, <span class="dt">color =</span> measure, <span class="dt">linetype =</span> measure)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Threshold&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Accuracy rate&quot;</span>,
       <span class="dt">color =</span> <span class="st">&quot;Measure&quot;</span>,
       <span class="dt">linetype =</span> <span class="st">&quot;Measure&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/threshold-compare-1.png" width="672" /></p>
<p>By graphing across many alternative thresholds, we can select a threshold level at the trade-off for which we are comfortable based on a visual inspection. But is that really the best approach? In order to make that determination we must have <strong>domain knowledge</strong> about about the benefits and costs to making that decision.</p>
</div>
<div id="roc-curve" class="section level3">
<h3>ROC curve</h3>
<p>A receiver operating characteristic (ROC) curve is an alternative graphical method for comparing the types of errors for differing thresholds. In this graph, you plot the false positive rate vs. the true positive rate (i.e. 1- specificity vs. sensitivity).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(threshold_x, <span class="kw">aes</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>specificity, sensitivity)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>)</code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/roc-ggplot-1.png" width="672" /></p>
<p>The overall performance of the classifier across all potential thresholds is the <strong>area under the (ROC) curve</strong> (AUC). The ideal AUC curve hugs the top left corner of the graph, so a larger AUC indicates a better classifier. An AUC of <span class="math inline">\(1\)</span> means perfect prediction for any threshold value. The dashed line represents the null model where we randomly guess whether individuals are survivors or dead (i.e. flipped a coin) and would have an AUC of <span class="math inline">\(.5\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(pROC)
roc_x &lt;-<span class="st"> </span><span class="kw">roc</span>(x_accuracy<span class="op">$</span>Survived, x_accuracy<span class="op">$</span>prob)
<span class="kw">plot</span>(roc_x)   <span class="co"># use pROC to draw the ROC curve</span></code></pre></div>
<p><img src="persp004_logistic_regression_files/figure-html/roc-auc-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># calculate the AUC</span>
auc_x &lt;-<span class="st"> </span><span class="kw">auc</span>(x_accuracy<span class="op">$</span>Survived, x_accuracy<span class="op">$</span>prob)
auc_x</code></pre></div>
<pre><code>## Area under the curve: 0.787</code></pre>
<p>With an AUC of 0.787, this model performs decently.</p>
</div>
</div>
</div>
<div id="session-info" class="section level1 toc-ignore">
<h1>Session Info</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">devtools<span class="op">::</span><span class="kw">session_info</span>()</code></pre></div>
<pre><code>##  setting  value                       
##  version  R version 3.4.1 (2017-06-30)
##  system   x86_64, darwin15.6.0        
##  ui       X11                         
##  language (EN)                        
##  collate  en_US.UTF-8                 
##  tz       America/Chicago             
##  date     2017-08-01                  
## 
##  package      * version    date       source                              
##  assertthat     0.2.0      2017-04-11 CRAN (R 3.4.0)                      
##  backports      1.1.0      2017-05-22 CRAN (R 3.4.0)                      
##  base         * 3.4.1      2017-07-07 local                               
##  base64enc      0.1-3      2015-07-28 CRAN (R 3.4.0)                      
##  bindr          0.1        2016-11-13 CRAN (R 3.4.0)                      
##  bindrcpp     * 0.2        2017-06-17 CRAN (R 3.4.0)                      
##  bit            1.1-12     2014-04-09 CRAN (R 3.4.0)                      
##  bit64          0.9-7      2017-05-08 CRAN (R 3.4.0)                      
##  blob           1.1.0      2017-06-17 CRAN (R 3.4.0)                      
##  boxes          0.0.0.9000 2017-07-19 Github (r-pkgs/boxes@03098dc)       
##  broom        * 0.4.2      2017-02-13 CRAN (R 3.4.0)                      
##  car            2.1-5      2017-07-04 CRAN (R 3.4.1)                      
##  caret        * 6.0-76     2017-04-18 CRAN (R 3.4.0)                      
##  cellranger     1.1.0      2016-07-27 CRAN (R 3.4.0)                      
##  class          7.3-14     2015-08-30 CRAN (R 3.4.1)                      
##  clisymbols     1.2.0      2017-05-21 cran (@1.2.0)                       
##  codetools      0.2-15     2016-10-05 CRAN (R 3.4.1)                      
##  colorspace     1.3-2      2016-12-14 CRAN (R 3.4.0)                      
##  compiler       3.4.1      2017-07-07 local                               
##  config         0.2        2016-08-02 CRAN (R 3.4.0)                      
##  crayon         1.3.2.9000 2017-07-19 Github (gaborcsardi/crayon@750190f) 
##  datasets     * 3.4.1      2017-07-07 local                               
##  DBI            0.7        2017-06-18 CRAN (R 3.4.0)                      
##  dbplyr         1.1.0      2017-06-27 CRAN (R 3.4.1)                      
##  devtools       1.13.2     2017-06-02 CRAN (R 3.4.0)                      
##  digest         0.6.12     2017-01-27 CRAN (R 3.4.0)                      
##  dplyr        * 0.7.2      2017-07-20 CRAN (R 3.4.1)                      
##  e1071          1.6-8      2017-02-02 CRAN (R 3.4.0)                      
##  evaluate       0.10.1     2017-06-24 CRAN (R 3.4.1)                      
##  forcats      * 0.2.0      2017-01-23 CRAN (R 3.4.0)                      
##  foreach        1.4.3      2015-10-13 CRAN (R 3.4.0)                      
##  foreign        0.8-69     2017-06-22 CRAN (R 3.4.1)                      
##  gapminder    * 0.2.0      2015-12-31 CRAN (R 3.4.0)                      
##  gganimate    * 0.1.0.9000 2017-05-26 Github (dgrtwo/gganimate@bf82002)   
##  ggplot2      * 2.2.1      2016-12-30 CRAN (R 3.4.0)                      
##  glue           1.1.1      2017-06-21 CRAN (R 3.4.1)                      
##  graphics     * 3.4.1      2017-07-07 local                               
##  grDevices    * 3.4.1      2017-07-07 local                               
##  grid           3.4.1      2017-07-07 local                               
##  gtable         0.2.0      2016-02-26 CRAN (R 3.4.0)                      
##  haven          1.1.0      2017-07-09 CRAN (R 3.4.1)                      
##  highr          0.6        2016-05-09 CRAN (R 3.4.0)                      
##  hms            0.3        2016-11-22 CRAN (R 3.4.0)                      
##  htmltools      0.3.6      2017-04-28 CRAN (R 3.4.0)                      
##  httpuv         1.3.5      2017-07-04 CRAN (R 3.4.1)                      
##  httr           1.2.1      2016-07-03 CRAN (R 3.4.0)                      
##  iterators      1.0.8      2015-10-13 CRAN (R 3.4.0)                      
##  jsonlite       1.5        2017-06-01 CRAN (R 3.4.0)                      
##  knitr        * 1.16       2017-05-18 CRAN (R 3.4.0)                      
##  labeling       0.3        2014-08-23 CRAN (R 3.4.0)                      
##  lattice      * 0.20-35    2017-03-25 CRAN (R 3.4.1)                      
##  lazyeval       0.2.0      2016-06-12 CRAN (R 3.4.0)                      
##  lme4           1.1-13     2017-04-19 CRAN (R 3.4.0)                      
##  lubridate      1.6.0      2016-09-13 CRAN (R 3.4.0)                      
##  magrittr       1.5        2014-11-22 CRAN (R 3.4.0)                      
##  MASS           7.3-47     2017-02-26 CRAN (R 3.4.1)                      
##  Matrix         1.2-10     2017-05-03 CRAN (R 3.4.1)                      
##  MatrixModels   0.4-1      2015-08-22 CRAN (R 3.4.0)                      
##  memoise        1.1.0      2017-04-21 CRAN (R 3.4.0)                      
##  methods        3.4.1      2017-07-07 local                               
##  mgcv           1.8-18     2017-07-28 CRAN (R 3.4.1)                      
##  mime           0.5        2016-07-07 CRAN (R 3.4.0)                      
##  minqa          1.2.4      2014-10-09 CRAN (R 3.4.0)                      
##  mnormt         1.5-5      2016-10-15 CRAN (R 3.4.0)                      
##  ModelMetrics   1.1.0      2016-08-26 CRAN (R 3.4.0)                      
##  modelr       * 0.1.1      2017-07-24 CRAN (R 3.4.1)                      
##  munsell        0.4.3      2016-02-13 CRAN (R 3.4.0)                      
##  nlme           3.1-131    2017-02-06 CRAN (R 3.4.1)                      
##  nloptr         1.0.4      2014-08-04 CRAN (R 3.4.0)                      
##  nnet           7.3-12     2016-02-02 CRAN (R 3.4.1)                      
##  nycflights13   0.2.2      2017-01-27 CRAN (R 3.4.0)                      
##  parallel       3.4.1      2017-07-07 local                               
##  pbkrtest       0.4-7      2017-03-15 CRAN (R 3.4.0)                      
##  pkgconfig      2.0.1      2017-03-21 CRAN (R 3.4.0)                      
##  plyr           1.8.4      2016-06-08 CRAN (R 3.4.0)                      
##  pROC         * 1.10.0     2017-06-10 CRAN (R 3.4.0)                      
##  psych          1.7.5      2017-05-03 CRAN (R 3.4.1)                      
##  purrr        * 0.2.2.2    2017-05-11 CRAN (R 3.4.0)                      
##  quantreg       5.33       2017-04-18 CRAN (R 3.4.0)                      
##  R6             2.2.2      2017-06-17 CRAN (R 3.4.0)                      
##  rappdirs       0.3.1      2016-03-28 CRAN (R 3.4.0)                      
##  rcfss        * 0.1.5      2017-07-31 local                               
##  Rcpp           0.12.12    2017-07-15 CRAN (R 3.4.1)                      
##  readr        * 1.1.1      2017-05-16 CRAN (R 3.4.0)                      
##  readxl         1.0.0      2017-04-18 CRAN (R 3.4.0)                      
##  reshape2       1.4.2      2016-10-22 CRAN (R 3.4.0)                      
##  rlang          0.1.1      2017-05-18 CRAN (R 3.4.0)                      
##  rmarkdown      1.6        2017-06-15 CRAN (R 3.4.0)                      
##  rprojroot      1.2        2017-01-16 CRAN (R 3.4.0)                      
##  RSQLite      * 2.0        2017-06-19 CRAN (R 3.4.1)                      
##  rstudioapi     0.6        2016-06-27 CRAN (R 3.4.0)                      
##  rvest          0.3.2      2016-06-17 CRAN (R 3.4.0)                      
##  scales         0.4.1      2016-11-09 CRAN (R 3.4.0)                      
##  shiny          1.0.3      2017-04-26 CRAN (R 3.4.0)                      
##  sparklyr     * 0.6.0      2017-07-29 CRAN (R 3.4.1)                      
##  SparseM        1.77       2017-04-23 CRAN (R 3.4.0)                      
##  splines        3.4.1      2017-07-07 local                               
##  stats        * 3.4.1      2017-07-07 local                               
##  stats4         3.4.1      2017-07-07 local                               
##  stringi        1.1.5      2017-04-07 CRAN (R 3.4.0)                      
##  stringr      * 1.2.0      2017-02-18 CRAN (R 3.4.0)                      
##  tibble       * 1.3.3      2017-05-28 CRAN (R 3.4.0)                      
##  tidyr        * 0.6.3      2017-05-15 CRAN (R 3.4.0)                      
##  tidyverse    * 1.1.1.9000 2017-07-19 Github (tidyverse/tidyverse@a028619)
##  titanic      * 0.1.0      2015-08-31 CRAN (R 3.4.0)                      
##  tools          3.4.1      2017-07-07 local                               
##  tweenr       * 0.1.5      2016-10-10 CRAN (R 3.4.0)                      
##  utils        * 3.4.1      2017-07-07 local                               
##  withr          2.0.0      2017-07-28 CRAN (R 3.4.1)                      
##  xml2           1.1.1      2017-01-24 CRAN (R 3.4.0)                      
##  xtable         1.8-2      2016-02-05 CRAN (R 3.4.0)                      
##  yaml           2.1.14     2016-11-12 CRAN (R 3.4.0)</code></pre>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>General at least as applied to the Titanic. I’d like to think technology has advanced some since the early 20th century that the same patterns do not apply today. <a href="https://en.wikipedia.org/wiki/Costa_Concordia_disaster">Not that sinking ships have gone away.</a><a href="#fnref1">↩</a></p></li>
<li id="fn2"><p><code>library(titanic)</code> contains both <code>titanic_train</code> and <code>titanic_test</code>. We want to use only <code>titanic_train</code> today. We’ll discuss the importance of <code>titanic_test</code> next week.<a href="#fnref2">↩</a></p></li>
<li id="fn3"><p>Given Rose’s condition in the present-day of the film, it’s not outside the realm of possibility.<a href="#fnref3">↩</a></p></li>
<li id="fn4"><p>Alternatively, you may see the function written</p>
<p><span class="math display">\[p(X) = \frac{1}{1 + e^{-(\beta_0 + \beta_{1}X)}}\]</span><a href="#fnref4">↩</a></p></li>
<li id="fn5"><p>The threshold can be adjusted depending on how conservative or risky of a prediction you wish to make.<a href="#fnref5">↩</a></p></li>
<li id="fn6"><p>Given <a href="http://www.footballdb.com/teams/nfl/pittsburgh-steelers/teamvsteam?opp=8">recent history</a>, this will probably occur.<a href="#fnref6">↩</a></p></li>
<li id="fn7"><p>Alternatively, we can use <code>broom::augment()</code> to add predicted probabilities for the original dataset:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(broom)

<span class="kw">augment</span>(survive_age, <span class="dt">newdata =</span> titanic, <span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">as_tibble</span>()</code></pre></div>
<pre><code>## # A tibble: 714 x 14
##    PassengerId Survived Pclass
##          &lt;int&gt;    &lt;int&gt;  &lt;int&gt;
##  1           1        0      3
##  2           2        1      1
##  3           3        1      3
##  4           4        1      1
##  5           5        0      3
##  6           7        0      1
##  7           8        0      3
##  8           9        1      3
##  9          10        1      2
## 10          11        1      3
## # ... with 704 more rows, and 11 more variables: Name &lt;chr&gt;, Sex &lt;chr&gt;,
## #   Age &lt;dbl&gt;, SibSp &lt;int&gt;, Parch &lt;int&gt;, Ticket &lt;chr&gt;, Fare &lt;dbl&gt;,
## #   Cabin &lt;chr&gt;, Embarked &lt;chr&gt;, .fitted &lt;dbl&gt;, .se.fit &lt;dbl&gt;</code></pre>
<ul>
<li><code>newdata = titanic</code> - produces a data frame containing all the original variables + the predicted probability for the observation</li>
<li><code>type.predict = &quot;response&quot;</code> - ensures we get the predicted probabilities, not the logged version</li>
</ul>
<a href="#fnref7">↩</a></li>
<li id="fn8"><p>R automatically includes constituent terms, so this turns into <code>Age + Sex + Age * Sex</code>. <a href="https://pan-oxfordjournals-org.proxy.uchicago.edu/content/14/1/63.full.pdf+html">Generally you always want to include constituent terms in a regression model with an interaction.</a><a href="#fnref8">↩</a></p></li>
<li id="fn9"><p><span class="math inline">\(\beta_{2}\text{sex}\)</span> can be factored out since it does not contain age as a constituent term.<a href="#fnref9">↩</a></p></li>
<li id="fn10"><p>We will discuss later on the effect of different threshold values.<a href="#fnref10">↩</a></p></li>
</ol>
</div>

<p>This work is licensed under the  <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 Creative Commons License</a>.</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
