---
title: "Day 0: Installing Software"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# Introduction

This course teaches students how to think programatically and use computational approaches to explore and address social scientific questions. Much of computer programming involves translating what you wish to do into a set of computational instructions. Think of human languages: languages conform to specific sets of grammatical and syntax rules which define how to interpret elements of speech such as nouns, verbs, and adjectives. Some languages have simple rules and are (relatively) easy to learn; others follow more complex rules that require greater effort in order to gain fluency.^[[Language Difficulty Rankings](http://www.effectivelanguagelearning.com/language-guide/language-difficulty)] Some languages derive from a common source and therefore share many similarities that make it easier to learn a second language within the same family of languages. So a native Spanish speaker will find it easier to learn French rather than Chinese, because French and Spanish share many grammatical rules and root derivations of words whereas Chinese and Spanish do not. Regardless, these are all perfectly usable languages humans use to communicate with one another.

In this course, we will learn how to use two specific languages to write programs and conduct data analysis: [R](https://www.r-project.org/) and [Python](https://www.python.org/).


# To do

Before we can do any of this, we need to install all the necessary software and get it setup and working.

* [Why R and Python?](setup01.html)
* [Setup R](setup03.html)
* [Setup Python](setup02.html)
* Git
    * [What is Git?](git00.html)
    * Installation
        * [Register a free GitHub account.](https://github.com/) As a university student, also check to see if you are eligible for [GitHub Education offers](https://education.github.com/). Some of these are very useful, such as unlimited [private repositories](https://help.github.com/articles/what-plan-should-i-choose/). Remember that once you create a GitHub account, you are stuck with that username. Choose something professional and start building a positive social media presence.
        * [Install Git](git01.html)
        * [Install Git client](git02.html)
    * Configure Git/GitHub
        * [Personalize Git](git03.html)
        * [Git -> GitHub](git04.html)
    * Configure Git with R and Python
        * [Using Git within RStudio](git05.html)
        * [Using Git with Python and Jupyter Notebooks](git06.html)
        * [GitHub credentials and avoiding monotony](git07.html)
        * [Complete homework 01](hw01_edit-README.html)


