<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Text analysis: fundamentals and sentiment analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45631879-2', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 66px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 71px;
  margin-top: -71px;
}

.section h2 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h3 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h4 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h5 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h6 {
  padding-top: 71px;
  margin-top: -71px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Computing for the Social Sciences</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="faq.html">FAQ</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->
<p><strong>This content is from the fall 2016 version of this course. Please go <a href = "https://uc-cfss.github.io">here</a> for the most recent version.</strong></p>

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Text analysis: fundamentals and sentiment analysis</h1>

</div>


<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(lubridate)
<span class="kw">library</span>(stringr)
<span class="kw">library</span>(tidytext)
<span class="kw">library</span>(broom)
<span class="kw">library</span>(scales)

<span class="kw">theme_set</span>(<span class="kw">theme_bw</span>())</code></pre></div>
<div id="objectives" class="section level1">
<h1>Objectives</h1>
<ul>
<li>Identify the basic workflow for conducting text analysis</li>
<li>Define <em>sentiment analysis</em> and review how sentiment analysis was used in <em>Conservatives report, but liberals display, greater happiness</em></li>
<li>Define the <em>tidy text format</em></li>
<li>Demonstrate how to conduct sentiment analysis using David Robinson’s <a href="http://varianceexplained.org/r/trump-tweets/">Text analysis of Trump’s tweets confirms he writes only the (angrier) Android half</a></li>
</ul>
</div>
<div id="basic-workflow-for-text-analysis" class="section level1">
<h1>Basic workflow for text analysis</h1>
<p>Draws on <a href="https://dzone.com/articles/common-text-mining-workflow">Common Text Mining Workflow</a></p>
<ul>
<li>Obtain your text sources</li>
<li>Extract documents and move into a corpus</li>
<li>Transformation</li>
<li>Extract features</li>
<li>Perform analysis</li>
</ul>
<div id="obtain-your-text-sources" class="section level2">
<h2>Obtain your text sources</h2>
<p>Can come from lots of areas:</p>
<ul>
<li>Web sites
<ul>
<li>Twitter</li>
</ul></li>
<li>Databases</li>
<li>PDF documents</li>
<li>Digital scans of printed materials</li>
</ul>
<p>The easier to convert your text data into digitally stored text, the cleaner your results and fewer transcription errors</p>
</div>
<div id="extract-documents-and-move-into-a-corpus" class="section level2">
<h2>Extract documents and move into a corpus</h2>
<ul>
<li><em>Text corpus</em> - large and structured set of texts</li>
<li>Typically stores the text as a raw character string with metadata and details stored with the text</li>
</ul>
</div>
<div id="transformation" class="section level2">
<h2>Transformation</h2>
<p>Examples of typical transformations include:</p>
<ul>
<li>Tag segments of speech for part-of-speech (nouns, verbs, adjectives, etc.) or entity recognition (person, place, company, etc.)</li>
<li>Standard text processing
<ul>
<li>Convert to lower case</li>
<li>Remove punctuation</li>
<li>Remove numbers</li>
<li>Remove <em>stopwords</em> - common parts of speech that are not informative such as <em>a</em>, <em>an</em>, <em>be</em>, <em>of</em>, etc.</li>
<li>Remove domain-specific stopwords</li>
<li>Stemming - reduce words to their word stem
<ul>
<li>“Fishing”, “fished”, and “fisher” -&gt; “fish”</li>
</ul></li>
</ul></li>
</ul>
</div>
<div id="extract-features" class="section level2">
<h2>Extract features</h2>
<ul>
<li>Convert the text string into some sort of quantifiable measures</li>
<li>Bag-of-words model
<ul>
<li>Each document is represented as a vector which counts the frequency of each term’s appearance in the document</li>
<li>Combine all the vectors for each document together and you create a <em>term-document matrix</em>
<ul>
<li>Each row is a document</li>
<li>Each column is a term</li>
<li>Each cell represents the frequency of the term appearing in the document</li>
</ul></li>
<li>Ignores context
<ul>
<li>Could randomly scramble the order of terms appearing in the document</li>
<li>Would still get the same term-document matrix</li>
</ul></li>
</ul></li>
</ul>
</div>
<div id="perform-analysis" class="section level2">
<h2>Perform analysis</h2>
<ul>
<li>Lots of approaches to take</li>
<li>Basic
<ul>
<li>Word frequency</li>
<li>Collocation - words commonly appearing near each other</li>
<li>Dictionary tagging - locating a specific set of words in the texts</li>
</ul></li>
<li>Advanced
<ul>
<li>Document classification
<ul>
<li>Supervised</li>
<li>Unsupervised</li>
</ul></li>
<li>Corpora comparison - comparing the content of different groups of text</li>
<li>Detecting clusters of document features - <em>topic modeling</em></li>
</ul></li>
</ul>
</div>
</div>
<div id="conservatives-report-but-liberals-display-greater-happiness" class="section level1">
<h1><em>Conservatives report, but liberals display, greater happiness</em></h1>
<p>Based on a theory of psychology that conservatives are generally happier than liberals. Authors argue that previous findings are flawed because they rely on self-reported happiness, which is an inaccurate measure of individual happiness. Instead, they measure happiness (in part) based on the text of Congressional speeches and Twitter posts.</p>
<div id="sentiment-analysis" class="section level2">
<h2>Sentiment analysis</h2>
<p><em>Sentiment analysis</em> uses text analysis to estimate the attitude of a speaker or writer with respect to some topic or the overall polarity of the document. For example, the sentence</p>
<blockquote>
<p>I am happy</p>
</blockquote>
<p>contains words and language typically associated with positive feelings and emotions. Therefore if some one tweeted “I am happy”, we could make an educated guess that the person is expressing positive feelings.</p>
<p>Obviously it would be difficult for us to create a complete dictionary that classifies words based on their emotional affect; fortunately other scholars have already done this for us. Some simply classify words and terms as positive or negative:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>)</code></pre></div>
<pre><code>## # A tibble: 6,788 × 2
##           word sentiment
##          &lt;chr&gt;     &lt;chr&gt;
## 1      2-faced  negative
## 2      2-faces  negative
## 3           a+  positive
## 4     abnormal  negative
## 5      abolish  negative
## 6   abominable  negative
## 7   abominably  negative
## 8    abominate  negative
## 9  abomination  negative
## 10       abort  negative
## # ... with 6,778 more rows</code></pre>
<p>Others rate them on a numeric scale:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_sentiments</span>(<span class="st">&quot;afinn&quot;</span>)</code></pre></div>
<pre><code>## # A tibble: 2,476 × 2
##          word score
##         &lt;chr&gt; &lt;int&gt;
## 1     abandon    -2
## 2   abandoned    -2
## 3    abandons    -2
## 4    abducted    -2
## 5   abduction    -2
## 6  abductions    -2
## 7       abhor    -3
## 8    abhorred    -3
## 9   abhorrent    -3
## 10     abhors    -3
## # ... with 2,466 more rows</code></pre>
<p>Still others rate words based on specific sentiments</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_sentiments</span>(<span class="st">&quot;nrc&quot;</span>)</code></pre></div>
<pre><code>## # A tibble: 13,901 × 2
##           word sentiment
##          &lt;chr&gt;     &lt;chr&gt;
## 1       abacus     trust
## 2      abandon      fear
## 3      abandon  negative
## 4      abandon   sadness
## 5    abandoned     anger
## 6    abandoned      fear
## 7    abandoned  negative
## 8    abandoned   sadness
## 9  abandonment     anger
## 10 abandonment      fear
## # ... with 13,891 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_sentiments</span>(<span class="st">&quot;nrc&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">count</span>(sentiment)</code></pre></div>
<pre><code>## # A tibble: 10 × 2
##       sentiment     n
##           &lt;chr&gt; &lt;int&gt;
## 1         anger  1247
## 2  anticipation   839
## 3       disgust  1058
## 4          fear  1476
## 5           joy   689
## 6      negative  3324
## 7      positive  2312
## 8       sadness  1191
## 9      surprise   534
## 10        trust  1231</code></pre>
<p>In order to assess the document or speaker’s overall sentiment, you simply count up the number of words associated with each sentiment. For instance, <a href="http://tidytextmining.com/sentiment.html#sentiment-analysis-with-inner-join">how positive or negative are Jane Austen’s novels</a>? We can determine this by counting up the number of positive and negative words in each chapter, like so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(janeaustenr)

tidy_books &lt;-<span class="st"> </span><span class="kw">austen_books</span>() %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(book) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">linenumber =</span> <span class="kw">row_number</span>(),
         <span class="dt">chapter =</span> <span class="kw">cumsum</span>(<span class="kw">str_detect</span>(text, <span class="kw">regex</span>(<span class="st">&quot;^chapter [</span><span class="ch">\\</span><span class="st">divxlc]&quot;</span>, 
                                                 <span class="dt">ignore_case =</span> <span class="ot">TRUE</span>)))) %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>() %&gt;%
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text)

janeaustensentiment &lt;-<span class="st"> </span>tidy_books %&gt;%
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">count</span>(book, <span class="dt">index =</span> linenumber %/%<span class="st"> </span><span class="dv">80</span>, sentiment) %&gt;%
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive -<span class="st"> </span>negative)</code></pre></div>
<pre><code>## Joining, by = &quot;word&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(janeaustensentiment, <span class="kw">aes</span>(index, sentiment, <span class="dt">fill =</span> book)) +
<span class="st">        </span><span class="kw">geom_bar</span>(<span class="dt">alpha =</span> <span class="fl">0.8</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">show.legend =</span> <span class="ot">FALSE</span>) +
<span class="st">        </span><span class="kw">facet_wrap</span>(~book, <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">scales =</span> <span class="st">&quot;free_x&quot;</span>)</code></pre></div>
<p><img src="text01_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Ignoring the specific code, this is a relatively simple operation. Once you have the text converted into a format suitable for analysis, tabulating and counting term frequency is not a complicated operation.</p>
<p>You can also conduct further analysis once you have this information. In this article, the researchers used speeches from the Congressional record as their corpus. They read this into a software package, converted the text into individual terms within each politician’s speeches, and counted up the number of positive and negative terms spoken by each member of Congress. Once they had this value for each politician, they could build a statistical model to predict how positive or negative an individual would sound based on known characteristics (e.g. political conservatism/liberalism, party membership, chamber majority, age, ethnicity, sex)</p>
<p>Likewise, the authors performed a similar analysis on a corpus of tweets from followers of the Democratic and Republican parties. Using the Twitter API, they harvested the tweets, imported them into their software, then conducted the same type of analysis - counting the number of positive and negative words in each tweet, then aggregating for each political party.</p>
</div>
</div>
<div id="tidytext" class="section level1">
<h1><code>tidytext</code></h1>
<p>A lot of these actions can be performed using tidy methods, as long as the text is stored in a tidy format. The <a href="https://github.com/juliasilge/tidytext"><code>tidytext</code></a> package is a recent addition to the <code>tidyverse</code> that attempts to implement a tidy framework for text analysis in R. To my knowledge, there is no comparable tidy method for Python. Python is arguably stronger than R in some aspects of text analysis, however if we want to perform this work primarily using a tidy approach R is the way to go.</p>
<div id="tidy-text-format" class="section level2">
<h2>Tidy text format</h2>
<ul>
<li>Defined as one-term-per-row</li>
<li>Differs from the document-term matrix (one-document-per-row and one-term-per-column)</li>
</ul>
</div>
</div>
<div id="exploring-content-of-donald-trumps-twitter-timeline" class="section level1">
<h1>Exploring content of Donald Trump’s Twitter timeline</h1>
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
Every non-hyperbolic tweet is from iPhone (his staff). <br><br>Every hyperbolic tweet is from Android (from him). <a href="https://t.co/GWr6D8h5ed">pic.twitter.com/GWr6D8h5ed</a>
</p>
— Todd Vaziri (@tvaziri) <a href="https://twitter.com/tvaziri/status/762005541388378112">August 6, 2016</a>
</blockquote>
<script async src="http://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>If you want to know what Donald Trump personally tweets from his account versus his handlers, it looks like we might have a way of detecting this difference. Tweets from an iPhone are his staff; tweets from an Android are from him. Can we quantify this behavior or use text analysis to lend evidence to this argument? <strong>Yes</strong>.</p>
<div id="obtaining-documents" class="section level2">
<h2>Obtaining documents</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(twitteR)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;twitteR&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     id, location</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># You&#39;d need to set global options with an authenticated app</span>
<span class="kw">setup_twitter_oauth</span>(<span class="kw">getOption</span>(<span class="st">&quot;twitter_api_key&quot;</span>),
                    <span class="kw">getOption</span>(<span class="st">&quot;twitter_api_token&quot;</span>))

<span class="co"># We can request only 3200 tweets at a time; it will return fewer</span>
<span class="co"># depending on the API</span>
trump_tweets &lt;-<span class="st"> </span><span class="kw">userTimeline</span>(<span class="st">&quot;realDonaldTrump&quot;</span>, <span class="dt">n =</span> <span class="dv">3200</span>)
trump_tweets_df &lt;-<span class="st"> </span>trump_tweets %&gt;%
<span class="st">  </span><span class="kw">map_df</span>(as.data.frame) %&gt;%
<span class="st">  </span><span class="kw">tbl_df</span>()</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># if you want to follow along without setting up Twitter authentication,</span>
<span class="co"># just use this dataset:</span>
<span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;http://varianceexplained.org/files/trump_tweets_df.rda&quot;</span>))</code></pre></div>
</div>
<div id="clean-up-the-data" class="section level2">
<h2>Clean up the data</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweets &lt;-<span class="st"> </span>trump_tweets_df %&gt;%
<span class="st">  </span><span class="kw">select</span>(id, statusSource, text, created) %&gt;%
<span class="st">  </span><span class="kw">extract</span>(statusSource, <span class="st">&quot;source&quot;</span>, <span class="st">&quot;Twitter for (.*?)&lt;&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(source %in%<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;iPhone&quot;</span>, <span class="st">&quot;Android&quot;</span>))

tweets %&gt;%
<span class="st">  </span><span class="kw">head</span>() %&gt;%
<span class="st">  </span>knitr::<span class="kw">kable</span>(<span class="dt">caption =</span> <span class="st">&quot;Example of Donald Trump tweets&quot;</span>)</code></pre></div>
<table>
<caption>Example of Donald Trump tweets</caption>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">source</th>
<th align="left">text</th>
<th align="left">created</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">762669882571980801</td>
<td align="left">Android</td>
<td align="left">My economic policy speech will be carried live at 12:15 P.M. Enjoy!</td>
<td align="left">2016-08-08 15:20:44</td>
</tr>
<tr class="even">
<td align="left">762641595439190016</td>
<td align="left">iPhone</td>
<td align="left">Join me in Fayetteville, North Carolina tomorrow evening at 6pm. Tickets now available at: <a href="https://t.co/Z80d4MYIg8" class="uri">https://t.co/Z80d4MYIg8</a></td>
<td align="left">2016-08-08 13:28:20</td>
</tr>
<tr class="odd">
<td align="left">762439658911338496</td>
<td align="left">iPhone</td>
<td align="left">#ICYMI: “Will Media Apologize to Trump?” <a href="https://t.co/ia7rKBmioA" class="uri">https://t.co/ia7rKBmioA</a></td>
<td align="left">2016-08-08 00:05:54</td>
</tr>
<tr class="even">
<td align="left">762425371874557952</td>
<td align="left">Android</td>
<td align="left">Michael Morell, the lightweight former Acting Director of C.I.A., and a man who has made serious bad calls, is a total Clinton flunky!</td>
<td align="left">2016-08-07 23:09:08</td>
</tr>
<tr class="odd">
<td align="left">762400869858115588</td>
<td align="left">Android</td>
<td align="left">The media is going crazy. They totally distort so many things on purpose. Crimea, nuclear, “the baby” and so much more. Very dishonest!</td>
<td align="left">2016-08-07 21:31:46</td>
</tr>
<tr class="even">
<td align="left">762284533341417472</td>
<td align="left">Android</td>
<td align="left">I see where Mayor Stephanie Rawlings-Blake of Baltimore is pushing Crooked hard. Look at the job she has done in Baltimore. She is a joke!</td>
<td align="left">2016-08-07 13:49:29</td>
</tr>
</tbody>
</table>
</div>
<div id="comparison-using-metadata" class="section level2">
<h2>Comparison using metadata</h2>
<p>One consideration is what time of day the tweets occur, which we’d expect to be a “signature” of their user. Here we can certainly spot a difference:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweets %&gt;%
<span class="st">  </span><span class="kw">count</span>(source, <span class="dt">hour =</span> <span class="kw">hour</span>(<span class="kw">with_tz</span>(created, <span class="st">&quot;EST&quot;</span>))) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">percent =</span> n /<span class="st"> </span><span class="kw">sum</span>(n)) %&gt;%
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(hour, percent, <span class="dt">color =</span> source)) +
<span class="st">  </span><span class="kw">geom_line</span>() +
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="kw">percent_format</span>()) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Hour of day (EST)&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;% of tweets&quot;</span>,
       <span class="dt">color =</span> <span class="st">&quot;&quot;</span>)</code></pre></div>
<p><img src="text01_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Trump on the Android does a lot more tweeting in the morning, while the campaign posts from the iPhone more in the afternoon and early evening.</p>
<p>Another place we can spot a difference is in Trump’s anachronistic behavior of “manually retweeting” people by copy-pasting their tweets, then surrounding them with quotation marks:</p>
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
“<a href="https://twitter.com/trumplican2016">@trumplican2016</a>: <a href="https://twitter.com/realDonaldTrump">@realDonaldTrump</a> <a href="https://twitter.com/DavidWohl">@DavidWohl</a> stay the course mr trump your message is resonating with the PEOPLE”
</p>
— Donald J. Trump (@realDonaldTrump) <a href="https://twitter.com/realDonaldTrump/status/758512401629192192">July 28, 2016</a>
</blockquote>
<script async src="http://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>Almost all of these quoted tweets are posted from the Android:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweets %&gt;%
<span class="st">  </span><span class="kw">count</span>(source,
        <span class="dt">quoted =</span> <span class="kw">ifelse</span>(<span class="kw">str_detect</span>(text, <span class="st">&#39;^&quot;&#39;</span>), <span class="st">&quot;Quoted&quot;</span>, <span class="st">&quot;Not quoted&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(source, n, <span class="dt">fill =</span> quoted)) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Number of tweets&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;&quot;</span>) +
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Whether tweets start with a quotation mark (&quot;)&#39;</span>)</code></pre></div>
<p><img src="text01_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="comparison-of-words" class="section level2">
<h2>Comparison of words</h2>
<p>Now that we’re sure there’s a difference between these two accounts, what can we say about the difference in the <em>content</em>? We can use the <a href="https://cran.r-project.org/web/packages/tidytext"><code>tidytext</code></a> package to analyze this.</p>
<p>We start by dividing into individual words using the <code>unnest_tokens</code> function, and removing some common “stopwords”. This is a common aspect to preparing text for analysis. Typically, <em>tokens</em> are single words from a document. However they can also be <em>bi-grams</em> (pairs of words), <em>tri-grams</em> (three-word sequences), <em>n-grams</em> (<span class="math inline">\(n\)</span>-length sequences of words), or in this case, individual words, hashtags, or references to other Twitter users. Because tweets are a special form of text (they can include words, urls, references to other users, hashtags, etc.) we need to use a custom tokenizing function to convert the text into tokens.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidytext)

reg &lt;-<span class="st"> &quot;([^A-Za-z</span><span class="ch">\\</span><span class="st">d#@&#39;]|&#39;(?![A-Za-z</span><span class="ch">\\</span><span class="st">d#@]))&quot;</span>   <span class="co"># custom regular expression to tokenize tweets</span>

<span class="co"># function to neatly print the first 10 rows using kable</span>
print_neat &lt;-<span class="st"> </span>function(df){
  df %&gt;%
<span class="st">    </span><span class="kw">head</span>() %&gt;%
<span class="st">    </span>knitr::<span class="kw">kable</span>()
}

<span class="co"># tweets data frame</span>
tweets %&gt;%
<span class="st">  </span><span class="kw">print_neat</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">source</th>
<th align="left">text</th>
<th align="left">created</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">762669882571980801</td>
<td align="left">Android</td>
<td align="left">My economic policy speech will be carried live at 12:15 P.M. Enjoy!</td>
<td align="left">2016-08-08 15:20:44</td>
</tr>
<tr class="even">
<td align="left">762641595439190016</td>
<td align="left">iPhone</td>
<td align="left">Join me in Fayetteville, North Carolina tomorrow evening at 6pm. Tickets now available at: <a href="https://t.co/Z80d4MYIg8" class="uri">https://t.co/Z80d4MYIg8</a></td>
<td align="left">2016-08-08 13:28:20</td>
</tr>
<tr class="odd">
<td align="left">762439658911338496</td>
<td align="left">iPhone</td>
<td align="left">#ICYMI: “Will Media Apologize to Trump?” <a href="https://t.co/ia7rKBmioA" class="uri">https://t.co/ia7rKBmioA</a></td>
<td align="left">2016-08-08 00:05:54</td>
</tr>
<tr class="even">
<td align="left">762425371874557952</td>
<td align="left">Android</td>
<td align="left">Michael Morell, the lightweight former Acting Director of C.I.A., and a man who has made serious bad calls, is a total Clinton flunky!</td>
<td align="left">2016-08-07 23:09:08</td>
</tr>
<tr class="odd">
<td align="left">762400869858115588</td>
<td align="left">Android</td>
<td align="left">The media is going crazy. They totally distort so many things on purpose. Crimea, nuclear, “the baby” and so much more. Very dishonest!</td>
<td align="left">2016-08-07 21:31:46</td>
</tr>
<tr class="even">
<td align="left">762284533341417472</td>
<td align="left">Android</td>
<td align="left">I see where Mayor Stephanie Rawlings-Blake of Baltimore is pushing Crooked hard. Look at the job she has done in Baltimore. She is a joke!</td>
<td align="left">2016-08-07 13:49:29</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># remove manual retweets</span>
tweets %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">str_detect</span>(text, <span class="st">&#39;^&quot;&#39;</span>)) %&gt;%
<span class="st">  </span><span class="kw">print_neat</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">source</th>
<th align="left">text</th>
<th align="left">created</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">762669882571980801</td>
<td align="left">Android</td>
<td align="left">My economic policy speech will be carried live at 12:15 P.M. Enjoy!</td>
<td align="left">2016-08-08 15:20:44</td>
</tr>
<tr class="even">
<td align="left">762641595439190016</td>
<td align="left">iPhone</td>
<td align="left">Join me in Fayetteville, North Carolina tomorrow evening at 6pm. Tickets now available at: <a href="https://t.co/Z80d4MYIg8" class="uri">https://t.co/Z80d4MYIg8</a></td>
<td align="left">2016-08-08 13:28:20</td>
</tr>
<tr class="odd">
<td align="left">762439658911338496</td>
<td align="left">iPhone</td>
<td align="left">#ICYMI: “Will Media Apologize to Trump?” <a href="https://t.co/ia7rKBmioA" class="uri">https://t.co/ia7rKBmioA</a></td>
<td align="left">2016-08-08 00:05:54</td>
</tr>
<tr class="even">
<td align="left">762425371874557952</td>
<td align="left">Android</td>
<td align="left">Michael Morell, the lightweight former Acting Director of C.I.A., and a man who has made serious bad calls, is a total Clinton flunky!</td>
<td align="left">2016-08-07 23:09:08</td>
</tr>
<tr class="odd">
<td align="left">762400869858115588</td>
<td align="left">Android</td>
<td align="left">The media is going crazy. They totally distort so many things on purpose. Crimea, nuclear, “the baby” and so much more. Very dishonest!</td>
<td align="left">2016-08-07 21:31:46</td>
</tr>
<tr class="even">
<td align="left">762284533341417472</td>
<td align="left">Android</td>
<td align="left">I see where Mayor Stephanie Rawlings-Blake of Baltimore is pushing Crooked hard. Look at the job she has done in Baltimore. She is a joke!</td>
<td align="left">2016-08-07 13:49:29</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># remove urls</span>
tweets %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">str_detect</span>(text, <span class="st">&#39;^&quot;&#39;</span>)) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;https://t.co/[A-Za-z</span><span class="ch">\\</span><span class="st">d]+|&amp;amp;&quot;</span>, <span class="st">&quot;&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">print_neat</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">source</th>
<th align="left">text</th>
<th align="left">created</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">762669882571980801</td>
<td align="left">Android</td>
<td align="left">My economic policy speech will be carried live at 12:15 P.M. Enjoy!</td>
<td align="left">2016-08-08 15:20:44</td>
</tr>
<tr class="even">
<td align="left">762641595439190016</td>
<td align="left">iPhone</td>
<td align="left">Join me in Fayetteville, North Carolina tomorrow evening at 6pm. Tickets now available at:</td>
<td align="left">2016-08-08 13:28:20</td>
</tr>
<tr class="odd">
<td align="left">762439658911338496</td>
<td align="left">iPhone</td>
<td align="left">#ICYMI: “Will Media Apologize to Trump?”</td>
<td align="left">2016-08-08 00:05:54</td>
</tr>
<tr class="even">
<td align="left">762425371874557952</td>
<td align="left">Android</td>
<td align="left">Michael Morell, the lightweight former Acting Director of C.I.A., and a man who has made serious bad calls, is a total Clinton flunky!</td>
<td align="left">2016-08-07 23:09:08</td>
</tr>
<tr class="odd">
<td align="left">762400869858115588</td>
<td align="left">Android</td>
<td align="left">The media is going crazy. They totally distort so many things on purpose. Crimea, nuclear, “the baby” and so much more. Very dishonest!</td>
<td align="left">2016-08-07 21:31:46</td>
</tr>
<tr class="even">
<td align="left">762284533341417472</td>
<td align="left">Android</td>
<td align="left">I see where Mayor Stephanie Rawlings-Blake of Baltimore is pushing Crooked hard. Look at the job she has done in Baltimore. She is a joke!</td>
<td align="left">2016-08-07 13:49:29</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># unnest into tokens - tidytext format</span>
tweets %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">str_detect</span>(text, <span class="st">&#39;^&quot;&#39;</span>)) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;https://t.co/[A-Za-z</span><span class="ch">\\</span><span class="st">d]+|&amp;amp;&quot;</span>, <span class="st">&quot;&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text, <span class="dt">token =</span> <span class="st">&quot;regex&quot;</span>, <span class="dt">pattern =</span> reg) %&gt;%
<span class="st">  </span><span class="kw">print_neat</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">source</th>
<th align="left">created</th>
<th align="left">word</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">record</td>
</tr>
<tr class="even">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">of</td>
</tr>
<tr class="odd">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">health</td>
</tr>
<tr class="even">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">#makeamericagreatagain</td>
</tr>
<tr class="odd">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">#trump2016</td>
</tr>
<tr class="even">
<td align="left">676509769562251264</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 21:11:12</td>
<td align="left">another</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># remove stop words</span>
tweets %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">str_detect</span>(text, <span class="st">&#39;^&quot;&#39;</span>)) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;https://t.co/[A-Za-z</span><span class="ch">\\</span><span class="st">d]+|&amp;amp;&quot;</span>, <span class="st">&quot;&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text, <span class="dt">token =</span> <span class="st">&quot;regex&quot;</span>, <span class="dt">pattern =</span> reg) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!word %in%<span class="st"> </span>stop_words$word,
         <span class="kw">str_detect</span>(word, <span class="st">&quot;[a-z]&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">print_neat</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">source</th>
<th align="left">created</th>
<th align="left">word</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">record</td>
</tr>
<tr class="even">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">health</td>
</tr>
<tr class="odd">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">#makeamericagreatagain</td>
</tr>
<tr class="even">
<td align="left">676494179216805888</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 20:09:15</td>
<td align="left">#trump2016</td>
</tr>
<tr class="odd">
<td align="left">676509769562251264</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 21:11:12</td>
<td align="left">accolade</td>
</tr>
<tr class="even">
<td align="left">676509769562251264</td>
<td align="left">iPhone</td>
<td align="left">2015-12-14 21:11:12</td>
<td align="left"><span class="citation">@trumpgolf</span></td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># store for future use</span>
tweet_words &lt;-<span class="st"> </span>tweets %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">str_detect</span>(text, <span class="st">&#39;^&quot;&#39;</span>)) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;https://t.co/[A-Za-z</span><span class="ch">\\</span><span class="st">d]+|&amp;amp;&quot;</span>, <span class="st">&quot;&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text, <span class="dt">token =</span> <span class="st">&quot;regex&quot;</span>, <span class="dt">pattern =</span> reg) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!word %in%<span class="st"> </span>stop_words$word,
         <span class="kw">str_detect</span>(word, <span class="st">&quot;[a-z]&quot;</span>))</code></pre></div>
<p>What were the most common words in Trump’s tweets overall?</p>
<p><img src="text01_files/figure-html/tweet_words_plot-1.png" width="768" /></p>
<p>Yeah, sounds about right.</p>
<div id="assessing-word-and-document-frequency" class="section level3">
<h3>Assessing word and document frequency</h3>
<p>One measure of how important a word may be is its <em>term frequency</em> (tf), how frequently a word occurs within a document. The problem with this approach is that some words occur many times in a document, yet are probably not important (e.g. “the”, “is”, “of”). Instead, we want a way of downweighting words that are common across all documents, and upweighting words that are frequent within a small set of documents.</p>
<p>Another approach is to look at a term’s <em>inverse document frequency</em> (idf), which decreases the weight for commonly used words and increases the weight for words that are not used very much in a collection of documents. This can be combined with term frequency to calculate a term’s <em>tf-idf</em>, the frequency of a term adjusted for how rarely it is used. It is intended to measure how important a word is to a document in a collection (or corpus) of documents. It is a rule-of-thumb or heuristic quantity, not a theoretically proven method. The inverse document frequency for any given term is defined as</p>
<p><span class="math display">\[idf(\text{term}) = \ln{\left(\frac{n_{\text{documents}}}{n_{\text{documents containing term}}}\right)}\]</span></p>
<p>To calculate <em>tf-idf</em> for this set of documents, we will pool all the tweets from iPhone and Android together and treat them as if they are two total documents. Then we can calculate the frequency of terms in each group, and standardize that relative to the the term’s frequency across the entire corpus.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweet_words_count &lt;-<span class="st"> </span>tweet_words %&gt;%
<span class="st">  </span><span class="kw">count</span>(source, word, <span class="dt">sort =</span> <span class="ot">TRUE</span>) %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>()
tweet_words_count</code></pre></div>
<pre><code>## # A tibble: 3,235 × 3
##     source                   word     n
##      &lt;chr&gt;                  &lt;chr&gt; &lt;int&gt;
## 1   iPhone             #trump2016   171
## 2  Android                hillary   124
## 3   iPhone #makeamericagreatagain    95
## 4  Android                crooked    93
## 5  Android                clinton    66
## 6  Android                 people    64
## 7   iPhone                hillary    52
## 8  Android                   cruz    50
## 9  Android                    bad    43
## 10  iPhone                america    43
## # ... with 3,225 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">total_words &lt;-<span class="st"> </span>tweet_words_count %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(source) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">total =</span> <span class="kw">sum</span>(n))
total_words</code></pre></div>
<pre><code>## # A tibble: 2 × 2
##    source total
##     &lt;chr&gt; &lt;int&gt;
## 1 Android  4901
## 2  iPhone  3852</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweet_words_count &lt;-<span class="st"> </span><span class="kw">left_join</span>(tweet_words_count, total_words)</code></pre></div>
<pre><code>## Joining, by = &quot;source&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweet_words_count</code></pre></div>
<pre><code>## # A tibble: 3,235 × 4
##     source                   word     n total
##      &lt;chr&gt;                  &lt;chr&gt; &lt;int&gt; &lt;int&gt;
## 1   iPhone             #trump2016   171  3852
## 2  Android                hillary   124  4901
## 3   iPhone #makeamericagreatagain    95  3852
## 4  Android                crooked    93  4901
## 5  Android                clinton    66  4901
## 6  Android                 people    64  4901
## 7   iPhone                hillary    52  3852
## 8  Android                   cruz    50  4901
## 9  Android                    bad    43  4901
## 10  iPhone                america    43  3852
## # ... with 3,225 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweet_words_count &lt;-<span class="st"> </span>tweet_words_count %&gt;%
<span class="st">  </span><span class="kw">bind_tf_idf</span>(word, source, n)
tweet_words_count</code></pre></div>
<pre><code>## # A tibble: 3,235 × 7
##     source                   word     n total         tf       idf
##      &lt;chr&gt;                  &lt;chr&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1   iPhone             #trump2016   171  3852 0.04439252 0.0000000
## 2  Android                hillary   124  4901 0.02530096 0.0000000
## 3   iPhone #makeamericagreatagain    95  3852 0.02466251 0.6931472
## 4  Android                crooked    93  4901 0.01897572 0.0000000
## 5  Android                clinton    66  4901 0.01346664 0.0000000
## 6  Android                 people    64  4901 0.01305856 0.0000000
## 7   iPhone                hillary    52  3852 0.01349948 0.0000000
## 8  Android                   cruz    50  4901 0.01020200 0.0000000
## 9  Android                    bad    43  4901 0.00877372 0.0000000
## 10  iPhone                america    43  3852 0.01116303 0.0000000
## # ... with 3,225 more rows, and 1 more variables: tf_idf &lt;dbl&gt;</code></pre>
<p>Which terms have a high tf-idf?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweet_words_count %&gt;%
<span class="st">  </span><span class="kw">select</span>(-total) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(tf_idf))</code></pre></div>
<pre><code>## # A tibble: 3,235 × 6
##     source                   word     n          tf       idf      tf_idf
##      &lt;chr&gt;                  &lt;chr&gt; &lt;int&gt;       &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1   iPhone #makeamericagreatagain    95 0.024662513 0.6931472 0.017094751
## 2   iPhone                   join    42 0.010903427 0.6931472 0.007557680
## 3   iPhone          #americafirst    27 0.007009346 0.6931472 0.004858508
## 4   iPhone             #votetrump    23 0.005970924 0.6931472 0.004138729
## 5   iPhone             #imwithyou    20 0.005192108 0.6931472 0.003598895
## 6   iPhone        #crookedhillary    17 0.004413292 0.6931472 0.003059061
## 7   iPhone          #trumppence16    14 0.003634476 0.6931472 0.002519227
## 8   iPhone                    7pm    11 0.002855659 0.6931472 0.001979392
## 9   iPhone                  video    11 0.002855659 0.6931472 0.001979392
## 10 Android                  badly    13 0.002652520 0.6931472 0.001838587
## # ... with 3,225 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweet_important &lt;-<span class="st"> </span>tweet_words_count %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(tf_idf)) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">word =</span> <span class="kw">factor</span>(word, <span class="dt">levels =</span> <span class="kw">rev</span>(<span class="kw">unique</span>(word))))

tweet_important %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(source) %&gt;%
<span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span>:<span class="dv">15</span>) %&gt;%
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(word, tf_idf, <span class="dt">fill =</span> source)) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">alpha =</span> <span class="fl">0.8</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Highest tf-idf words in @realDonaldTrump&quot;</span>,
       <span class="dt">subtitle =</span> <span class="st">&quot;Top 15 for Android and iPhone&quot;</span>,
       <span class="dt">x =</span> <span class="ot">NULL</span>, <span class="dt">y =</span> <span class="st">&quot;tf-idf&quot;</span>) +
<span class="st">  </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="text01_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<ul>
<li><p><strong>Most hashtags come from the iPhone</strong>. Indeed, almost no tweets from Trump’s Android contained hashtags, with some rare exceptions like <a href="https://twitter.com/realDonaldTrump/status/753960134422900736">this one</a>. (This is true only because we filtered out the quoted “retweets”, as Trump does sometimes quote tweets <a href="https://twitter.com/realDonaldTrump/status/731805331425218560">like this</a> that contain hashtags).</p></li>
<li><p><strong>Words like “join”, and times like “7pm”, also came only from the iPhone</strong>. The iPhone is clearly responsible for event announcements like <a href="https://twitter.com/realDonaldTrump/status/743522630230228993">this one</a> (“Join me in Houston, Texas tomorrow night at 7pm!”)</p></li>
<li><p><strong>A lot of “emotionally charged” words, like “badly” and “dumb”, were overwhelmingly more common on Android.</strong> This supports the original hypothesis that this is the “angrier” or more hyperbolic account.</p></li>
</ul>
</div>
<div id="sentiment-analysis-1" class="section level3">
<h3>Sentiment analysis</h3>
<p>Since we’ve observed a difference in sentiment between the Android and iPhone tweets, let’s try quantifying it. We’ll work with the <a href="http://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm">NRC Word-Emotion Association</a> lexicon, available from the <code>tidytext</code> package, which associates words with 10 sentiments: <strong>positive</strong>, <strong>negative</strong>, <strong>anger</strong>, <strong>anticipation</strong>, <strong>disgust</strong>, <strong>fear</strong>, <strong>joy</strong>, <strong>sadness</strong>, <strong>surprise</strong>, and <strong>trust</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nrc &lt;-<span class="st"> </span>sentiments %&gt;%
<span class="st">  </span><span class="kw">filter</span>(lexicon ==<span class="st"> &quot;nrc&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">select</span>(word, sentiment)
nrc</code></pre></div>
<pre><code>## # A tibble: 13,901 × 2
##           word sentiment
##          &lt;chr&gt;     &lt;chr&gt;
## 1       abacus     trust
## 2      abandon      fear
## 3      abandon  negative
## 4      abandon   sadness
## 5    abandoned     anger
## 6    abandoned      fear
## 7    abandoned  negative
## 8    abandoned   sadness
## 9  abandonment     anger
## 10 abandonment      fear
## # ... with 13,891 more rows</code></pre>
<p>To measure the sentiment of the Android and iPhone tweets, we can count the number of words in each category:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sources &lt;-<span class="st"> </span>tweet_words %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(source) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total_words =</span> <span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>() %&gt;%
<span class="st">  </span><span class="kw">distinct</span>(id, source, total_words)
sources</code></pre></div>
<pre><code>## # A tibble: 1,172 × 3
##                    id  source total_words
##                 &lt;chr&gt;   &lt;chr&gt;       &lt;int&gt;
## 1  676494179216805888  iPhone        3852
## 2  676509769562251264  iPhone        3852
## 3  680496083072593920 Android        4901
## 4  680503951440121856 Android        4901
## 5  680505672476262400 Android        4901
## 6  680734915718176768 Android        4901
## 7  682764544402440192  iPhone        3852
## 8  682792967736848385  iPhone        3852
## 9  682805320217980929  iPhone        3852
## 10 685490467329425408 Android        4901
## # ... with 1,162 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">by_source_sentiment &lt;-<span class="st"> </span>tweet_words %&gt;%
<span class="st">  </span><span class="kw">inner_join</span>(nrc, <span class="dt">by =</span> <span class="st">&quot;word&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">count</span>(sentiment, id) %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>() %&gt;%
<span class="st">  </span><span class="kw">complete</span>(sentiment, id, <span class="dt">fill =</span> <span class="kw">list</span>(<span class="dt">n =</span> <span class="dv">0</span>)) %&gt;%
<span class="st">  </span><span class="kw">inner_join</span>(sources) %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(source, sentiment, total_words) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">words =</span> <span class="kw">sum</span>(n)) %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>()</code></pre></div>
<pre><code>## Joining, by = &quot;id&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(by_source_sentiment)</code></pre></div>
<pre><code>## # A tibble: 6 × 4
##    source    sentiment total_words words
##     &lt;chr&gt;        &lt;chr&gt;       &lt;int&gt; &lt;dbl&gt;
## 1 Android        anger        4901   321
## 2 Android anticipation        4901   256
## 3 Android      disgust        4901   207
## 4 Android         fear        4901   268
## 5 Android          joy        4901   199
## 6 Android     negative        4901   560</code></pre>
<p>(For example, we see that 321 of the 4901 words in the Android tweets were associated with “anger”). We then want to measure how much more likely the Android account is to use an emotionally-charged term relative to the iPhone account. Since this is count data, we can use a <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/poisson.test.html">Poisson test</a> to measure the difference:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># function to calculate the poisson.test for a given sentiment</span>
poisson_test &lt;-<span class="st"> </span>function(df){
  <span class="kw">poisson.test</span>(df$words, df$total_words)
}

<span class="co"># use the nest() and map() functions to apply poisson_test to each sentiment and </span>
<span class="co"># extract results using broom::tidy()</span>
sentiment_differences &lt;-<span class="st"> </span>by_source_sentiment %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(sentiment) %&gt;%
<span class="st">  </span><span class="kw">nest</span>() %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">poisson =</span> <span class="kw">map</span>(data, poisson_test),
         <span class="dt">poisson_tidy =</span> <span class="kw">map</span>(poisson, tidy)) %&gt;%
<span class="st">  </span><span class="kw">unnest</span>(poisson_tidy, <span class="dt">.drop =</span> <span class="ot">TRUE</span>)
sentiment_differences</code></pre></div>
<pre><code>## # A tibble: 10 × 9
##       sentiment estimate statistic      p.value parameter  conf.low
##           &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1         anger 1.492863       321 2.193242e-05  274.3619 1.2353162
## 2  anticipation 1.169804       256 1.191668e-01  239.6467 0.9604950
## 3       disgust 1.677259       207 1.777434e-05  170.2164 1.3116238
## 4          fear 1.560280       268 1.886129e-05  225.6487 1.2640494
## 5           joy 1.002605       199 1.000000e+00  198.7724 0.8089357
## 6      negative 1.692841       560 7.094486e-13  459.1363 1.4586926
## 7      positive 1.058760       555 3.820571e-01  541.4449 0.9303732
## 8       sadness 1.620044       303 1.150493e-06  251.9650 1.3260252
## 9      surprise 1.167925       159 2.174483e-01  148.9393 0.9083517
## 10        trust 1.128482       369 1.471929e-01  350.5114 0.9597478
## # ... with 3 more variables: conf.high &lt;dbl&gt;, method &lt;fctr&gt;,
## #   alternative &lt;fctr&gt;</code></pre>
<p>And we can visualize it with a 95% confidence interval:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sentiment_differences %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>() %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> <span class="kw">reorder</span>(sentiment, estimate)) %&gt;%
<span class="st">  </span><span class="kw">mutate_each</span>(<span class="kw">funs</span>(. -<span class="st"> </span><span class="dv">1</span>), estimate, conf.low, conf.high) %&gt;%
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(estimate, sentiment)) +
<span class="st">  </span><span class="kw">geom_point</span>() +
<span class="st">  </span><span class="kw">geom_errorbarh</span>(<span class="kw">aes</span>(<span class="dt">xmin =</span> conf.low, <span class="dt">xmax =</span> conf.high)) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">labels =</span> <span class="kw">percent_format</span>()) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;% increase in Android relative to iPhone&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;Sentiment&quot;</span>)</code></pre></div>
<p><img src="text01_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Thus, Trump’s Android account uses about 40-80% more words related to <strong>disgust</strong>, <strong>sadness</strong>, <strong>fear</strong>, <strong>anger</strong>, and other “negative” sentiments than the iPhone account does. (The positive emotions weren’t different to a statistically significant extent).</p>
<p>We’re especially interested in which words drove this different in sentiment. Let’s consider the words with the largest changes within each category:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tweet_important %&gt;%
<span class="st">  </span><span class="kw">inner_join</span>(nrc, <span class="dt">by =</span> <span class="st">&quot;word&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!sentiment %in%<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;positive&quot;</span>, <span class="st">&quot;negative&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> <span class="kw">reorder</span>(sentiment, -tf_idf),
         <span class="dt">word =</span> <span class="kw">reorder</span>(word, -tf_idf)) %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(sentiment) %&gt;%
<span class="st">  </span><span class="kw">top_n</span>(<span class="dv">10</span>, tf_idf) %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>() %&gt;%
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(word, tf_idf, <span class="dt">fill =</span> source)) +
<span class="st">  </span><span class="kw">facet_wrap</span>(~<span class="st"> </span>sentiment, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">nrow =</span> <span class="dv">4</span>) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>,
       <span class="dt">y =</span> <span class="st">&quot;tf-idf&quot;</span>) +
<span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">name =</span> <span class="st">&quot;&quot;</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Android&quot;</span>, <span class="st">&quot;iPhone&quot;</span>),
                    <span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;lightblue&quot;</span>))</code></pre></div>
<pre><code>## Warning in inner_join_impl(x, y, by$x, by$y, suffix$x, suffix$y): joining
## factor and character vector, coercing into character vector</code></pre>
<p><img src="text01_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>This confirms that lots of words annotated as negative sentiments are more common in Trump’s Android tweets than the campaign’s iPhone tweets. It’s no wonder <a href="http://www.nytimes.com/2016/11/07/us/politics/donald-trump-presidential-race.html">Trump’s staff took away his tweeting privileges for the remainder of the campaign</a>.</p>
</div>
</div>
</div>
<div id="acknowledgments" class="section level1 toc-ignore">
<h1>Acknowledgments</h1>
<ul>
<li>This page is derived in part from <a href="http://stat545.com">“UBC STAT 545A and 547M”</a>, licensed under the <a href="https://creativecommons.org/licenses/by-nc/3.0/">CC BY-NC 3.0 Creative Commons License</a>.</li>
<li>This page is derived in part from <a href="http://varianceexplained.org/r/trump-tweets/">“Text analysis of Trump’s tweets confirms he writes only the (angrier) Android half”</a> and licensed under a <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.</li>
<li>This page is derived in part from <a href="http://tidytextmining.com/">“Tidy Text Mining with R”</a> and licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/us/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 United States License</a>.</li>
</ul>
</div>
<div id="session-info" class="section level1 toc-ignore">
<h1>Session Info</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">devtools::<span class="kw">session_info</span>()</code></pre></div>
<pre><code>## Session info --------------------------------------------------------------</code></pre>
<pre><code>##  setting  value                       
##  version  R version 3.3.1 (2016-06-21)
##  system   x86_64, darwin13.4.0        
##  ui       RStudio (1.0.44)            
##  language (EN)                        
##  collate  en_US.UTF-8                 
##  tz       America/Chicago             
##  date     2016-11-16</code></pre>
<pre><code>## Packages ------------------------------------------------------------------</code></pre>
<pre><code>##  package      * version date       source                           
##  assertthat     0.1     2013-12-06 CRAN (R 3.3.0)                   
##  bit            1.1-12  2014-04-09 CRAN (R 3.3.0)                   
##  bit64          0.9-5   2015-07-05 CRAN (R 3.3.0)                   
##  boot         * 1.3-18  2016-02-23 CRAN (R 3.3.1)                   
##  broom        * 0.4.1   2016-06-24 CRAN (R 3.3.0)                   
##  car            2.1-3   2016-08-11 CRAN (R 3.3.0)                   
##  caret        * 6.0-73  2016-11-10 CRAN (R 3.3.2)                   
##  class          7.3-14  2015-08-30 CRAN (R 3.3.1)                   
##  codetools      0.2-15  2016-10-05 CRAN (R 3.3.0)                   
##  colorspace     1.2-7   2016-10-11 CRAN (R 3.3.0)                   
##  DBI            0.5-1   2016-09-10 CRAN (R 3.3.0)                   
##  devtools       1.12.0  2016-06-24 CRAN (R 3.3.0)                   
##  digest         0.6.10  2016-08-02 CRAN (R 3.3.0)                   
##  dplyr        * 0.5.0   2016-06-24 CRAN (R 3.3.0)                   
##  e1071          1.6-7   2015-08-05 CRAN (R 3.3.0)                   
##  evaluate       0.10    2016-10-11 CRAN (R 3.3.0)                   
##  foreach        1.4.3   2015-10-13 CRAN (R 3.3.0)                   
##  foreign        0.8-67  2016-09-13 CRAN (R 3.3.0)                   
##  formatR        1.4     2016-05-09 CRAN (R 3.3.0)                   
##  gapminder    * 0.2.0   2015-12-31 CRAN (R 3.3.0)                   
##  gganimate    * 0.1     2016-11-11 Github (dgrtwo/gganimate@26ec501)
##  ggplot2      * 2.2.0   2016-11-10 Github (hadley/ggplot2@f442f32)  
##  gtable         0.2.0   2016-02-26 CRAN (R 3.3.0)                   
##  highr          0.6     2016-05-09 CRAN (R 3.3.0)                   
##  htmltools      0.3.5   2016-03-21 CRAN (R 3.3.0)                   
##  htmlwidgets    0.8     2016-11-09 CRAN (R 3.3.1)                   
##  httr           1.2.1   2016-07-03 CRAN (R 3.3.0)                   
##  ISLR         * 1.0     2013-06-11 CRAN (R 3.3.0)                   
##  iterators      1.0.8   2015-10-13 CRAN (R 3.3.0)                   
##  janeaustenr  * 0.1.4   2016-10-26 CRAN (R 3.3.0)                   
##  jsonlite       1.1     2016-09-14 CRAN (R 3.3.0)                   
##  knitr          1.15    2016-11-09 CRAN (R 3.3.1)                   
##  labeling       0.3     2014-08-23 CRAN (R 3.3.0)                   
##  lattice      * 0.20-34 2016-09-06 CRAN (R 3.3.0)                   
##  lazyeval       0.2.0   2016-06-12 CRAN (R 3.3.0)                   
##  lme4           1.1-12  2016-04-16 cran (@1.1-12)                   
##  lubridate    * 1.6.0   2016-09-13 CRAN (R 3.3.0)                   
##  magrittr       1.5     2014-11-22 CRAN (R 3.3.0)                   
##  MASS           7.3-45  2016-04-21 CRAN (R 3.3.1)                   
##  Matrix         1.2-7.1 2016-09-01 CRAN (R 3.3.0)                   
##  MatrixModels   0.4-1   2015-08-22 CRAN (R 3.3.0)                   
##  memoise        1.0.0   2016-01-29 CRAN (R 3.3.0)                   
##  mgcv           1.8-16  2016-11-07 CRAN (R 3.3.0)                   
##  minqa          1.2.4   2014-10-09 cran (@1.2.4)                    
##  mnormt         1.5-5   2016-10-15 CRAN (R 3.3.0)                   
##  ModelMetrics   1.1.0   2016-08-26 CRAN (R 3.3.0)                   
##  modelr       * 0.1.0   2016-08-31 CRAN (R 3.3.0)                   
##  munsell        0.4.3   2016-02-13 CRAN (R 3.3.0)                   
##  nlme           3.1-128 2016-05-10 CRAN (R 3.3.1)                   
##  nloptr         1.0.4   2014-08-04 cran (@1.0.4)                    
##  nnet           7.3-12  2016-02-02 CRAN (R 3.3.1)                   
##  pbkrtest       0.4-6   2016-01-27 CRAN (R 3.3.0)                   
##  plyr           1.8.4   2016-06-08 CRAN (R 3.3.0)                   
##  profvis      * 0.3.2   2016-05-19 CRAN (R 3.3.0)                   
##  psych          1.6.9   2016-09-17 cran (@1.6.9)                    
##  purrr        * 0.2.2   2016-06-18 CRAN (R 3.3.0)                   
##  quantreg       5.29    2016-09-04 CRAN (R 3.3.0)                   
##  R6             2.2.0   2016-10-05 CRAN (R 3.3.0)                   
##  randomForest * 4.6-12  2015-10-07 CRAN (R 3.3.0)                   
##  rcfss        * 0.1.0   2016-10-06 local                            
##  Rcpp           0.12.7  2016-09-05 cran (@0.12.7)                   
##  readr        * 1.0.0   2016-08-03 CRAN (R 3.3.0)                   
##  readxl       * 0.1.1   2016-03-28 CRAN (R 3.3.0)                   
##  reshape2       1.4.2   2016-10-22 CRAN (R 3.3.0)                   
##  rjson          0.2.15  2014-11-03 cran (@0.2.15)                   
##  rmarkdown    * 1.1     2016-10-16 CRAN (R 3.3.1)                   
##  rsconnect      0.5     2016-10-17 CRAN (R 3.3.0)                   
##  rstudioapi     0.6     2016-06-27 CRAN (R 3.3.0)                   
##  scales       * 0.4.1   2016-11-09 CRAN (R 3.3.1)                   
##  SnowballC      0.5.1   2014-08-09 cran (@0.5.1)                    
##  SparseM        1.72    2016-09-06 CRAN (R 3.3.0)                   
##  stringi        1.1.2   2016-10-01 CRAN (R 3.3.0)                   
##  stringr      * 1.1.0   2016-08-19 cran (@1.1.0)                    
##  tibble       * 1.2     2016-08-26 cran (@1.2)                      
##  tidyr        * 0.6.0   2016-08-12 CRAN (R 3.3.0)                   
##  tidytext     * 0.1.2   2016-10-28 CRAN (R 3.3.0)                   
##  tidyverse    * 1.0.0   2016-09-09 CRAN (R 3.3.0)                   
##  tokenizers     0.1.4   2016-08-29 CRAN (R 3.3.0)                   
##  tree         * 1.0-37  2016-01-21 CRAN (R 3.3.0)                   
##  twitteR      * 1.1.9   2015-07-29 CRAN (R 3.3.0)                   
##  withr          1.0.2   2016-06-20 CRAN (R 3.3.0)                   
##  yaml           2.1.13  2014-06-12 CRAN (R 3.3.0)</code></pre>
</div>

<p>This work is licensed under the  <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 Creative Commons License</a>.</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
