---
title: "Data transformation"
date: 2021-01-19T09:40:00-06:00
publishDate: 2019-04-08T09:40:00-06:00
draft: false

aliases: ["/cm003.html"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
time_end: 2021-01-19T11:00:00-06:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Computational problem-solving, verbs for data manipulation, and practice transforming data frames using dplyr."

# Location of event.
location: "Online"

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: "/slides/data-transformation/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Identify computer programming as a form of problem solving
* Practice decomposing an analytical goal into a set of discrete, computational tasks
* Identify the verbs for a language of data manipulation
* Clarify confusing aspects of data transformation from [R for Data Science](http://r4ds.had.co.nz/transform.html)
* Practice transforming data

## Before class

* Read Chapters 5-6 from [R for Data Science](http://r4ds.had.co.nz/)

## Class materials

* [Computer programming as a form of problem solving](/notes/problem-solving/)
* [`dplyr` in brief](/notes/dplyr/)
* [Practice transforming college education (data)](/notes/transform-college/)

## Additional resources

* [Data Wrangling with `dplyr` and `tidyr` Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

## What you need to do after class

* [Register your GitHub username for the course](https://forms.gle/XZ8XRBecWNKKwBme6) - all homework assignments will be in **private repositories**. Private repos can only be seen and edited by members of our [course organization](https://github.com/cfss-win21). Once you register your GitHub account, I will invite you to join the course organization. If you don't register your account, you won't have access to any of the homework assignments.
* Complete your peer evaluations for homework 01. Review the following:
    * [General Homework Rubric](/faq/homework-evaluations/)
    * [Performing peer review](/faq/peer-evaluations/)
    * To find which peers you will evaluate:
        * Navigate to the [pull request page for `hw01`](https://github.com/cfss-win21/hw01/pulls)
        * Click **Reviews** > **Awaiting review from you**
        * If you submitted your pull request on-time, you were randomly assigned two other pull requests to evaluate. If you did not submit your pull request on-time, you are still expected to perform two peer evaluations. Select any two pull requests and provide feedback on their submission.
