---
title: "Text analysis: classification and topic modeling"
date: 2022-11-21T12:25:00-05:00
publishDate: 2019-06-01T12:25:00-05:00
draft: false

aliases: ["/cm018.html"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
time_end: 2022-11-21T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Implement supervised and unsupervised learning methods for text data."

# Location of event.
location: "Hollister Hall 162"

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: "/slides/text-analysis-classification-and-topic-modeling/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Introduce supervised text classification
* Implement a `tidymodels` workflow using text features
* Define topic modeling
* Explain Latent Dirichlet allocation and how this process works
* Demonstrate how to use LDA to recover topic structure from an unknown set of topics
* Identify methods for selecting the appropriate parameter for $k$

## Before class

- Read [Supervised classification with text data](/notes/supervised-text-classification/)
    - For greater depth of coverage, read [Classification](https://smltar.com/mlclassification.html) in *Supervised Machine Learning for Text Analysis in R*
- Read chapter 6 in [*Tidy Text Mining with R*](http://tidytextmining.com/)
    - [Topic modeling](/notes/topic-modeling/) from the lecture notes demonstrates how to implement this in a (semi)-tidy workflow

## Class materials

- [Predicting song artist from lyrics](/notes/predicting-song-artist/)
* [Text analysis: topic modeling](/notes/topic-modeling/)

## What you need to do after class

* [Complete the text analysis homework](/homework/text-analysis/)
