---
title: "Data wrangling: relational data and factors"
date: 2022-09-12T12:25:00-05:00
publishDate: 2019-04-17T12:25:00-05:00
draft: false

aliases: ["/cm006.html"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
time_end: 2022-09-12T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Introduce relational data structures, and practice working with factor columns."

# Location of event.
location: "Hollister Hall 162"

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: "/slides/data-wrangling-relational-data-and-factors/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Introduce relational data
* Demonstrate how tables can be linked to one another
* Demonstrate methods in `dplyr` for linking and merging related tables
* Practice joining tables
* Define factors
* Demonstrate how to transform and reorder factors for visualizations
* Practice transforming factors

## Before class

* Read Chapters 13, 15 from [R for Data Science](http://r4ds.had.co.nz/)
    * Do not complete exercises 13.4.6.2-3 -- we will be completing these as in-class exercises

## Class materials

* [Relational data: a quick review](/notes/relational-data/)
* [Practice using relational data](/notes/relational-data-exercise/)
* [Practice transforming and visualizing factors](/notes/factors-exercise/)

## What you need to do after class

* [Complete the wrangling and visualizing data homework](/homework/wrangle-data/)
