---
title: "Data transformation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# cm003 - October 8, 2018

## Overview

* Identify computer programming as a form of problem solving
* Practice decomposing an analytical goal into a set of discrete, computational tasks
* Identify the verbs for a language of data manipulation
* Clarify confusing aspects of data transformation from [R for Data Science](http://r4ds.had.co.nz/transform.html)
* Practice transforming data

## Before class

* Read Chapters 5-6 from [R for Data Science](http://r4ds.had.co.nz/)

## Slides and class materials

* [Slides](extras/cm003_slides.html)
* [Computer programming as a form of problem solving](datawrangle_problem_solve.html)
* [`dplyr` in brief](datawrangle_dplyr.html)
* [Practice transforming college education (data)](datawrangle_transform_college.html)

## Additional resources

* [Data Wrangling with `dplyr` and `tidyr` Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

## What you need to do

* [Register your GitHub username for the course](https://goo.gl/forms/96MlxifdxxNJxuHt2) - all remaining homework assignments will be in **private repositories**. Private repos can only be seen and edited by members of our [course organization](https://github.com/uc-cfss). Once you register your GitHub account, I will invite you to join the course organization. If you don't register your account, you won't have access to any of the homework assignments.
* Complete your peer evaluations for homework 01. Review the following:
    * [General Homework Rubric](https://cfss.uchicago.edu/hw00_homework_grading.html)
    * [Performing peer review](https://cfss.uchicago.edu/hw00_peer-review.html)
    * To find which peers you will evaluate:
        * Navigate to the [pull request page for `hw01`](https://github.com/uc-cfss/hw01/pulls)
        * Click **Reviews** > **Awaiting review from you**
        * If you submitted your pull request on-time, you were randomly assigned two other pull requests to evaluate. If you did not submit your pull request on-time, you are still expected to perform two peer evaluations. Select any two pull requests and provide feedback on their submission.
