---
title: "Data wrangling: tidy data"
author: |
  | MACS 30500
  | University of Chicago
output: rcfss::cfss_slides
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE,
                      message = FALSE,
                      warning = FALSE)

set.seed(1234)

library(tidyverse)
theme_set(theme_minimal(base_size = 24))
```

## `readr` vs. base R

```{r compare-speed-small, dependson = "data-gen", message = FALSE, echo = FALSE}
library(microbenchmark)

results_small <- microbenchmark(
  read.csv = read.csv("../data/sim-data-small.csv"),
  read_csv = read_csv("../data/sim-data-small.csv")
)
```

```{r compare-speed-small-plot, dependson = "compare-speed-small", message = FALSE, echo = FALSE}
autoplot(results_small) +
  scale_y_log10(breaks = c(25, 50, 100)) +
  labs(y = "Time [milliseconds], logged",
       subtitle = "50,000 observations")
```

## `readr` vs. base R

```{r compare-speed-large, dependson = "data-gen", message = FALSE, echo = FALSE}
library(microbenchmark)

results_large <- microbenchmark(
  read.csv = read.csv("../data/sim-data-large.csv"),
  read_csv = read_csv("../data/sim-data-large.csv")
)
```

```{r compare-speed-large-plot, dependson = "compare-speed-large", message = FALSE, echo = FALSE}
autoplot(results_large) +
  scale_y_log10(breaks = c(2.5, 5, 10, 20)) +
  labs(y = "Time [seconds], logged",
       subtitle = "5,000,000 observations")
```

## Alternative file formats

* CSV
* RDS
* Feather
* Excel
* SPSS/Stata

----

```{r challenge, echo = FALSE}
challenge <- read_csv(
  readr_example("challenge.csv"), 
  col_types = cols(
    x = col_double(),
    y = col_date()
  )
)

challenge
```

## RDS {.scrollable}

```{r rds, dependson = "challenge", message = FALSE, echo = FALSE}
# write to csv
write_csv(challenge, "../data/challenge.csv")

# write to/read from rds
write_rds(challenge, "../data/challenge.rds")
read_rds("../data/challenge.rds")
```

```{r rds-2, dependson = "challenge", message = FALSE}
# compare file size
file.info("../data/challenge.csv")$size %>%
  utils:::format.object_size("auto")

file.info("../data/challenge.rds")$size %>%
  utils:::format.object_size("auto")
```

```{r rds-3, dependson = "challenge", echo = FALSE}
# compare read speeds
microbenchmark(
  read_csv = read_csv(
    readr_example("challenge.csv"), 
    col_types = cols(
      x = col_double(),
      y = col_date()
    )
  ),
  read_rds = read_rds("../data/challenge.rds")
) %>%
  autoplot +
  scale_y_continuous(labels = scales::comma) +
  labs(y = "Time [microseconds], logged")
```

## `feather`

```{r feather, dependson = "challenge", include = FALSE}
library(feather)

write_feather(challenge, "../data/challenge.feather")
read_feather("../data/challenge.feather")
```

```{r feather-2, dependson = "challenge", message = FALSE, echo = FALSE}
# compare read speeds
microbenchmark(
  read_csv = read_csv(
    readr_example("challenge.csv"), 
    col_types = cols(
      x = col_double(),
      y = col_date()
    )
  ),
  read_rds = read_rds("../data/challenge.rds"),
  read_feather = read_feather("../data/challenge.feather")
) %>%
  autoplot +
  labs(y = "Time [microseconds], logged")
```

## `readxl` {.scrollable}

```{r readxl}
library(readxl)

xlsx_example <- readxl_example("datasets.xlsx")
read_excel(xlsx_example)
```

```{r readxl-sheets, dependson = "readxl"}
excel_sheets(xlsx_example)
```

```{r readxl-select-sheet, dependson = "readxl"}
read_excel(xlsx_example, sheet = "chickwts")
read_excel(xlsx_example, sheet = 2)
```

## `haven` {.scrollable}

```{r haven}
library(haven)

# SAS
read_sas(system.file("examples", "iris.sas7bdat", package = "haven"))
write_sas(mtcars, "../data/mtcars.sas7bdat")

# SPSS
read_sav(system.file("examples", "iris.sav", package = "haven"))
write_sav(mtcars, "../data/mtcars.sav")

# Stata
read_dta(system.file("examples", "iris.dta", package = "haven"))
write_dta(mtcars, "../data/mtcars.dta")
```

## Tidy data

![Figure 12.1 from [@hadley2016]](http://r4ds.had.co.nz/images/tidy-1.png)

## Common tidying tasks

* Gathering
* Spreading
* Separating
* Uniting

## Gathering

```{r spread-columns}
table4a
```

## Gathering

```{r spread-columns}
```

```{r gather}
table4a %>% 
  gather(`1999`, `2000`, key = year, value = cases)
```

## Spreading {.scrollable}

```{r spread-rows}
table2
```

## Spreading

```{r spread-rows}
```

```{r spread}
table2 %>%
  spread(key = type, value = count)
```

## Separating

```{r merged-columns}
table3
```

## Separating

```{r merged-columns}
```

```{r separate}
table3 %>% 
  separate(rate, into = c("cases", "population"))
```

## Uniting

```{r merged-rows}
table5
```

## Uniting {.scrollable}

```{r merged-rows}
```

```{r unite}
table5 %>% 
  unite(new, century, year)

# remove underscore
table5 %>% 
  unite(new, century, year, sep = "")
```
