---
title: "Presenting academic research"
author: |
  | MACS 30200
  | University of Chicago
output: rcfss::cfss_slides
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      echo = FALSE)

library(tidyverse)
library(broom)
library(forcats)
library(modelr)
library(stringr)
library(car)
library(rcfss)
library(coefplot)
library(RColorBrewer)
library(lme4)

options(digits = 3)
set.seed(1234)
theme_set(theme_minimal(base_size = 22))
```

## Presenting at conferences

* Journal article/research paper
* Oral presentations
    * Paper panels
    * Lightning talks
* Poster presentations

## Goals of a research poster

* Extended abstract
* Snapshot of your research
    * More in-depth than an abstract
    * Less in-depth than the full paper
* Designing a good poster is tough

## Must haves

* Title
* Introduction
* Data and methods
* Results
* Conclusions
* Contact information

## Optional

* Literature cited
* Acknowledgements

## What not to include

* Abstract
* Verbatim text

## Helpful tips

* Don't reproduce the paper
* Keep the words to a minimum
* Choose your words carefully (informative phrases)
* Have a logical flow
* Make the poster legible
* Visualize your results
    * Functional
    * Pretty

## Examples of scientific posters

* [A bad poster](https://s-media-cache-ak0.pinimg.com/originals/18/1a/6c/181a6cd948f5f0ac02bdd0509db90779.jpg)
* [Do decisions follow dollars? Campaign contributions and state supreme court decisions](https://github.com/UC-MACSS/persp-research/raw/master/demos/poster-example-1.pdf)
* [A matched case analysis of Supreme Court behavior under mandatory and discretionary jurisdiction](https://github.com/UC-MACSS/persp-research/raw/master/demos/poster-example-2.pdf)

## Presenting the poster

* Don't just set it up and leave
* Prepare an oral pitch for your project
* Don't read from your poster
* Behave professionally

## Research poster templates

* Powerpoint
    * [UChicago template](https://github.com/UC-MACSS/persp-research/blob/master/demos/E-Poster%20Template%20Academic%20conference.ppt)
    * [Poster Presentations templates](https://www.posterpresentations.com/html/free_poster_templates.html)
* $\LaTeX$
    * [$\LaTeX$ poster template](http://www.brian-amberg.de/uni/poster/)
    * [`beamerposter`](https://github.com/deselaers/latex-beamerposter)
* R Markdown
    * [`flexdashboard` poster](https://github.com/odeleongt/flexdashboard-poster)
    * [`drposter`](https://github.com/bbucior/drposter)

## Printing posters

* Render as PDF
* Proof-read the poster
* Lamination
* Foam core backing

## Poster size

* 36 x 48 inches
* 48 x 60 inches
* More poster, more money
* Landscape vs. portrait orientation

## Where to print the poster

* [Booth School print shop](https://facilities.chicagobooth.edu/old/poster&banner.htm)
    * \$28 for a 36 x 48 laminated poster
    * 72 hour turnaround
* [John Crerar Library - PSD Graphic Arts](http://graphicarts.uchicago.edu/)
    * \$50ish for a 24 x 36 inch non-laminated poster
    * \$85 for a 36 x 48 inch non-laminated poster
    * 24 hour turnaround
    * Cash or check only
* [Fedex Office](http://www.fedex.com/us/office/) at 1315 E 57th St
    * Starting at \$43.50 for 24 x 36 inch non-laminated poster
    * Starting at \$87 for 36 x 48 inch non-laminated poster
    * 24 hour turnaround

## Grading rubric

1. Overall design/layout (10 points)
    * Clarity
    * Organization
    * Structure/flow
    * Use of color
    * Parsimony and efficiency of language
1. Visualization (10 points)
    * Plots
    * Tables
1. Content (10 points)
    * What is the question?
    * What is the answer?
    * How did you answer the question?
    * How strong is the evidence?


